// Example usage - Complete Nucleic Acids Workbook with Diagrams and DOCX Export
import { EnhancedMolecularBiologyWorkbook } from './molecularbiology.js';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, ImageRun, AlignmentType, WidthType, BorderStyle } from 'docx';
import fs from 'fs';
import path from 'path';

// ========================================
// DOCX EXPORTER CLASS
// ========================================
class MolecularBiologyDocxExporter {
    constructor(workbookResult) {
        this.result = workbookResult;
        this.content = workbookResult.content;
        this.workbook = workbookResult.workbook;
        this.diagrams = workbookResult.diagrams;
    }

    async exportToDocx(outputPath) {
        console.log(`   📝 Creating DOCX document...`);
        const sections = [];

        // Title Page
        sections.push(...this.createTitlePage());

        // Table of Contents placeholder
        sections.push(
            new Paragraph({
                text: 'Table of Contents',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: '(Contents will be generated by Word)',
                spacing: { after: 400 }
            })
        );

        // Process each workbook section
        console.log(`   📚 Processing ${this.workbook.sections.length} sections...`);
        for (const section of this.workbook.sections) {
            sections.push(...await this.createSection(section));
        }

        // Add diagrams section with embedded images
        if (this.diagrams?.renderedImages?.length > 0) {
            console.log(`   🎨 Adding ${this.diagrams.renderedImages.length} diagrams...`);
            sections.push(...await this.createDiagramsSection());
        }

        // Create document
        console.log(`   💾 Writing DOCX file...`);
        const doc = new Document({
            sections: [{
                properties: {
                    page: {
                        margin: {
                            top: 1440,
                            right: 1440,
                            bottom: 1440,
                            left: 1440
                        }
                    }
                },
                children: sections
            }]
        });

        // Write to file
        const buffer = await Packer.toBuffer(doc);
        fs.writeFileSync(outputPath, buffer);
        
        console.log(`   ✅ DOCX exported to ${outputPath}`);
        return outputPath;
    }

    createTitlePage() {
        return [
            new Paragraph({
                text: this.workbook.title || 'Molecular Biology Workbook',
                heading: HeadingLevel.TITLE,
                alignment: AlignmentType.CENTER,
                spacing: { before: 2000, after: 400 }
            }),
            new Paragraph({
                text: this.content.topic || 'Molecular Biology',
                heading: HeadingLevel.HEADING_1,
                alignment: AlignmentType.CENTER,
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: `Category: ${this.content.category || 'N/A'}`,
                alignment: AlignmentType.CENTER,
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: `Generated: ${new Date().toLocaleDateString()}`,
                alignment: AlignmentType.CENTER,
                spacing: { after: 400 }
            }),
            new Paragraph({
                text: '',
                pageBreakBefore: true
            })
        ];
    }

    async createSection(section) {
        const paragraphs = [];

        // Section title
        paragraphs.push(
            new Paragraph({
                text: section.title,
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            })
        );

        // Handle different section types
        switch (section.type) {
            case 'problem':
            case 'overview':
            case 'detailed_content':
            case 'comparisons':
            case 'examples_applications':
            case 'contextual':
            case 'experiments':
            case 'misconceptions':
            case 'metacognitive':
            case 'assessment':
            case 'related_topics':
                if (section.data && Array.isArray(section.data)) {
                    paragraphs.push(...this.createContentFromData(section.data));
                }
                break;

            case 'diagrams':
                paragraphs.push(...await this.createDiagramsSectionContent(section));
                break;

            default:
                paragraphs.push(
                    new Paragraph({
                        text: 'Section content...',
                        spacing: { after: 200 }
                    })
                );
        }

        // Add relevant diagrams after this section
        if (this.shouldAddDiagramsAfterSection(section)) {
            paragraphs.push(...await this.addRelevantDiagrams(section));
        }

        return paragraphs;
    }

    createContentFromData(data) {
        const paragraphs = [];

        for (const row of data) {
            if (!row || row.length === 0) {
                paragraphs.push(new Paragraph({ text: '', spacing: { after: 100 } }));
            } else if (row[0] && row[0].toUpperCase() === row[0] && row[0].length > 0 && (!row[1] || row[1] === '')) {
                // Header
                paragraphs.push(
                    new Paragraph({
                        text: row[0],
                        heading: HeadingLevel.HEADING_2,
                        spacing: { before: 200, after: 100 }
                    })
                );
            } else if (row[0] && row[0].startsWith('  ')) {
                // Bullet point
                paragraphs.push(
                    new Paragraph({
                        text: row.join(' ').trim(),
                        bullet: { level: 0 },
                        spacing: { after: 100 }
                    })
                );
            } else {
                // Regular paragraph
                paragraphs.push(
                    new Paragraph({
                        children: [
                            new TextRun({ text: String(row[0] || ''), bold: true }),
                            new TextRun({ text: ': ' }),
                            new TextRun({ text: String(row[1] || '') })
                        ],
                        spacing: { after: 100 }
                    })
                );
            }
        }

        return paragraphs;
    }

    shouldAddDiagramsAfterSection(section) {
        const relevantSections = ['overview', 'detailed_content', 'comparisons'];
        return relevantSections.includes(section.type);
    }

    async addRelevantDiagrams(section) {
        const paragraphs = [];
        
        if (!this.diagrams?.renderedImages || this.diagrams.renderedImages.length === 0) {
            return paragraphs;
        }

        const relevantDiagrams = this.diagrams.renderedImages.slice(0, 2);

        if (relevantDiagrams.length === 0) {
            return paragraphs;
        }

        paragraphs.push(
            new Paragraph({
                text: 'Related Diagrams',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 300, after: 200 }
            })
        );

        for (const diagram of relevantDiagrams) {
            if (diagram.type === 'image') {
                paragraphs.push(...await this.createDiagramParagraph(diagram));
            }
        }

        return paragraphs;
    }

    async createDiagramParagraph(diagram) {
        const paragraphs = [];

        try {
            if (diagram.type === 'image' && diagram.buffer) {
                paragraphs.push(
                    new Paragraph({
                        text: this.formatDiagramTitle(diagram.key),
                        heading: HeadingLevel.HEADING_3,
                        spacing: { before: 200, after: 100 }
                    })
                );

                const maxWidth = 6 * 914400;
                const aspectRatio = diagram.height / diagram.width;
                const width = maxWidth;
                const height = Math.round(width * aspectRatio);

                paragraphs.push(
                    new Paragraph({
                        children: [
                            new ImageRun({
                                data: diagram.buffer,
                                transformation: {
                                    width: width,
                                    height: height
                                }
                            })
                        ],
                        alignment: AlignmentType.CENTER,
                        spacing: { after: 200 }
                    })
                );

                paragraphs.push(
                    new Paragraph({
                        text: `Figure: ${this.formatDiagramTitle(diagram.key)}`,
                        alignment: AlignmentType.CENTER,
                        italics: true,
                        spacing: { after: 300 }
                    })
                );
            }
        } catch (error) {
            console.error(`   ⚠️  Error adding diagram ${diagram.key}:`, error.message);
        }

        return paragraphs;
    }

    async createDiagramsSection() {
        const paragraphs = [];

        paragraphs.push(
            new Paragraph({
                text: 'Molecular Diagrams',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 },
                pageBreakBefore: true
            })
        );

        for (const diagram of this.diagrams.renderedImages) {
            if (diagram.type === 'image') {
                paragraphs.push(...await this.createDiagramParagraph(diagram));
            }
        }

        return paragraphs;
    }

    async createDiagramsSectionContent(section) {
        const paragraphs = [];

        if (section.diagrams) {
            for (const diagram of section.diagrams) {
                if (diagram.type === 'image') {
                    paragraphs.push(...await this.createDiagramParagraph(diagram));
                }
            }
        }

        return paragraphs;
    }

    formatDiagramTitle(key) {
        return key
            .replace(/([A-Z])/g, ' $1')
            .replace(/_/g, ' ')
            .trim()
            .split(' ')
            .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join(' ');
    }
}

// ========================================
// HELPER FUNCTIONS
// ========================================
async function exportDiagrams(result, outputDir) {
    if (!result.diagrams?.renderedImages) {
        console.log('   ⚠️  No diagrams to export');
        return;
    }
    
    const diagramDir = path.join(outputDir, 'diagrams');
    if (!fs.existsSync(diagramDir)) {
        fs.mkdirSync(diagramDir, { recursive: true });
    }
    
    let exportedCount = 0;
    for (const diagram of result.diagrams.renderedImages) {
        if (diagram.type === 'image' && diagram.buffer) {
            const filepath = path.join(diagramDir, `${diagram.key}.png`);
            fs.writeFileSync(filepath, diagram.buffer);
            exportedCount++;
        }
    }
    
    console.log(`   💾 Exported ${exportedCount} PNG diagrams to ${diagramDir}`);
}

async function exportWithDocx(result, outputDir) {
    console.log(`\n   📦 Exporting to ${outputDir}...`);
    
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }
    
    // Export diagrams as PNG files
    await exportDiagrams(result, outputDir);
    
    // Export to DOCX with embedded diagrams
    const docxPath = path.join(outputDir, 'workbook.docx');
    const exporter = new MolecularBiologyDocxExporter(result);
    await exporter.exportToDocx(docxPath);
    
    // Export content JSON
    const contentPath = path.join(outputDir, 'content.json');
    fs.writeFileSync(contentPath, JSON.stringify(result.content, null, 2));
    console.log(`   💾 Content JSON saved`);
    
    // Create summary
    const summary = {
        generated: new Date().toISOString(),
        topic: result.content.topic,
        category: result.content.category,
        diagramCount: result.diagrams?.renderedImages?.length || 0,
        diagrams: result.diagrams?.renderedImages?.map(d => d.key) || [],
        exports: {
            docx: 'workbook.docx',
            content: 'content.json',
            diagrams: 'diagrams/'
        }
    };
    
    const summaryPath = path.join(outputDir, 'summary.json');
    fs.writeFileSync(summaryPath, JSON.stringify(summary, null, 2));
    console.log(`   💾 Summary JSON saved`);
    
    console.log(`   ✅ Export complete!\n`);
}

// ========================================
// MAIN DEMONSTRATION FUNCTION
// ========================================
async function demonstrateWorkbookWithDiagrams() {
    console.log('\n' + '='.repeat(80));
    console.log('NUCLEIC ACIDS WORKBOOK - COMPLETE DEMONSTRATION');
    console.log('Content Generation + Diagrams + DOCX Export');
    console.log('='.repeat(80) + '\n');

    try {
        // Step 1: Create workbook instance
        console.log('📚 Step 1: Creating workbook instance with all features enabled...');
        const workbook = new EnhancedMolecularBiologyWorkbook({
            theme: 'molecular',
            includeDiagrams: true,
            diagramWidth: 800,
            diagramHeight: 600,
            includeExperiments: true,
            metacognitiveSupport: true,
            contextualLearning: true,
            includeComparisons: true,
            includeExamples: true,
            includeCommonMisconceptions: true,
            explanationLevel: 'detailed'
        });
        console.log('✅ Workbook instance created\n');

        // Step 2: Generate nucleic acids content
        console.log('🧬 Step 2: Generating nucleic acids content...');
        const result = await workbook.handleMolecularProblem({
            topic: 'nucleic_acids',
            parameters: {},
            context: {}
        });
        console.log('✅ Content generated\n');

        // Step 3: Display content summary
        console.log('📊 Step 3: Content Summary');
        console.log('─'.repeat(80));
        console.log(`Topic: ${result.content.topic}`);
        console.log(`Category: ${result.content.category}`);
        console.log(`Summary: ${result.content.summary.substring(0, 100)}...`);
        
        // Display content structure
        console.log('\n📚 Content Structure:');
        const contentSections = Object.keys(result.content).filter(
            key => !['topic', 'category', 'summary'].includes(key)
        );
        contentSections.forEach(section => {
            console.log(`   ✓ ${section}`);
        });

        // Display workbook sections
        console.log(`\n📖 Workbook Sections (${result.workbook.sections.length}):${result.workbook.sections.length}):`);
        result.workbook.sections.forEach(section => {
            console.log(`   • ${section.title} (${section.type})`);
        });

        // Step 4: Display diagram information
        console.log('\n🎨 Step 4: Diagram Information');
        console.log('─'.repeat(80));
        console.log(`Number of diagrams: ${result.diagrams?.renderedImages?.length || 0}\n`);

        if (result.diagrams && result.diagrams.renderedImages) {
            console.log('Diagrams generated:');
            for (const diagram of result.diagrams.renderedImages) {
                if (diagram.type === 'image') {
                    console.log(`   ✓ ${diagram.key} (${diagram.width}x${diagram.height}px)`);
                } else if (diagram.type === 'error') {
                    console.log(`   ✗ ${diagram.key} - Error: ${diagram.error}`);
                }
            }
        }

        // Step 5: Display specific content details
        console.log('\n🔬 Step 5: Nucleic Acids Content Details');
        console.log('─'.repeat(80));

        // Nucleotide Structure
        if (result.content.nucleotideStructure) {
            console.log('\n📌 Nucleotide Components:');
            const components = result.content.nucleotideStructure.components;
            console.log(`   • Pentose Sugar: DNA (${components.pentoseSugar.DNA.sugar}) / RNA (${components.pentoseSugar.RNA.sugar})`);
            console.log(`   • Nitrogenous Bases:`);
            console.log(`     - Purines: ${components.nitrogenousBase.purines.bases.adenine.abbreviation}, ${components.nitrogenousBase.purines.bases.guanine.abbreviation}`);
            console.log(`     - Pyrimidines: ${components.nitrogenousBase.pyrimidines.bases.cytosine.abbreviation}, ${components.nitrogenousBase.pyrimidines.bases.thymine.abbreviation}, ${components.nitrogenousBase.pyrimidines.bases.uracil.abbreviation}`);
            console.log(`   • Phosphate Group: ${components.phosphateGroup.structure}`);
        }

        // DNA Structure
        if (result.content.DNAStructure) {
            console.log('\n📌 DNA Structure:');
            const dna = result.content.DNAStructure.doubleHelix;
            console.log(`   • Discoverers: ${dna.discoverers}`);
            console.log(`   • Structure: ${dna.features.helix}`);
            console.log(`   • Diameter: ${dna.features.diameter}`);
            console.log(`   • Base Pairing: A-T (${result.content.DNAStructure.basePairing.complementarity.AT.bonds}), G-C (${result.content.DNAStructure.basePairing.complementarity.GC.bonds})`);
        }

        // Central Dogma
        if (result.content.centralDogma) {
            console.log('\n📌 Central Dogma:');
            const dogma = result.content.centralDogma;
            console.log(`   • Concept: ${dogma.concept}`);
            console.log(`   • Main Flow: ${dogma.mainFlow}`);
            console.log(`   • Replication: ${dogma.replication.process} - ${dogma.replication.purpose}`);
            console.log(`   • Transcription: ${dogma.transcription.process} - ${dogma.transcription.purpose}`);
            console.log(`   • Translation: ${dogma.translation.process} - ${dogma.translation.purpose}`);
        }

        // Genetic Code
        if (result.content.geneticCode) {
            console.log('\n📌 Genetic Code Features:');
            const code = result.content.geneticCode.features;
            Object.entries(code).forEach(([key, value]) => {
                console.log(`   • ${key}: ${value}`);
            });
        }

        // DNA vs RNA Comparison
        if (result.content.DNAvsRNA) {
            console.log('\n📌 DNA vs RNA Comparison:');
            result.content.DNAvsRNA.comparison.slice(0, 5).forEach(comp => {
                console.log(`   • ${comp.feature}:`);
                console.log(`     - DNA: ${comp.DNA}`);
                console.log(`     - RNA: ${comp.RNA}`);
            });
        }

        // Step 6: Export all diagrams
        console.log('\n💾 Step 6: Exporting diagrams to files...');
        console.log('─'.repeat(80));
        const exportResults = await workbook.exportAllDiagramsForTopic('./output/diagrams');
        console.log(`Exported ${exportResults.length} diagrams:`);
        exportResults.forEach(result => {
            if (result.success) {
                console.log(`   ✓ ${result.diagramKey} → ${result.filename}`);
            } else {
                console.log(`   ✗ ${result.diagramKey} - Error: ${result.error}`);
            }
        });

        // Step 7: Cache statistics
        console.log('\n📊 Step 7: Cache Statistics');
        console.log('─'.repeat(80));
        const cacheStats = workbook.getDiagramCacheStats();
        console.log(`Cached diagrams: ${cacheStats.cachedDiagrams}`);
        console.log('Cache keys:');
        cacheStats.cacheKeys.forEach(key => {
            console.log(`   • ${key}`);
        });

        // Step 8: Export to DOCX with embedded diagrams
        console.log('\n📄 Step 8: Exporting complete workbook to DOCX...');
        console.log('─'.repeat(80));
        await exportWithDocx(result, './output/complete_nucleic_acids');

        // Final Summary
        console.log('\n' + '='.repeat(80));
        console.log('✅ DEMONSTRATION COMPLETED SUCCESSFULLY!');
        console.log('='.repeat(80));
        console.log('\n📂 Output Files:');
        console.log('   ./output/complete_nucleic_acids/');
        console.log('   ├── workbook.docx (Complete workbook with embedded diagrams)');
        console.log('   ├── content.json (Full content data)');
        console.log('   ├── summary.json (Quick reference)');
        console.log('   └── diagrams/ (Individual PNG files)');
        console.log('\n   ./output/diagrams/ (Separate diagram exports)');
        console.log('\n💡 Open workbook.docx to view the complete molecular biology workbook!');
        console.log('   All content sections with embedded diagrams after relevant sections.\n');

        return result;

    } catch (error) {
        console.error('\n❌ ERROR:', error.message);
        console.error('Stack trace:', error.stack);
        throw error;
    }
}

// ========================================
// EXPORT SPECIFIC DIAGRAM FUNCTION
// ========================================
async function exportSpecificDiagram() {
    console.log('\n' + '='.repeat(80));
    console.log('EXPORT SPECIFIC DIAGRAM');
    console.log('='.repeat(80) + '\n');

    try {
        const workbook = new EnhancedMolecularBiologyWorkbook();

        console.log('📊 Exporting DNA Structure diagram...');
        const result = await workbook.exportDiagram(
            'dnaStructure',
            './output/dna_structure.png',
            {
                width: 1200,
                height: 800,
                showLabels: true,
                backgroundColor: '#FFFFFF'
            }
        );

        if (result.success) {
            console.log(`✅ Successfully exported to: ${result.filename}\n`);
        } else {
            console.log(`❌ Export failed: ${result.error}\n`);
        }

        return result;

    } catch (error) {
        console.error('\n❌ ERROR:', error.message);
        throw error;
    }
}


// ========================================
// EXPERIMENT DEMONSTRATION FUNCTION
// ========================================
// ========================================
// UPDATED: COMPLETE DEMONSTRATION WITH EXPERIMENT AND DIAGRAMS
// ========================================
async function demonstrateWorkbookWithExperiment() {
    console.log('\n' + '='.repeat(80));
    console.log('NUCLEIC ACIDS + FISCHER EXPERIMENT WORKBOOK');
    console.log('Content + Experiment + Diagrams + DOCX Export');
    console.log('='.repeat(80) + '\n');

    try {
        // Step 1: Create workbook instance
        console.log('📚 Step 1: Creating workbook instance with all features enabled...');
        const workbook = new EnhancedMolecularBiologyWorkbook({
            theme: 'molecular',
            includeDiagrams: true,  // IMPORTANT: Enable diagrams
            diagramWidth: 800,
            diagramHeight: 600,
            includeExperiments: true,  // Enable experiments
            metacognitiveSupport: true,
            contextualLearning: true,
            includeComparisons: true,
            includeExamples: true,
            includeCommonMisconceptions: true,
            explanationLevel: 'detailed'
        });
        console.log('✅ Workbook instance created\n');

        // Step 2: Generate nucleic acids content WITH DIAGRAMS
        console.log('🧬 Step 2: Generating nucleic acids content with diagrams...');
        const result = await workbook.handleMolecularProblem({
            topic: 'nucleic_acids',
            parameters: {},
            context: {}
        });
        console.log('✅ Content and diagrams generated\n');

        // Step 3: Display content summary
        console.log('📊 Step 3: Content Summary');
        console.log('─'.repeat(80));
        console.log(`Topic: ${result.content.topic}`);
        console.log(`Category: ${result.content.category}`);
        console.log(`Summary: ${result.content.summary.substring(0, 100)}...`);
        
        // Display content structure
        console.log('\n📚 Content Structure:');
        const contentSections = Object.keys(result.content).filter(
            key => !['topic', 'category', 'summary'].includes(key)
        );
        contentSections.forEach(section => {
            console.log(`   ✓ ${section}`);
        });

        // Display workbook sections
        console.log(`\n📖 Workbook Sections (${result.workbook.sections.length}):`);
        result.workbook.sections.forEach(section => {
            console.log(`   • ${section.title} (${section.type})`);
        });

        // Step 4: Display diagram information
        console.log('\n🎨 Step 4: Diagram Information');
        console.log('─'.repeat(80));
        console.log(`Number of diagrams: ${result.diagrams?.renderedImages?.length || 0}\n`);

        if (result.diagrams && result.diagrams.renderedImages) {
            console.log('Diagrams generated:');
            for (const diagram of result.diagrams.renderedImages) {
                if (diagram.type === 'image') {
                    console.log(`   ✓ ${diagram.key} (${diagram.width}x${diagram.height}px)`);
                } else if (diagram.type === 'error') {
                    console.log(`   ✗ ${diagram.key} - Error: ${diagram.error}`);
                }
            }
        }

        // Step 5: Display specific content details
        console.log('\n🔬 Step 5: Nucleic Acids Content Details');
        console.log('─'.repeat(80));

        // Nucleotide Structure
        if (result.content.nucleotideStructure) {
            console.log('\n📌 Nucleotide Components:');
            const components = result.content.nucleotideStructure.components;
            console.log(`   • Pentose Sugar: DNA (${components.pentoseSugar.DNA.sugar}) / RNA (${components.pentoseSugar.RNA.sugar})`);
            console.log(`   • Nitrogenous Bases:`);
            console.log(`     - Purines: ${components.nitrogenousBase.purines.bases.adenine.abbreviation}, ${components.nitrogenousBase.purines.bases.guanine.abbreviation}`);
            console.log(`     - Pyrimidines: ${components.nitrogenousBase.pyrimidines.bases.cytosine.abbreviation}, ${components.nitrogenousBase.pyrimidines.bases.thymine.abbreviation}, ${components.nitrogenousBase.pyrimidines.bases.uracil.abbreviation}`);
            console.log(`   • Phosphate Group: ${components.phosphateGroup.structure}`);
        }

        // DNA Structure
        if (result.content.DNAStructure) {
            console.log('\n📌 DNA Structure:');
            const dna = result.content.DNAStructure.doubleHelix;
            console.log(`   • Discoverers: ${dna.discoverers}`);
            console.log(`   • Structure: ${dna.features.helix}`);
            console.log(`   • Diameter: ${dna.features.diameter}`);
            console.log(`   • Base Pairing: A-T (${result.content.DNAStructure.basePairing.complementarity.AT.bonds}), G-C (${result.content.DNAStructure.basePairing.complementarity.GC.bonds})`);
        }

        // Central Dogma
        if (result.content.centralDogma) {
            console.log('\n📌 Central Dogma:');
            const dogma = result.content.centralDogma;
            console.log(`   • Concept: ${dogma.concept}`);
            console.log(`   • Main Flow: ${dogma.mainFlow}`);
            console.log(`   • Replication: ${dogma.replication.process} - ${dogma.replication.purpose}`);
            console.log(`   • Transcription: ${dogma.transcription.process} - ${dogma.transcription.purpose}`);
            console.log(`   • Translation: ${dogma.translation.process} - ${dogma.translation.purpose}`);
        }

        // Genetic Code
        if (result.content.geneticCode) {
            console.log('\n📌 Genetic Code Features:');
            const code = result.content.geneticCode.features;
            Object.entries(code).forEach(([key, value]) => {
                console.log(`   • ${key}: ${value}`);
            });
        }

        // DNA vs RNA Comparison
        if (result.content.DNAvsRNA) {
            console.log('\n📌 DNA vs RNA Comparison:');
            result.content.DNAvsRNA.comparison.slice(0, 5).forEach(comp => {
                console.log(`   • ${comp.feature}:`);
                console.log(`     - DNA: ${comp.DNA}`);
                console.log(`     - RNA: ${comp.RNA}`);
            });
        }

        // Step 6: Get Fischer Lock-and-Key Experiment
        console.log('\n🧪 Step 6: Adding Fischer Lock-and-Key Experiment...');
        console.log('─'.repeat(80));
        
        const fischerExperiment = workbook.molecularExperiments.fischer_lock_and_key;
        
        if (fischerExperiment) {
            console.log(`Experiment Name: ${fischerExperiment.name}`);
            console.log(`Category: ${fischerExperiment.category}`);
            console.log(`Related Topics: ${fischerExperiment.relatedTopics.join(', ')}`);
            
            // Display historical background
            if (fischerExperiment.historicalBackground) {
                console.log('\n📜 Historical Background:');
                const hist = fischerExperiment.historicalBackground;
                console.log(`   • Scientist: ${hist.scientist}`);
                console.log(`   • Year: ${hist.year}`);
                console.log(`   • Hypothesis: ${hist.hypothesis}`);
                console.log(`   • Nobel Prize: ${hist.nobelPrize}`);
                console.log(`   • Quote: "${hist.quote}"`);
            }
            
            // Display lab experiment details
            if (fischerExperiment.labExperiment) {
                console.log('\n🧪 Laboratory Experiment:');
                const lab = fischerExperiment.labExperiment;
                console.log(`   • Title: ${lab.title}`);
                console.log(`   • Hypothesis: ${lab.hypothesis}`);
                console.log(`   • Purpose: ${lab.purpose}`);
                
                // Display expected results
                if (lab.expectedResults) {
                    console.log('\n   Expected Results:');
                    console.log(`   • Starch + Amylase: ${lab.expectedResults.benedictsTest.starchPlusAmylase}`);
                    console.log(`   • Cellulose + Amylase: ${lab.expectedResults.benedictsTest.cellulosePlusAmylase}`);
                }
                
                // Display conclusions
                if (lab.conclusions) {
                    console.log('\n   Key Conclusions:');
                    lab.conclusions.slice(0, 3).forEach(conclusion => {
                        console.log(`   • ${conclusion}`);
                    });
                }
            }
            
            console.log('\n✅ Experiment data retrieved\n');
        } else {
            console.log('⚠️  Fischer experiment not found\n');
        }

        // Step 7: Export all diagrams to files
        console.log('💾 Step 7: Exporting diagrams to files...');
        console.log('─'.repeat(80));
        const exportResults = await workbook.exportAllDiagramsForTopic('./output/diagrams');
        console.log(`Exported ${exportResults.length} diagrams:`);
        exportResults.forEach(exportResult => {
            if (exportResult.success) {
                console.log(`   ✓ ${exportResult.diagramKey} → ${exportResult.filename}`);
            } else {
                console.log(`   ✗ ${exportResult.diagramKey} - Error: ${exportResult.error}`);
            }
        });

        // Step 8: Cache statistics
        console.log('\n📊 Step 8: Cache Statistics');
        console.log('─'.repeat(80));
        const cacheStats = workbook.getDiagramCacheStats();
        console.log(`Cached diagrams: ${cacheStats.cachedDiagrams}`);
        console.log('Cache keys:');
        cacheStats.cacheKeys.forEach(key => {
            console.log(`   • ${key}`);
        });

        // Step 9: Prepare combined result with experiment
        console.log('\n📦 Step 9: Preparing combined workbook...');
        console.log('─'.repeat(80));
        
        // Add experiment to result (diagrams are already included from handleMolecularProblem)
        const combinedResult = {
            ...result,
            experiment: fischerExperiment
        };
        
        console.log('✅ Combined result prepared');
        console.log(`   • Content sections: ${Object.keys(combinedResult.content).length}`);
        console.log(`   • Diagrams: ${combinedResult.diagrams?.renderedImages?.length || 0}`);
        console.log(`   • Experiment: ${combinedResult.experiment ? 'Included' : 'Not included'}`);
        console.log('');

        // Step 10: Export to DOCX with experiment AND diagrams
        console.log('📄 Step 10: Exporting complete workbook to DOCX...');
        console.log('─'.repeat(80));
        await exportWithExperiment(combinedResult, './output/nucleic_acids_with_experiment');

        // Final Summary
        console.log('\n' + '='.repeat(80));
        console.log('✅ COMPLETE WORKBOOK GENERATED SUCCESSFULLY!');
        console.log('='.repeat(80));
        console.log('\n📂 Output Files:');
        console.log('   ./output/nucleic_acids_with_experiment/');
        console.log('   ├── workbook.docx (Content + Experiment + Diagrams)');
        console.log('   ├── content.json (Nucleic acids content)');
        console.log('   ├── experiment.json (Fischer experiment data)');
        console.log('   ├── summary.json (Quick reference)');
        console.log('   └── diagrams/ (Individual PNG files)');
        console.log('\n   ./output/diagrams/ (Separate diagram exports)');
        console.log('\n💡 Open workbook.docx to view:');
        console.log('   ✓ Complete nucleic acids content');
        console.log('   ✓ Fischer Lock-and-Key experiment (historical + lab)');
        console.log('   ✓ All diagrams embedded throughout the document');
        console.log('\n📊 Summary:');
        console.log(`   • Content Sections: ${Object.keys(combinedResult.content).length}`);
        console.log(`   • Workbook Sections: ${combinedResult.workbook.sections.length}`);
        console.log(`   • Diagrams Generated: ${combinedResult.diagrams?.renderedImages?.length || 0}`);
        console.log(`   • Experiment Included: ${combinedResult.experiment ? 'Yes ✓' : 'No ✗'}`);
        console.log('');

        return combinedResult;

    } catch (error) {
        console.error('\n❌ ERROR:', error.message);
        console.error('Stack trace:', error.stack);
        throw error;
    }
}

// ========================================
// EXPORT WITH EXPERIMENT FUNCTION
// ========================================
async function exportWithExperiment(result, outputDir) {
    console.log(`\n   📦 Exporting to ${outputDir}...`);

    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    // Export diagrams as PNG files
    await exportDiagrams(result, outputDir);

    // Export to DOCX with embedded diagrams AND experiment
    const docxPath = path.join(outputDir, 'workbook.docx');
    const exporter = new MolecularBiologyDocxExporterWithExperiment(result);
    await exporter.exportToDocx(docxPath);

    // Export content JSON
    const contentPath = path.join(outputDir, 'content.json');
    fs.writeFileSync(contentPath, JSON.stringify(result.content, null, 2));
    console.log(`   💾 Content JSON saved`);

    // Export experiment JSON
    if (result.experiment) {
        const experimentPath = path.join(outputDir, 'experiment.json');
        fs.writeFileSync(experimentPath, JSON.stringify(result.experiment, null, 2));
        console.log(`   💾 Experiment JSON saved`);
    }

    // Create summary
    const summary = {
        generated: new Date().toISOString(),
        topic: result.content.topic,
        category: result.content.category,
        diagramCount: result.diagrams?.renderedImages?.length || 0,
        hasExperiment: !!result.experiment,
        experimentName: result.experiment?.name || 'N/A',
        diagrams: result.diagrams?.renderedImages?.map(d => d.key) || [],
        exports: {
            docx: 'workbook.docx',
            content: 'content.json',
            experiment: 'experiment.json',
            diagrams: 'diagrams/'
        }
    };

    const summaryPath = path.join(outputDir, 'summary.json');
    fs.writeFileSync(summaryPath, JSON.stringify(summary, null, 2));
    console.log(`   💾 Summary JSON saved`);

    console.log(`   ✅ Export complete!\n`);
}

// ========================================
// EXTENDED DOCX EXPORTER WITH EXPERIMENT
// ========================================
class MolecularBiologyDocxExporterWithExperiment extends MolecularBiologyDocxExporter {
    constructor(workbookResult) {
        super(workbookResult);
        this.experiment = workbookResult.experiment;
    }

    async exportToDocx(outputPath) {
        console.log(`   📝 Creating DOCX document with experiment...`);
        const sections = [];

        // Title Page
        sections.push(...this.createTitlePage());

        // Table of Contents
        sections.push(
            new Paragraph({
                text: 'Table of Contents',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: '(Contents will be generated by Word)',
                spacing: { after: 400 }
            })
        );

        // Process workbook sections
        console.log(`   📚 Processing ${this.workbook.sections.length} content sections...`);
        for (const section of this.workbook.sections) {
            sections.push(...await this.createSection(section));
        }

        // Add experiment section
        if (this.experiment) {
            console.log(`   🔬 Adding experiment section...`);
            sections.push(...this.createExperimentSection());
        }

        // Add diagrams section
        if (this.diagrams?.renderedImages?.length > 0) {
            console.log(`   🎨 Adding ${this.diagrams.renderedImages.length} diagrams...`);
            sections.push(...await this.createDiagramsSection());
        }

        // Create document
        console.log(`   💾 Writing DOCX file...`);
        const doc = new Document({
            sections: [{
                properties: {
                    page: {
                        margin: {
                            top: 1440,
                            right: 1440,
                            bottom: 1440,
                            left: 1440
                        }
                    }
                },
                children: sections
            }]
        });

        const buffer = await Packer.toBuffer(doc);
        fs.writeFileSync(outputPath, buffer);

        console.log(`   ✅ DOCX exported to ${outputPath}`);
        return outputPath;
    }

    createExperimentSection() {
        const paragraphs = [];

        // Page break before experiment
        paragraphs.push(
            new Paragraph({
                text: '',
                pageBreakBefore: true
            })
        );

        // Experiment title
        paragraphs.push(
            new Paragraph({
                text: 'Related Experiment',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            })
        );

        paragraphs.push(
            new Paragraph({
                text: this.experiment.name,
                heading: HeadingLevel.HEADING_2,
                spacing: { after: 200 }
            })
        );

        // Historical Background Section
        if (this.experiment.historicalBackground) {
            paragraphs.push(...this.createHistoricalBackgroundSection());
        }

        // Lab Experiment Section
        if (this.experiment.labExperiment) {
            paragraphs.push(...this.createLabExperimentSection());
        }

        return paragraphs;
    }

    createHistoricalBackgroundSection() {
        const paragraphs = [];
        const hist = this.experiment.historicalBackground;

        paragraphs.push(
            new Paragraph({
                text: 'Historical Background',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 300, after: 150 }
            })
        );

        // Scientist and year
        paragraphs.push(
            new Paragraph({
                children: [
                    new TextRun({ text: 'Scientist: ', bold: true }),
                    new TextRun({ text: hist.scientist })
                ],
                spacing: { after: 100 }
            })
        );

        paragraphs.push(
            new Paragraph({
                children: [
                    new TextRun({ text: 'Year: ', bold: true }),
                    new TextRun({ text: hist.year })
                ],
                spacing: { after: 100 }
            })
        );

        // Hypothesis
        paragraphs.push(
            new Paragraph({
                children: [
                    new TextRun({ text: 'Hypothesis: ', bold: true }),
                    new TextRun({ text: hist.hypothesis })
                ],
                spacing: { after: 100 }
            })
        );

        // Proposal
        if (hist.proposal) {
            paragraphs.push(
                new Paragraph({
                    children: [
                        new TextRun({ text: 'Proposal: ', bold: true }),
                        new TextRun({ text: hist.proposal })
                    ],
                    spacing: { after: 100 }
                })
            );
        }

        // Context
        if (hist.context) {
            paragraphs.push(
                new Paragraph({
                    children: [
                        new TextRun({ text: 'Context: ', bold: true }),
                        new TextRun({ text: hist.context })
                    ],
                    spacing: { after: 100 }
                })
            );
        }

        // Significance
        if (hist.significance) {
            paragraphs.push(
                new Paragraph({
                    children: [
                        new TextRun({ text: 'Significance: ', bold: true }),
                        new TextRun({ text: hist.significance })
                    ],
                    spacing: { after: 100 }
                })
            );
        }

        // Quote
        if (hist.quote) {
            paragraphs.push(
                new Paragraph({
                    text: `"${hist.quote}"`,
                    italics: true,
                    alignment: AlignmentType.CENTER,
                    spacing: { before: 150, after: 150 }
                })
            );
        }

        // Nobel Prize
        if (hist.nobelPrize) {
            paragraphs.push(
                new Paragraph({
                    children: [
                        new TextRun({ text: 'Nobel Prize: ', bold: true }),
                        new TextRun({ text: hist.nobelPrize })
                    ],
                    spacing: { after: 200 }
                })
            );
        }

        return paragraphs;
    }

    createLabExperimentSection() {
        const paragraphs = [];
        const lab = this.experiment.labExperiment;

        paragraphs.push(
            new Paragraph({
                text: 'Laboratory Experiment',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 300, after: 150 }
            })
        );

        // Title
        paragraphs.push(
            new Paragraph({
                text: lab.title,
                heading: HeadingLevel.HEADING_3,
                spacing: { after: 150 }
            })
        );

        // Hypothesis
        paragraphs.push(
            new Paragraph({
                children: [
                    new TextRun({ text: 'Hypothesis: ', bold: true }),
                    new TextRun({ text: lab.hypothesis })
                ],
                spacing: { after: 100 }
            })
        );

        // Purpose
        paragraphs.push(
            new Paragraph({
                children: [
                    new TextRun({ text: 'Purpose: ', bold: true }),
                    new TextRun({ text: lab.purpose })
                ],
                spacing: { after: 200 }
            })
        );

        // Background
        if (lab.background) {
            paragraphs.push(
                new Paragraph({
                    text: 'Background',
                    heading: HeadingLevel.HEADING_3,
                    spacing: { before: 200, after: 100 }
                })
            );

            Object.entries(lab.background).forEach(([key, value]) => {
                if (typeof value === 'string') {
                    paragraphs.push(
                        new Paragraph({
                            children: [
                                new TextRun({ text: `${key}: `, bold: true }),
                                new TextRun({ text: value })
                            ],
                            spacing: { after: 100 }
                        })
                    );
                }
            });
        }

        // Variables
        if (lab.variables) {
            paragraphs.push(
                new Paragraph({
                    text: 'Variables',
                    heading: HeadingLevel.HEADING_3,
                    spacing: { before: 200, after: 100 }
                })
            );

            Object.entries(lab.variables).forEach(([key, value]) => {
                const valueText = Array.isArray(value) ? value.join(', ') : value;
                paragraphs.push(
                    new Paragraph({
                        children: [
                            new TextRun({ text: `${key}: `, bold: true }),
                            new TextRun({ text: valueText })
                        ],
                        spacing: { after: 100 }
                    })
                );
            });
        }

        // Materials
        if (lab.materials) {
            paragraphs.push(
                new Paragraph({
                    text: 'Materials',
                    heading: HeadingLevel.HEADING_3,
                    spacing: { before: 200, after: 100 }
                })
            );

            lab.materials.forEach(material => {
                paragraphs.push(
                    new Paragraph({
                        text: material,
                        bullet: { level: 0 },
                        spacing: { after: 50 }
                    })
                );
            });
        }

        // Safety Precautions
        if (lab.safetyPrecautions) {
            paragraphs.push(
                new Paragraph({
                    text: 'Safety Precautions',
                    heading: HeadingLevel.HEADING_3,
                    spacing: { before: 200, after: 100 }
                })
            );

            lab.safetyPrecautions.forEach(precaution => {
                paragraphs.push(
                    new Paragraph({
                        text: precaution,
                        bullet: { level: 0 },
                        spacing: { after: 50 }
                    })
                );
            });
        }

        // Procedure
        if (lab.procedure) {
            paragraphs.push(
                new Paragraph({
                    text: 'Procedure',
                    heading: HeadingLevel.HEADING_3,
                    spacing: { before: 200, after: 100 }
                })
            );

            let stepNumber = 1;
            lab.procedure.forEach(step => {
                if (step.trim() === '') {
                    paragraphs.push(new Paragraph({ text: '', spacing: { after: 100 } }));
                } else if (step === step.toUpperCase() && step.includes(':')) {
                    paragraphs.push(
                        new Paragraph({
                            text: step,
                            bold: true,
                            spacing: { before: 150, after: 100 }
                        })
                    );
                } else {
                    paragraphs.push(
                        new Paragraph({
                            text: step,
                            numbering: { reference: 'experiment-numbering', level: 0 },
                            spacing: { after: 50 }
                        })
                    );
                }
            });
        }

        // Expected Results
        if (lab.expectedResults) {
            paragraphs.push(
                new Paragraph({
                    text: 'Expected Results',
                    heading: HeadingLevel.HEADING_3,
                    spacing: { before: 200, after: 100 }
                })
            );

            this.addNestedContent(paragraphs, lab.expectedResults);
        }

        // Results
        if (lab.results) {
            paragraphs.push(
                new Paragraph({
                    children: [
                        new TextRun({ text: 'Results: ', bold: true }),
                        new TextRun({ text: lab.results })
                    ],
                    spacing: { before: 200, after: 100 }
                })
            );
        }

        // Conclusions
        if (lab.conclusions) {
            paragraphs.push(
                new Paragraph({
                    text: 'Conclusions',
                    heading: HeadingLevel.HEADING_3,
                    spacing: { before: 200, after: 100 }
                })
            );

            lab.conclusions.forEach(conclusion => {
                paragraphs.push(
                    new Paragraph({
                        text: conclusion,
                        bullet: { level: 0 },
                        spacing: { after: 50 }
                    })
                );
            });
        }

        // Real World Applications
        if (lab.realWorldApplications || lab.applications) {
            const applications = lab.realWorldApplications || lab.applications;
            paragraphs.push(
                new Paragraph({
                    text: 'Real World Applications',
                    heading: HeadingLevel.HEADING_3,
                    spacing: { before: 200, after: 100 }
                })
            );

            applications.forEach(app => {
                paragraphs.push(
                    new Paragraph({
                        text: app,
                        bullet: { level: 0 },
                        spacing: { after: 50 }
                    })
                );
            });
        }

        return paragraphs;
    }

    addNestedContent(paragraphs, obj, level = 0) {
        Object.entries(obj).forEach(([key, value]) => {
            if (typeof value === 'object' && !Array.isArray(value)) {
                paragraphs.push(
                    new Paragraph({
                        text: key,
                        bold: true,
                        spacing: { before: 100, after: 50 }
                    })
                );
                this.addNestedContent(paragraphs, value, level + 1);
            } else {
                const valueText = typeof value === 'string' ? value : JSON.stringify(value);
                paragraphs.push(
                    new Paragraph({
                        children: [
                            new TextRun({ text: `${key}: `, bold: true }),
                            new TextRun({ text: valueText })
                        ],
                        spacing: { after: 50 }
                    })
                );
            }
        });
    }
}


// ========================================
// UPDATE RUN DEMONSTRATIONS SECTION
// ========================================
// Replace the existing "RUN DEMONSTRATIONS" section with:

console.log('\n🚀 Starting Molecular Biology Workbook Demonstrations...\n');

// Choose which demonstration to run:

// Option 1: Run complete demonstration WITH experiment
demonstrateWorkbookWithExperiment()
    .then(() => {
        console.log('\n🎉 Demonstration with experiment completed successfully!');
        process.exit(0);
    })
    .catch(error => {
        console.error('\n💥 Fatal error:', error);
        process.exit(1);
    });

// Option 2: Run original demonstration WITHOUT experiment (comment out option 1, uncomment this)
// demonstrateWorkbookWithDiagrams()
//     .then(() => {
//         console.log('\n🎉 All demonstrations completed successfully!');
//         process.exit(0);
//     })
//     .catch(error => {
//         console.error('\n💥 Fatal error:', error);
//         process.exit(1);
//     });

// Optional: Export specific diagram


exportSpecificDiagram().catch(console.error);
