

this.assessmentQuestions = { 

thermodynamics: {
    zerothLaw: {
        remember:   "State the Zeroth Law of Thermodynamics in full. Define: (a) thermal equilibrium; (b) system; (c) surroundings. Name the four laws of thermodynamics in order and give the key quantity each introduces.",
        understand: "Explain why the Zeroth Law is described as 'logically prior' to the other laws, even though it was formulated last. Your answer must explain what concept the Zeroth Law establishes that is assumed without proof in the First and Second Laws.",
        apply:      "Object A at 75°C is placed in thermal contact with object B at 40°C. After a long time, both read 55°C on a calibrated thermometer. (a) State what has been reached. (b) A third object C, previously in contact with B at 40°C, is now placed in contact with A at 55°C. Using the Zeroth Law, predict the final temperature of C. Justify your answer without any calculation.",
        analyze:    "A thermocouple thermometer and a resistance thermometer are both calibrated at 0°C and 100°C fixed points. At 50°C they agree. At 70°C the thermocouple reads 70.4°C and the resistance thermometer reads 70.0°C. Analyse whether this violates the Zeroth Law. Identify the physical reason for the discrepancy and state what it implies about thermometric scales.",
        evaluate:   "Evaluate the following student claim: 'If two objects feel the same temperature to the touch, they must be at the same temperature — so the human hand is a reliable thermometer.' Identify where this reasoning is physically correct, where it fails, and what physical quantity the hand is actually sensing. Reference the Zeroth Law in your answer.",
        create:     "Construct a thought experiment to demonstrate that a logically consistent temperature scale requires the transitive property guaranteed by the Zeroth Law. Your experiment must show that without the Zeroth Law, two different thermometers could give contradictory readings for the same object — and explain what physical scenario would cause this."
    },

    firstLaw: {
        remember:   "Write the First Law of Thermodynamics. Define each symbol using the physics sign convention. State what is meant by a state function and give two examples. Name the four standard thermodynamic processes and the constraint that defines each.",
        understand: "Explain why internal energy is a state function but heat and work are not. Your answer must include a concrete example showing that Q and W individually depend on the path taken between two states, while Q − W does not.",
        apply:      "An ideal gas undergoes the following sequence: (1) absorbs 600 J of heat while doing 250 J of work on surroundings; (2) then has 400 J of work done on it while losing 150 J of heat. Calculate: (a) ΔU for each step; (b) the total ΔU for both steps combined; (c) whether the gas temperature is higher or lower at the end than the beginning.",
        analyze:    "A gas undergoes a four-step cycle on a P-V diagram: A→B isothermal expansion; B→C isochoric cooling; C→D isothermal compression; D→A isochoric heating. For each step, determine the sign (positive, negative, or zero) of Q, W, and ΔU. Then determine the sign of net W and net Q for the full cycle. Verify that your answers are consistent with the First Law applied to a complete cycle.",
        evaluate:   "A student calculates the work done by a gas during isothermal expansion from V_i to V_f using W = PΔV, obtaining a single value. Evaluate this approach — identify when it is correct, when it is an approximation, and what calculation should be used for an ideal gas undergoing isothermal expansion. Calculate the percentage error for a gas expanding from V to 2V at constant T compared to the exact result.",
        create:     "Design a bomb calorimeter experiment to measure the enthalpy of combustion of ethanol. Your design must specify: (a) what is kept constant (volume or pressure) and why this matters for interpreting the result in terms of ΔU vs ΔH; (b) how you apply the First Law to convert the temperature rise to ΔU; (c) the correction needed to obtain ΔH from ΔU; (d) three sources of systematic error and how you would correct for each."
    },

    secondLaw: {
        remember:   "State both the Kelvin-Planck and Clausius statements of the Second Law. Write the Carnot efficiency equation and the Carnot COP equation for a refrigerator. Define entropy as both a thermodynamic quantity and statistically (Boltzmann). State the condition for: (a) a reversible process; (b) an irreversible process; (c) an impossible process — in terms of ΔS_universe.",
        understand: "Explain using entropy why it is impossible for a heat engine to convert heat entirely to work in a cycle. Your explanation must: (a) identify where entropy is produced and destroyed in the cycle; (b) show that 100% efficiency would require ΔS_universe < 0; (c) explain why this is prohibited.",
        apply:      "A heat engine operates between T_H = 750 K and T_C = 300 K. In each cycle it absorbs Q_H = 12,000 J. (a) Calculate the Carnot efficiency. (b) Calculate the maximum work output. (c) Calculate the minimum heat rejected. (d) The actual engine produces 4,200 J of work. Calculate its actual efficiency and compare to Carnot. (e) Calculate ΔS_universe per cycle for the actual engine.",
        analyze:    "Entropy data for a process are recorded: a 500 g metal block at 400 K is placed in contact with a large water bath at 300 K. The specific heat of the metal is 450 J·kg⁻¹·K⁻¹. (a) Calculate the heat transferred from metal to water (assuming the bath stays at 300 K). (b) Calculate ΔS_metal. (c) Calculate ΔS_water. (d) Calculate ΔS_universe. (e) Analyse what the sign of ΔS_universe tells you about the direction of this process — would the reverse process (water spontaneously heating the metal) be consistent with the First Law? With the Second Law?",
        evaluate:   "A company markets a heat pump that 'achieves COP = 8.5 heating a house at 20°C from outside air at −5°C'. Evaluate whether this claim is thermodynamically possible. Calculate the Carnot COP for these temperatures and compare. If the claimed COP exceeds Carnot, identify which law is violated. If it does not exceed Carnot, assess whether it is plausible in practice.",
        create:     "Design a thermodynamic cycle to extract maximum work from a hot spring at 95°C (368 K) using the surrounding environment at 15°C (288 K) as the cold reservoir. Your design must: (a) specify the four steps of the cycle; (b) calculate the Carnot efficiency; (c) calculate the work output per 1,000 J absorbed; (d) explain why the real installation would achieve lower efficiency and identify three specific irreversibilities; (e) propose one engineering modification to reduce each irreversibility."
    },

    entropyAndDisorder: {
        remember:   "Write Boltzmann's entropy equation and define Ω. State the Third Law of Thermodynamics. Write the formula for entropy change during reversible isothermal heat transfer. Write the formula for entropy change during heating from T_i to T_f at constant pressure.",
        understand: "Explain using the concept of microstates (Ω) why a gas expanding into a vacuum is irreversible and why it never spontaneously contracts. Your answer must: (a) compare Ω for the expanded and contracted states; (b) connect Ω to S using Boltzmann's equation; (c) explain why probability — not force — determines the direction of the process.",
        apply:      "3 kg of water (c = 4,200 J·kg⁻¹·K⁻¹) is heated from 20°C (293 K) to 100°C (373 K) at constant pressure by a large reservoir at 373 K. Calculate: (a) the heat added to the water; (b) ΔS_water; (c) ΔS_reservoir; (d) ΔS_universe. State whether the process is reversible or irreversible and justify using the calculated values.",
        analyze:    "Temperature-entropy (T-S) data for a Carnot cycle are given as four corners: (T_H, S_low), (T_H, S_high), (T_C, S_high), (T_C, S_low). Analyse the shape of this cycle on a T-S diagram. Identify which sides correspond to which processes (isothermal, adiabatic). Show that the area enclosed equals the net work output. Explain why this diagram makes the Carnot cycle analysis much simpler than a P-V diagram.",
        evaluate:   "Evaluate the statement: 'Entropy always increases, so the universe is running down toward a state of maximum entropy where nothing useful can happen — this is the heat death of the universe.' Address: (a) which part of this statement is physically correct; (b) which part overstates thermodynamic conclusions; (c) what 'heat death' would actually look like thermodynamically; (d) whether local decreases in entropy (such as life, stars, and structure) are consistent with the overall statement.",
        create:     "Construct an experimental investigation to verify Boltzmann's entropy interpretation for the mixing of two ideal gases. Your investigation should: (a) specify a model system (e.g. coloured beads in partitioned boxes); (b) define how you count microstates before and after mixing; (c) calculate ΔS = k_B·ln(Ω_final/Ω_initial) for a specific case; (d) connect this to the thermodynamic result ΔS_mix = nR·ln(V_f/V_i) for each gas; (e) propose a real experiment using gas diffusion that could provide supporting evidence."
    }
},

nuclearPhysics: {
    radioactivityBasics: {
        remember:   "Define the following terms with SI units where applicable: activity, decay constant, half-life, nucleon, isotope. State the nuclide notation for uranium-238 and identify the number of protons, neutrons, and nucleons.",
        understand: "Explain why radioactive decay is described as both random and exponential. Your answer must address: (a) why individual nuclear decay is unpredictable; (b) why large samples nonetheless follow a precise mathematical law; (c) what physical quantity the decay constant λ represents at the level of a single nucleus.",
        apply:      "A radioactive source has initial activity 6400 Bq and half-life 12 minutes. (a) Calculate the decay constant λ in s⁻¹. (b) Calculate the activity after 36 minutes using both the (½)^n method and the exponential method — confirm they agree. (c) Calculate the number of undecayed nuclei at t = 36 min.",
        analyze:    "Activity measurements for a source: t (min): 0, 5, 10, 15, 20, 25; A (Bq): 3200, 2263, 1600, 1132, 800, 566. (a) Calculate ln(A) for each time point. (b) Plot ln(A) vs t and determine the gradient. (c) Calculate λ and T½ from the gradient. (d) Verify whether the data are consistent with single-isotope exponential decay.",
        evaluate:   "Evaluate the claim: 'A radioactive source with a very long half-life (e.g. 10⁹ years) poses negligible radiation risk because it decays so slowly.' Assess this claim using the relationship A = λN. Identify what other factors besides T½ determine activity and hence risk. Conclude whether the claim is generally valid, giving a counterexample where a long-lived isotope does pose a significant risk.",
        create:     "Design an experiment to measure the half-life of a short-lived radioactive source (T½ ~ 5 minutes) using a Geiger-Müller tube. Your design must specify: (a) the measurement procedure with appropriate time intervals; (b) background radiation correction method; (c) the graphical analysis (linearisation) used to extract T½; (d) at least three sources of experimental uncertainty and how you minimise each; (e) the minimum number of half-lives you would measure and why."
    },

    nuclearDecayTypes: {
        remember:   "For each of the following decay types — alpha, beta-minus, beta-plus, gamma — state: (a) the particle or radiation emitted; (b) its charge; (c) the change in Z; (d) the change in A; (e) the approximate penetrating power. Arrange in order of ionising power (greatest first).",
        understand: "Explain, using the concept of the N/Z stability band, why: (a) carbon-14 (Z=6, N=8) undergoes beta-minus decay; (b) fluorine-18 (Z=9, N=9) undergoes beta-plus decay; (c) uranium-238 (Z=92, N=146) undergoes alpha decay. Each explanation must identify the position of the nucleus relative to the stability band and the direction of movement caused by the decay.",
        apply:      "Write complete, balanced nuclear equations for: (a) alpha decay of polonium-210 (²¹⁰₈₄Po); (b) beta-minus decay of strontium-90 (⁹⁰₃₈Sr); (c) beta-plus decay of sodium-22 (²²₁₁Na); (d) gamma decay of an excited technetium-99m nucleus (⁹⁹ₘ₄₃Tc). For each, verify conservation of mass number and atomic number.",
        analyze:    "The decay of bismuth-212 (²¹²₈₃Bi) proceeds by two competing pathways: (1) alpha decay (64% branching ratio) followed by beta-minus decay; (2) beta-minus decay (36% branching ratio) followed by alpha decay. (a) Write the complete decay equations for both pathways. (b) Show that both pathways lead to the same final nuclide. (c) Explain what 'branching ratio' means in terms of individual nuclear decay probability.",
        evaluate:   "Evaluate the following statement: 'Alpha radiation is always less dangerous than gamma radiation because it can be stopped by a sheet of paper.' Assess this claim separately for: (a) external irradiation from a source outside the body; (b) internal contamination where the source has been ingested. Use radiation weighting factors (w_R: α = 20, γ = 1) to support your conclusion. State clearly whether the claim is correct, incorrect, or context-dependent.",
        create:     "Construct the first six steps of the uranium-238 decay chain. For each step: (a) write the complete balanced decay equation; (b) identify the decay type; (c) state the half-life of each parent nuclide (look up or use given values: ²³⁸U: 4.47×10⁹ yr; ²³⁴Th: 24.1 days; ²³⁴Pa: 1.17 min; ²³⁴U: 2.46×10⁵ yr; ²³⁰Th: 7.54×10⁴ yr; ²²⁶Ra: 1600 yr). (d) Comment on the trend in half-lives along the chain and explain which step would be the bottleneck controlling the overall decay rate."
    },

    halfLifeAndDecay: {
        remember:   "Write the two forms of the radioactive decay law: (a) in terms of the decay constant λ; (b) in terms of the half-life T½. State the equation linking T½ and λ. Define what is meant by saying a source has an activity of 1 MBq.",
        understand: "Explain why the rate of decrease in activity of a radioactive source slows over time, even though the decay constant λ is unchanged. Your answer must: (a) identify which quantity decreases as decay proceeds; (b) explain how this causes the decay rate to decrease; (c) connect this to the shape of the activity-time graph.",
        apply:      "Cobalt-57 has T½ = 271.8 days and is used as a calibration source. Initial activity = 2.00 × 10⁷ Bq. (a) Calculate λ in s⁻¹. (b) Calculate the activity after 1 year (365 days). (c) Calculate the number of undecayed Co-57 nuclei at t = 0. (d) Calculate the time for activity to fall to 1.00 × 10⁶ Bq. Show full algebraic rearrangement before substituting numbers.",
        analyze:    "Two radioactive sources are mixed: source P (T½ = 4 hours, A₀ = 800 Bq) and source Q (T½ = 12 hours, A₀ = 400 Bq). (a) Write an expression for the total activity A_total(t) as the sum of two exponentials. (b) Calculate the total activity at t = 0, 4, 8, 12, 24 hours. (c) Plot these values and describe how the shape of the decay curve differs from a single-isotope exponential. (d) Determine which isotope dominates the activity after 24 hours.",
        evaluate:   "Evaluate Newton's Law of Cooling and radioactive decay as analogous exponential processes: (a) Identify the physical quantity that plays the role of 'number of undecayed nuclei' in Newton's cooling. (b) Identify the analogue of the decay constant λ in Newton's cooling. (c) State one way in which the analogy breaks down physically. (d) Assess whether the mathematics of one model could be used to solve problems in the other without modification.",
        create:     "Construct a complete quantitative decay analysis for a medical iodine-131 therapy application. Given: T½(¹³¹I) = 8.02 days, initial activity administered = 7.4 GBq, regulatory clearance limit = 1 GBq. (a) Calculate λ in day⁻¹. (b) Calculate activities at day 0, 8, 16, 24, 32 and tabulate. (c) Calculate the exact day on which activity falls below 1 GBq. (d) Calculate the number of ¹³¹I atoms at the point of clearance and the mass of ¹³¹I remaining. (e) Propose a monitoring schedule (measurement times and acceptable activity thresholds) for the patient's radiation safety management."
    },

    nuclearReactions: {
        remember:   "State Einstein's mass-energy equation. State the value of c. Give the conversion: 1 atomic mass unit (u) = ??? MeV/c². Define: (a) mass defect; (b) binding energy; (c) binding energy per nucleon. State which nucleus has the highest binding energy per nucleon.",
        understand: "Explain the physical meaning of the binding energy curve (binding energy per nucleon vs mass number). Your answer must explain: (a) why binding energy per nucleon increases from hydrogen to iron; (b) why it decreases from iron to uranium; (c) why both fission of uranium and fusion of hydrogen release energy, using the concept of 'moving toward the peak'.",
        apply:      "Calculate the binding energy of oxygen-16 (¹⁶₈O) in MeV and the binding energy per nucleon. Given: m(¹⁶O) = 15.994915 u; m_p = 1.007276 u; m_n = 1.008665 u; 1 u = 931.5 MeV/c². Show all steps explicitly: composition, separated nucleon mass, mass defect, total BE, BE per nucleon.",
        analyze:    "The following fusion reactions have been proposed for energy generation: (A) ²H + ²H → ³He + n + 3.27 MeV; (B) ²H + ²H → ³H + p + 4.03 MeV; (C) ²H + ³H → ⁴He + n + 17.6 MeV. (a) Verify reaction (C) using atomic mass data: m(²H) = 2.014102 u, m(³H) = 3.016049 u, m(⁴He) = 4.002602 u, m(n) = 1.008665 u. (b) Calculate energy per nucleon for reaction (C). (c) Analyse why reaction (C) is the preferred candidate for fusion reactors despite requiring tritium, which is radioactive and rare.",
        evaluate:   "A student claims: 'Nuclear fission is more efficient than fusion because fission reactors already generate electricity worldwide, whereas fusion has not yet achieved net energy gain.' Evaluate this claim by separating it into two sub-claims: (a) 'fission is more technologically mature' — assess whether this implies greater energy efficiency per unit fuel mass; (b) 'fusion has not achieved net energy gain' — assess the current status as of recent years and distinguish between scientific Q > 1 and engineering/wall-plug Q > 1. Conclude whether the student's overall claim is well-reasoned.",
        create:     "Design a quantitative analysis of the energy available from the known global reserves of uranium-235 versus deuterium (for D-T fusion). Given: (a) global U-235 reserves approximately 2 × 10⁶ tonnes; energy per fission ~200 MeV; (b) global deuterium in oceans: ~2.4 × 10¹⁶ kg; energy per D-T fusion 17.6 MeV, requiring 1 deuterium per reaction. Calculate the total energy available from each source in joules and in years of current global electricity consumption (~8 × 10¹³ kWh/year). Use your calculations to construct a quantitative argument about which fuel offers greater long-term energy security."
    }
},

optics: {
    reflectionBasics: {
        remember:   "State the Law of Reflection in full. Define: normal, angle of incidence, specular reflection, diffuse reflection. Identify which type of reflection produces a clear image and which does not.",
        understand: "Explain why a rough surface such as a painted wall produces diffuse reflection, even though every individual point on the surface obeys the Law of Reflection exactly. Your answer must connect the microscopic geometry of the surface to the macroscopic distribution of reflected rays.",
        apply:      "An object is placed 24 cm in front of a concave mirror of focal length 8 cm. (a) Calculate the image distance using the mirror equation. (b) Calculate the magnification. (c) State whether the image is real or virtual, upright or inverted, and magnified or diminished. (d) Repeat the calculation for a convex mirror of the same focal length magnitude and compare the results.",
        analyze:    "Experimental data for a concave mirror: object distances u = 15, 20, 25, 30, 40 cm; corresponding image distances v = 60, 30, 21.4, 18, 15 cm. (a) Calculate 1/u and 1/v for each pair. (b) Plot 1/v against 1/u and determine the focal length from the intercepts. (c) Assess whether the data are consistent with the mirror equation and identify any anomalous points.",
        evaluate:   "A student proposes replacing the flat mirror in a car's interior rear-view mirror with a concave mirror, arguing that a concave mirror magnifies images and will therefore make it easier to see following vehicles. Evaluate this proposal by considering the image properties of a concave mirror for objects beyond 2F, the typical distances of following vehicles, and the safety implications of any image distortion.",
        create:     "Design a dental mirror that allows a dentist to view tooth surfaces that cannot be seen directly. Specify: (a) the type of mirror (plane, concave, or convex) and justify your choice based on the required image properties; (b) a suitable radius of curvature and the resulting focal length; (c) the working distance from mirror to tooth surface for clear viewing; (d) calculate the expected magnification at this working distance."
    },

    refractionBasics: {
        remember:   "State Snell's Law with all symbols defined. Define refractive index and give its formula in terms of the speed of light. Give approximate refractive index values for air, water, and crown glass. State the direction rule for bending when light enters a denser medium.",
        understand: "Explain why a swimming pool appears shallower than it actually is when viewed from directly above. Your answer must describe the path of light from the pool floor to the observer's eye, identify where refraction occurs, and explain how the brain's interpretation produces the illusion of a shallower pool.",
        apply:      "A ray of light travels from air into a diamond (n = 2.42) at an angle of incidence of 30°. (a) Calculate the angle of refraction inside the diamond. (b) Calculate the speed of light inside the diamond. (c) A fish is at the bottom of a 3.0 m deep pond (n = 1.33). Calculate its apparent depth when viewed from directly above.",
        analyze:    "Light passes through a glass block with parallel sides (n = 1.52, thickness 4 cm) and enters at 50°. (a) Calculate the angle inside the glass. (b) Calculate the angle upon exit into air. (c) Analyse whether the exit ray is parallel to the entry ray. (d) Calculate the lateral displacement (perpendicular distance between incident and emergent rays). (Hint: draw the geometry and use trigonometry.)",
        evaluate:   "A student states that light bends more when it travels from air into diamond (n = 2.42) than when it travels from water (n = 1.33) into diamond. Evaluate this claim by calculating both angles of refraction for θᵢ = 45° in each case, comparing the results, and explaining what physically determines the degree of bending.",
        create:     "Design an experiment to measure the refractive index of an unknown transparent liquid using a glass semicircular tank, a laser pointer, a protractor, and a ruler. (a) Describe the experimental arrangement; (b) explain why a semicircular tank is preferable to a rectangular one for this purpose; (c) specify the measurements to take and how Snell's Law is applied; (d) describe how you would plot a graph to determine n with higher precision than a single measurement; (e) identify three sources of error and how you would minimise each."
    },

    totalInternalReflection: {
        remember:   "State the two conditions necessary for total internal reflection. Write the formula for critical angle. State the critical angle for water (n = 1.33) and glass (n = 1.52) at their respective air boundaries.",
        understand: "Explain, using Snell's Law, why total internal reflection is impossible when light travels from a less dense into a denser medium. Your answer must show algebraically what happens to the equation n₁sinθ₁ = n₂sinθ₂ when n₂ > n₁ and θ₁ = 90°.",
        apply:      "An optical fibre has core n = 1.55 and cladding n = 1.48. (a) Calculate the critical angle at the core-cladding boundary. (b) Calculate the numerical aperture (NA = √(n_core² − n_cladding²)). (c) Calculate the maximum angle at which light can enter the fibre from air and still propagate by TIR. (d) A second fibre has n_core = 1.55 and n_cladding = 1.52. Compare its NA and acceptance angle to the first fibre.",
        analyze:    "A student shines a laser into a semicircular glass block (n = 1.52) through the flat face, aiming toward the curved surface at the centre of the block (so no refraction occurs at the curved face — only at the flat face on exit). They increase the angle of incidence at the flat face from 0° to 90°. (a) Calculate the critical angle. (b) Analyse what the student observes as the angle increases through the critical angle. (c) At θᵢ = 30°, 40°, 41.1°, and 50° — describe the ray behaviour in each case.",
        evaluate:   "Evaluate the following claim about optical fibres: 'Since TIR ensures 100% reflection at the core-cladding boundary, optical fibres should transmit light without any power loss over any distance.' Identify at least three real mechanisms that cause power loss in optical fibres despite TIR, explain the physical origin of each, and assess the practical implications for long-distance communication.",
        create:     "Design an experiment to measure the critical angle of a glass block using a laser, a semicircular glass block, a turntable, and a screen. (a) Describe the experimental setup; (b) explain how you will identify the critical angle from observations rather than just calculating it; (c) describe how you will use your measurement to determine the refractive index of the glass; (d) estimate the uncertainty in your critical angle measurement and the resulting uncertainty in n; (e) explain how you would modify the experiment to measure the critical angle of a liquid."
    },

    lensesAndMirrors: {
        remember:   "Write the thin lens equation and define each symbol. State the sign convention for real and virtual images. Define focal length, optical centre, and principal axis. State what lens power measures and its unit.",
        understand: "Explain why an object placed between a converging lens and its focal point produces a virtual image, while an object beyond the focal point produces a real image. Your explanation must reference what happens to the refracted rays in each case — do they converge or diverge after the lens?",
        apply:      "A converging lens has focal length 12 cm. An object of height 5 cm is placed 20 cm from the lens. (a) Calculate the image distance. (b) Calculate the magnification. (c) Calculate the image height. (d) State whether the image is real or virtual, upright or inverted, and give the location of the image relative to the lens. (e) Calculate the power of the lens in dioptres.",
        analyze:    "A person's eye has a far point of 1.5 m and a near point of 15 cm. (a) Analyse the type and severity of the vision defect. (b) Calculate the power of lens needed for distance vision. (c) Calculate the power of lens needed for near vision at 25 cm. (d) Analyse whether this person's near vision actually needs correction if their near point is already at 15 cm, explaining your reasoning.",
        evaluate:   "A manufacturer produces a converging lens of focal length 20 cm for use as a magnifying glass and claims a magnification of 5×. Evaluate this claim by calculating the magnification when: (a) the image is at the near point (25 cm) and (b) the image is at infinity. Identify which formula the manufacturer is likely using and whether the claimed value is achievable. Assess the practical difference between viewing comfort in each case.",
        create:     "Design a two-lens system to project a 35 mm photographic slide (dimensions 24 mm × 36 mm) onto a screen 4 m away, producing an image 1.2 m wide. (a) Calculate the required magnification; (b) calculate the required image distance and object distance for a single lens; (c) calculate the required focal length; (d) calculate the power of the lens; (e) describe the orientation of the slide in the projector (which way up does it need to be placed) and explain why; (f) suggest why a real projector uses a compound lens system rather than a single thin lens."
    }
},

waves: {
    waveBasics: {
        remember:   "State the wave equation and define every variable with its SI unit. Define amplitude, frequency, wavelength, and period. State the relationship between period and frequency.",
        understand: "Explain why the frequency of a wave does not change when it crosses from one medium to another, but its wavelength does. Your answer must identify what determines frequency and what determines wave speed.",
        apply:      "A water wave has frequency 2.5 Hz and wavelength 0.40 m. (a) Calculate the wave speed. (b) The wave moves into shallower water where the speed drops to 0.60 m·s⁻¹. Calculate the new wavelength. (c) State what happens to the frequency and explain why.",
        analyze:    "A displacement-distance graph shows four complete cycles over 8.0 m with maximum displacement 0.030 m. The wave travels at 12 m·s⁻¹. (a) Read off the wavelength and amplitude. (b) Calculate the frequency and period. (c) Sketch the graph as it would appear 0.5 s later. (d) If the amplitude is doubled, calculate the factor by which the wave energy increases.",
        evaluate:   "A student states: 'Radio waves travel faster than visible light because they have longer wavelengths.' Evaluate this claim. Use v = fλ and your knowledge of electromagnetic waves to identify the error. Calculate the wavelength of a 100 MHz radio wave and a 600 nm light wave and compare their speeds.",
        create:     "Design an experiment to measure the speed of microwaves using a microwave oven (turntable removed) and chocolate. Specify: (a) the physical effect you are exploiting and the relevant wave property you are measuring; (b) all measurements taken; (c) additional data needed and where you would obtain it; (d) calculation procedure; (e) one significant source of error and how you would minimise it."
    },

    transverseAndLongitudinal: {
        remember:   "Define transverse wave and longitudinal wave. State the direction of particle oscillation relative to energy propagation in each. Give two examples of each type. State which type can be polarised.",
        understand: "Explain the difference between compressions and rarefactions in a longitudinal wave. Your answer must include a description of particle spacing and pressure in each region, and explain why longitudinal waves cannot be polarised.",
        apply:      "A longitudinal wave (sound) travels at 340 m·s⁻¹ in air at 660 Hz. (a) Calculate the wavelength in air. (b) The sound enters water (v = 1500 m·s⁻¹). Calculate the wavelength in water. (c) Unpolarised light of intensity 600 W·m⁻² passes through a single polaroid. State the transmitted intensity. (d) The polarised beam then passes through a second polaroid at 45° to the first. Calculate the final intensity using Malus's Law.",
        analyze:    "A student sends waves along a slinky spring, first with a flicking motion sideways (perpendicular to the slinky axis) and then with a push-pull motion (along the slinky axis). Analyse: (a) which motion produces a transverse wave and which produces a longitudinal wave; (b) how you would demonstrate that the transverse wave can be polarised using a narrow slit in a cardboard barrier; (c) why the same slit cannot polarise the longitudinal wave.",
        evaluate:   "Evaluate the following statement: 'Ultrasound is used for medical imaging rather than ordinary sound because ultrasound travels faster through tissue, giving better penetration.' Identify every error in this statement, provide correct explanations for why ultrasound is used, and calculate the wavelength of both 50 Hz sound and 5 MHz ultrasound in tissue (v = 1540 m·s⁻¹) to support your answer.",
        create:     "Propose an experiment to determine whether seismic waves from a distant earthquake are P-waves (longitudinal) or S-waves (transverse) using a seismograph that records ground movement. Specify: (a) how P and S waves differ in their effect on ground particle motion; (b) what the seismograph record would look like for each type; (c) how the arrival time difference between P and S waves at multiple stations could be used to locate the epicentre; (d) what the absence of S-waves at certain seismograph stations tells us about Earth's internal structure."
    },

    waveBehaviour: {
        remember:   "State the law of reflection. Define constructive interference and state the path difference condition for it. Define destructive interference and state the path difference condition for it. Define a node and an antinode in a standing wave.",
        understand: "Explain why diffraction is most pronounced when the gap width is approximately equal to the wavelength. Your answer must describe what happens to the wave pattern for a gap much smaller than λ, approximately equal to λ, and much larger than λ.",
        apply:      "Two coherent speakers emit at 425 Hz. Speed of sound = 340 m·s⁻¹. Point P is 4.80 m from speaker A and 5.60 m from speaker B. (a) Calculate the wavelength. (b) Calculate the path difference at P. (c) Express the path difference in wavelengths and determine whether P is a maximum or minimum. (d) Calculate the resultant amplitude at P if each speaker produces amplitude 2.0 cm at that point.",
        analyze:    "A string of length 1.20 m fixed at both ends is driven at various frequencies. Strong vibration (resonance) is observed at 50 Hz, 100 Hz, 150 Hz, and 200 Hz. (a) Identify the fundamental frequency and the harmonic numbers present. (b) Calculate the wave speed on the string. (c) Sketch the standing wave patterns for the 50 Hz and 150 Hz resonances, labelling nodes (N) and antinodes (A). (d) Explain why resonance does not occur at 75 Hz.",
        evaluate:   "A student sets up two speakers 1.0 m apart emitting coherent waves at 340 Hz and claims that the point directly between them (0.5 m from each) is a destructive interference minimum because 'the waves from each speaker cancel in the middle'. Evaluate this claim by calculating the path difference at the midpoint and applying the correct interference condition. Identify the student's conceptual error.",
        create:     "Design a double-slit interference experiment using a laser pointer (λ = 650 nm) to measure the separation of two close slits. Specify: (a) the equation you will use, defining all symbols; (b) all measurements required and the instrument used for each; (c) how you will calculate the slit separation; (d) how you will reduce percentage uncertainty in the smallest measurement; (e) one modification that would make the fringe pattern easier to measure and explain the wave physics behind it."
    },

    soundWaves: {
        remember:   "State the approximate speed of sound in air at 20°C. State which of solid, liquid, and gas transmits sound fastest. Define intensity of a sound wave and state its units. Write the formula for sound level in decibels.",
        understand: "Explain, using a particle model, why sound travels faster in steel than in air. Your answer must reference the properties of the particles in each medium that affect wave transmission speed.",
        apply:      "A small speaker produces sound of intensity 8.0 × 10⁻³ W·m⁻² at a distance of 1.5 m from the source. (a) Calculate the intensity at 6.0 m from the source using the inverse square law. (b) Calculate the sound level in dB at both distances. (c) A second identical speaker is placed next to the first. State the intensity at 1.5 m from the pair and calculate the new sound level. Explain why the level increases by 3 dB rather than doubling.",
        analyze:    "Intensity measurements taken at five distances from a speaker are: 0.5 m → 1600 mW·m⁻²; 1.0 m → 400 mW·m⁻²; 2.0 m → 100 mW·m⁻²; 4.0 m → 25 mW·m⁻²; 8.0 m → 6.3 mW·m⁻². (a) Calculate I × r² at each distance and comment on whether the inverse square law holds. (b) Plot log(I) against log(r) and determine the gradient. (c) State what the gradient tells you about the relationship between I and r. (d) Identify one physical condition that must be met for the inverse square law to apply and assess whether it is likely met in this experiment.",
        evaluate:   "Evaluate Newton's Law of Cooling and the inverse square law as models, comparing how both involve a quantity decreasing with distance or time but with fundamentally different mathematical forms. Identify: (a) the form of each law; (b) what physical geometry or mechanism produces each form; (c) in what sense the two laws are analogous and in what sense they are fundamentally different.",
        create:     "Construct a complete experimental investigation to verify that the intensity of sound from a small speaker follows the inverse square law. Your plan must include: (a) equipment list with specification of the sound level meter or microphone; (b) the range of distances you would use and why; (c) the controlled variables and how you would control them; (d) the data transformation that produces a straight-line graph to confirm the law; (e) at least two sources of systematic error in an indoor environment and how you would reduce them."
    }
},

electricity: {
    currentFlow: {
        remember:   "State the equation relating electric current, charge, and time. Define the ampere in terms of charge and time. State the charge on a single electron and give its value to two significant figures.",
        understand: "Explain why the drift velocity of electrons in a wire is much smaller than the speed at which an electrical signal propagates when a switch is closed. Your answer must distinguish between what moves slowly (electrons) and what moves quickly (the electric field), and explain the physical mechanism for each.",
        apply:      "A current of 3.2 A flows through a resistor for 5 minutes. (a) Calculate the charge that passes through the resistor. (b) Calculate the number of electrons that pass a cross-section of the resistor. (c) If the resistor is connected to a 12 V supply, calculate the energy transferred to the resistor.",
        analyze:    "A student records the following current-time data for a wire: t (s): 0, 10, 20, 30, 40; I (A): 4.0, 3.2, 2.6, 2.1, 1.7. (a) Calculate the total charge passed in the first 40 s using the trapezoidal approximation. (b) Analyse whether the current decays exponentially by plotting ln(I) against t and assessing linearity. (c) Determine the time constant from your graph.",
        evaluate:   "A student states: 'In a series circuit with two identical resistors, the current flows from the battery, halves at the first resistor, then the remaining half flows through the second resistor before returning to the battery.' Evaluate this statement in full — identify every error, state the correct behaviour using KCL, and explain what actually happens to the current.",
        create:     "Design an experiment to measure how the current through an electrolytic cell varies with applied voltage. Your design must specify: (a) circuit diagram with all components labelled; (b) method for varying voltage in controlled steps; (c) safety precautions for electrolysis; (d) how you will calculate charge transferred and use Faraday's Law to determine the mass of metal deposited; (e) two sources of error and how they will be minimised."
    },

    voltageAndPotential: {
        remember:   "Define potential difference. Write the equation relating potential difference, energy, and charge. State the SI unit of potential difference and show it is equivalent to J·C⁻¹. Define EMF and state how it differs from terminal voltage.",
        understand: "Explain using an energy argument why the potential difference across each component in a series circuit adds up to the supply voltage. Your explanation must reference what voltage physically represents (energy per unit charge) and what happens to energy as charge passes through each component.",
        apply:      "A battery has EMF 12.0 V and internal resistance 0.6 Ω. It is connected to an external circuit of resistance 5.4 Ω. (a) Calculate the current. (b) Calculate the terminal voltage. (c) Calculate the power delivered to the external circuit. (d) Calculate the efficiency of the battery (power to external circuit as percentage of total power from EMF).",
        analyze:    "A battery's terminal voltage is measured at 8.4 V with no current flowing, 7.8 V when delivering 2 A, and 7.2 V when delivering 4 A. (a) Analyse whether the terminal voltage varies linearly with current. (b) Determine EMF and internal resistance from two data points. (c) Determine the short-circuit current (when R_external = 0) and comment on whether this is achievable in practice.",
        evaluate:   "Evaluate the claim: 'A student can determine the EMF of a battery by simply connecting a voltmeter across its terminals.' Identify the condition under which this gives an accurate result, the condition under which it underestimates EMF, and what additional measurement would allow exact determination of both ε and r from a voltmeter reading alone.",
        create:     "Design a circuit to provide a stable 5.0 V reference voltage from a 9 V battery, using only resistors and a Zener diode (breakdown voltage = 5.0 V, maximum current = 20 mA). Specify: (a) the series resistor value needed to limit Zener current to 10 mA when the battery is fully charged (9 V) and nearly flat (7 V); (b) how the output voltage changes as load current is drawn; (c) the maximum load current the circuit can supply while maintaining regulation; (d) efficiency at full load."
    },

    resistanceAndOhmsLaw: {
        remember:   "State Ohm's Law. Define resistance and give its SI unit. Write the equation for resistance in terms of resistivity, length, and area. State whether metals and thermistors increase or decrease in resistance with increasing temperature.",
        understand: "Explain the physical mechanism of electrical resistance in a metallic conductor. Your answer must reference the free electron model, the role of lattice vibrations, and why resistance increases with temperature for metals but decreases for semiconductors.",
        apply:      "A tungsten filament lamp is rated 60 W at 230 V. (a) Calculate the resistance of the filament at operating temperature. (b) Tungsten has resistivity ρ = 5.6 × 10⁻⁷ Ω·m at operating temperature. If the filament diameter is 0.06 mm, calculate the required length. (c) At room temperature, tungsten has ρ = 5.5 × 10⁻⁸ Ω·m. Calculate the cold resistance and the initial current when the lamp is first switched on.",
        analyze:    "I-V data for an unknown component: V (V): 0, 1, 2, 3, 4, 5; I (mA): 0, 8, 14, 18, 21, 23. (a) Plot I vs V and describe the shape. (b) Calculate resistance at V = 1 V, V = 3 V, and V = 5 V. (c) Analyse how resistance changes with V and identify the most likely component type with justification. (d) Determine whether Ohm's Law applies.",
        evaluate:   "A student investigating resistance measures a 2 Ω reading for a short copper wire and a 2 Ω reading for a long nichrome wire. They conclude: 'These wires have the same resistance, so they will perform identically in a circuit.' Evaluate this conclusion — identify what the identical resistance values conceal about the two wires, and explain what additional information would be needed to fully characterise each wire's electrical properties.",
        create:     "Design a resistance thermometer to measure temperatures between 0°C and 100°C using a platinum wire (resistivity ρ₀ = 1.06 × 10⁻⁷ Ω·m at 0°C, temperature coefficient α = 3.85 × 10⁻³ K⁻¹). Specify: (a) the wire geometry needed for a resistance of 100 Ω at 0°C; (b) the resistance at 100°C using R(T) = R₀(1 + αT); (c) the circuit for measuring this resistance accurately using a Wheatstone bridge; (d) the sensitivity (ΔR per °C) and whether this is adequate for clinical thermometry (resolution 0.1°C required)."
    },

    seriesAndParallelCircuits: {
        remember:   "State the three rules for series circuits (current, voltage, resistance). State the three rules for parallel circuits. Write the two-resistor shortcut for parallel resistance and state the condition under which it applies.",
        understand: "Explain why the total resistance of a parallel combination is always less than the smallest individual resistance. Your explanation must reference the concept of current paths and must not use any equations — physical reasoning only.",
        apply:      "A circuit consists of R₁ = 8 Ω in series with a parallel combination of R₂ = 12 Ω and R₃ = 6 Ω, all connected to a 24 V supply. (a) Calculate the resistance of the parallel combination. (b) Calculate the total circuit resistance. (c) Calculate the total current from the supply. (d) Calculate the voltage across the parallel combination. (e) Calculate the current through R₂ and R₃. (f) Verify using KCL and KVL.",
        analyze:    "A student measures the current from the supply as 4 A and the voltage across one branch of a two-branch parallel circuit as 12 V. The two resistors in the branches are R₁ = 4 Ω and R₂ = unknown. (a) Determine R₂ using KCL and Ohm's Law. (b) Calculate the total resistance of the parallel combination. (c) Determine the supply voltage. (d) Analyse what would happen to the total current if R₂ were disconnected — and whether the brightness of a lamp in R₁'s branch would change.",
        evaluate:   "A student designing a simple circuit states: 'I'll connect the two 6 Ω resistors in parallel to get a total resistance of 3 Ω, then connect the 3 Ω resistor in series with this to get a total of 6 Ω.' Evaluate each step of this reasoning — identify any errors and calculate the correct total resistance.",
        create:     "Design a potential divider circuit to provide three different output voltages (2 V, 5 V, and 9 V) from a single 12 V supply, using a chain of series resistors with output taps between them. (a) Specify the three resistor values required. (b) Calculate the current through the potential divider chain. (c) Assess the effect of connecting a 1 kΩ load across the 5 V output — calculate the new voltage at that tap. (d) Propose a modification to the design that reduces the loading effect, explaining the trade-off involved."
    }
},

mechanics: {
    newtonLaws: {
        remember:   "State Newton's Three Laws of Motion in your own words. Define inertia and explain which of Newton's laws introduces this concept. Write the equation form of Newton's Second Law, identify each variable and its SI unit.",
        understand: "Explain why a horse pulling a cart can accelerate the cart forward, even though Newton's Third Law states the cart pulls the horse backward with an equal force. Your answer must identify which forces act on which objects and explain why the net force on the cart is not zero.",
        apply:      "A 1500 kg car accelerates uniformly from 0 to 28 m·s⁻¹ in 9.0 s. The frictional resistance force is 500 N. (a) Calculate the acceleration. (b) Calculate the net force. (c) Calculate the engine driving force. (d) Calculate the engine power output at the moment the car reaches 28 m·s⁻¹.",
        analyze:    "A velocity-time graph for a 1000 kg vehicle shows three phases: Phase A (0–8 s): v increases linearly from 0 to 16 m·s⁻¹. Phase B (8–20 s): v remains constant at 16 m·s⁻¹. Phase C (20–25 s): v decreases linearly to 0. Analyse each phase: calculate acceleration, net force, and (for Phase B) the engine driving force if rolling resistance is 400 N. Calculate total displacement for the journey.",
        evaluate:   "Evaluate the following student explanation: 'When I push a wall, the wall pushes back on me with an equal force. Since the two forces are equal and opposite, they cancel and nothing moves — this proves Newton's Third Law.' Identify what is correct and what is fundamentally wrong about this explanation. Use Newton's Third Law correctly to explain what happens when a person pushes against a wall that does not move.",
        create:     "Design a complete experiment to verify Newton's Second Law using a dynamics trolley on a frictionless (or friction-compensated) runway, a pulley, and hanging masses. Your design must: (a) state the specific relationship you are testing; (b) explain how you vary net force while keeping mass constant; (c) describe how you measure acceleration; (d) specify how you will graph the data to produce a straight line and how you extract the value of mass from it; (e) identify and address the two most significant sources of systematic error."
    },

    forcesAndEquilibrium: {
        remember:   "State the two conditions for static equilibrium. Define coefficient of static friction and write the equation relating friction force to normal reaction. Name four types of force commonly shown on free body diagrams and state the direction of each.",
        understand: "Explain why the friction force on a stationary car on a slope acts up the slope, even though the car is not moving and friction is often described as 'opposing motion'. Your answer must connect the concept of tendency to slide to the direction of the static friction force.",
        apply:      "A 12 kg crate rests on a slope inclined at 28° to the horizontal. The coefficient of static friction is 0.50. (a) Draw a labelled free body diagram. (b) Calculate the component of weight along the slope. (c) Calculate the normal reaction force. (d) Calculate the maximum available static friction. (e) State whether the crate slides and justify your answer with numbers.",
        analyze:    "A uniform ladder of mass 20 kg and length 5.0 m leans against a smooth vertical wall, with its foot on rough ground at 60° to the horizontal. A 70 kg person stands two-thirds of the way up the ladder. Analyse the forces on the ladder: calculate the normal reaction from the wall (taking torques about the foot of the ladder), the normal reaction from the ground, and the minimum coefficient of friction at the ground needed to prevent the ladder from slipping.",
        evaluate:   "Evaluate this student claim: 'The friction force on a sliding object is always less than the friction force on a stationary object about to move, because kinetic friction is less than static friction.' Assess whether this generalisation is correct, identify the condition under which it is valid, and give one practical engineering situation where this distinction is critical.",
        create:     "Construct a systematic method for solving any static equilibrium problem involving an extended body. Your method must: (a) specify the steps in order; (b) explain how to choose the optimal pivot point for taking torques; (c) show how the method applies to the ladder problem above; (d) identify which step most students skip that causes incorrect answers; (e) explain how you verify that your answer is internally consistent."
    },

    kinematicsBasics: {
        remember:   "Write all four suvat equations. For each, state which four of the five kinematic variables (s, u, v, a, t) appear in it. State the condition that must be satisfied for the suvat equations to be valid.",
        understand: "Explain why braking distance is proportional to the square of initial speed rather than to the initial speed itself. Your answer must reference the specific suvat equation that establishes this relationship and show the algebraic derivation of the proportionality.",
        apply:      "A ball is launched horizontally at 15 m·s⁻¹ from the top of a cliff of height 80 m. (a) Calculate the time for the ball to reach the ground. (b) Calculate the horizontal distance from the base of the cliff where it lands. (c) Calculate the vertical component of velocity on impact. (d) Calculate the resultant speed and direction on impact.",
        analyze:    "A sprinter's position-time data are recorded: t (s): 0, 1, 2, 3, 4, 5, 6; x (m): 0, 3.5, 10, 18, 27, 36, 45. (a) Calculate average velocity for each 1 s interval. (b) Calculate average acceleration for each interval. (c) Identify when acceleration is approximately zero and connect this to Newton's laws. (d) Determine whether the suvat equations would be a valid model for the entire 6 s run and justify your answer.",
        evaluate:   "A student uses the equation s = ut + ½at² to calculate the distance a skydiver falls in 60 s, using u = 0 and a = 9.81 m·s⁻². Evaluate this calculation. Identify the physical phenomenon the student has ignored, explain how it changes the motion qualitatively, and describe what a more realistic velocity-time graph would look like for the skydiver.",
        create:     "Design an experiment to measure g using a free-fall method with a ruler and an electronic timer. (a) Specify exactly what you will measure and how. (b) Derive the equation you will use to calculate g from your measurements. (c) Describe how you will plot your data to give a straight-line graph from which g can be extracted. (d) Identify the dominant source of random error and the dominant source of systematic error. (e) Describe how you would assess whether your result is consistent with the accepted value of 9.81 m·s⁻²."
    },

    energyAndWork: {
        remember:   "State the work-energy theorem. Write the equations for kinetic energy, gravitational potential energy, and work done by a constant force at angle θ. State what is meant by a conservative force and give one example.",
        understand: "Explain why a centripetal force does no work on an object moving in a circular path. Your answer must use the definition W = Fs·cos θ and identify the relevant angle. Then explain the consequence for kinetic energy in uniform circular motion.",
        apply:      "A 70 kg skier starts from rest at the top of a 250 m long slope inclined at 15°. Friction does 4200 J of work against the skier over the descent. (a) Calculate the vertical height of the slope. (b) Calculate the gravitational PE lost. (c) Calculate the kinetic energy at the bottom. (d) Calculate the speed at the bottom.",
        analyze:    "A force-displacement graph for a braking car shows force on the y-axis (0 to 6000 N) and displacement on the x-axis (0 to 40 m). The force decreases linearly from 6000 N at 0 m to 0 N at 40 m. (a) Calculate the work done by the braking force using the area under the graph. (b) If the car has mass 1200 kg and the braking force is the only horizontal force, calculate the initial speed of the car using the work-energy theorem. (c) Verify by calculating the average braking force and using a suvat equation.",
        evaluate:   "A student states: 'When a ball is thrown upward, it slows down because it loses kinetic energy, which is converted to gravitational PE. At the top, all KE has become PE. Therefore, the total mechanical energy at the top is zero.' Evaluate this reasoning step by step — identify which parts are correct, which contain an error, and state the correct final conclusion.",
        create:     "Construct a complete energy audit for a ski-jump event from start to landing. The jumper (mass 70 kg) starts from rest at a height of 90 m, launches from the ramp edge at height 10 m at an angle of 12° above horizontal, and lands on a slope 50 m below the ramp edge. (a) Calculate the launch speed assuming 8% of initial PE is lost to friction during descent. (b) Calculate the time of flight and horizontal range using projectile equations. (c) Calculate KE at landing. (d) Identify where energy conservation would give incorrect results without the friction term. (e) Propose one measurement that could be taken during the jump to verify your energy calculations."
    },

    momentumAndImpulse: {
        remember:   "Define momentum and give its SI unit. Write the impulse-momentum theorem. State the law of conservation of momentum and identify the condition under which it applies. Distinguish between elastic and inelastic collisions in terms of which quantity is conserved in each.",
        understand: "Explain why a golf ball experiences a larger force from a club that follows through its swing compared to one that stops abruptly at contact, even if both produce the same change in the ball's momentum. Your answer must use the impulse-momentum theorem and identify what differs between the two cases.",
        apply:      "A 3.0 kg trolley moving at 4.0 m·s⁻¹ collides with a stationary 5.0 kg trolley. After the collision, the 3.0 kg trolley moves at 0.5 m·s⁻¹ in the original direction. (a) Calculate the velocity of the 5.0 kg trolley after collision. (b) Calculate the kinetic energy before and after. (c) Calculate the energy lost and classify the collision as elastic, inelastic, or perfectly inelastic.",
        analyze:    "Force-time data from a car crash test are: t (ms): 0, 10, 20, 30, 40, 50; F (kN): 0, 15, 35, 30, 10, 0. (a) Use the trapezium rule to calculate the total impulse. (b) If the test dummy has mass 75 kg and was initially at rest relative to the car (which was moving at 14 m·s⁻¹), calculate the dummy's final velocity. (c) Calculate the change in dummy's KE. (d) Analyse whether the impulse and energy change are consistent with each other.",
        evaluate:   "A student solves a collision problem (2 kg ball at 6 m·s⁻¹ hits stationary 2 kg ball) using kinetic energy conservation, obtaining that each ball moves at 4.24 m·s⁻¹ after collision. Evaluate this solution — identify the principle used, state whether it is applicable here, demonstrate why using momentum conservation gives a different answer, and explain which answer is physically correct (assuming the collision is elastic) by applying both conservation laws simultaneously.",
        create:     "Design a complete experimental investigation to test whether momentum is conserved in a collision between two dynamics trolleys. Your investigation must specify: (a) the apparatus and how it is set up; (b) how you will measure velocity before and after collision (with specific instrument and measurement technique); (c) how you will calculate momentum before and after for each trolley and for the system; (d) how you will present results to make conservation clear; (e) the sources of error that would cause apparent non-conservation and how you will quantify them; (f) how you would modify the experiment to test both elastic and inelastic collisions."
    }
},


heatTransfer: {
    conductionBasics: {
        remember:   "State Fourier's Law of heat conduction. Define each variable including its SI unit. State what thermal conductivity measures and give one example of a high-k and one example of a low-k material.",
        understand: "Explain why increasing the thickness of an insulating wall reduces heat loss, using Fourier's Law. Your answer must identify which variable in the equation changes and explain why thickness appears in the denominator rather than the numerator.",
        apply:      "A concrete wall (k = 1.0 W·m⁻¹·K⁻¹) is 0.20 m thick with area 8 m². The inner surface is at 18°C and the outer surface is at −2°C. (a) Calculate the rate of heat loss through the wall. (b) Calculate the thermal resistance of this wall. (c) How thick would the wall need to be to halve the heat loss rate?",
        analyze:    "A composite wall consists of three layers: plasterboard (L = 0.01 m, k = 0.16), brick (L = 0.20 m, k = 0.8), and granite cladding (L = 0.05 m, k = 3.0). All layers have the same area. Analyse which layer provides the greatest thermal resistance, calculate the total R, and determine the heat loss rate for ΔT = 20 K across an area of 6 m². Show all working.",
        evaluate:   "A student states: 'Adding more layers to a composite wall always significantly reduces total heat loss.' Evaluate this claim. Identify when adding a layer produces a large reduction, when it produces a negligible reduction, and what property of the added material determines which outcome occurs. Support your answer with a numerical example.",
        create:     "Design a composite wall for a cold-storage building that must maintain −18°C inside when the external temperature reaches 35°C. Specify at least three layers with material choice, thickness, and k value for each. Calculate total R per unit area and heat gain rate per square metre. Justify each material choice. Include a vapour barrier consideration and explain where it should be placed and why."
    },

    convectionBasics: {
        remember:   "Define natural convection and forced convection. State Newton's Law of Cooling (rate form) and identify each variable. State one context where natural convection dominates and one where forced convection is used.",
        understand: "Explain the physical mechanism by which a natural convection current is established above a hot horizontal surface. Your explanation must connect: temperature increase → density change → buoyancy force → fluid movement → heat transfer. Do not use any equations — use physical reasoning only.",
        apply:      "A heating element has surface area 0.06 m² and is maintained at 120°C in a room at 22°C. The convective heat transfer coefficient is h = 12 W·m⁻²·K⁻¹. (a) Calculate the rate of convective heat transfer. (b) If a fan increases h to 45 W·m⁻²·K⁻¹, calculate the new heat transfer rate. (c) Calculate the factor by which forced convection increases heat removal compared to natural convection in this case.",
        analyze:    "Temperature-time data for a cooling metal block in still air are recorded: t (min): 0, 10, 20, 30, 40; T (°C): 95, 72, 55, 43, 34; T_ambient = 22°C. (a) Calculate (T − T_ambient) for each time point. (b) Calculate ln(T − T_ambient) for each time point. (c) Plot ln(T − T_ambient) vs t and assess linearity. (d) Determine the cooling constant k from the gradient. (e) Predict the temperature at t = 60 min.",
        evaluate:   "Evaluate the claim: 'A domestic radiator heats a room primarily by radiation, hence its name.' Using quantitative reasoning, assess the relative contributions of convection and radiation from a typical radiator surface at 70°C in a room at 20°C (assume ε = 0.9, h = 8 W·m⁻²·K⁻¹). Calculate the power per unit area from each mechanism and conclude whether the naming is physically justified.",
        create:     "Design an experiment to measure the convective heat transfer coefficient h for a heated flat plate in natural convection. Your design must specify: (a) the equipment needed and the measurement principle; (b) how you will measure surface temperature and fluid temperature separately; (c) how you will calculate Q/t and hence h; (d) at least three controlled variables and how you will control them; (e) how you would modify the experiment to compare natural and forced convection."
    },

    radiationBasics: {
        remember:   "Write the Stefan-Boltzmann Law. State the value and units of σ. Define emissivity and state its range. State Wien's Displacement Law and identify what b represents.",
        understand: "Explain why the Stefan-Boltzmann Law must use temperature in Kelvin rather than Celsius. Your answer must include a numerical example demonstrating the error produced by using Celsius — compare the result for an object at 100°C using both temperature scales.",
        apply:      "A metal surface has area 0.5 m², emissivity ε = 0.85, and temperature 400°C. The surroundings are at 20°C. (a) Convert both temperatures to Kelvin. (b) Calculate the power emitted by the surface. (c) Calculate the power absorbed from the surroundings. (d) Calculate the net power radiated. Show each step.",
        analyze:    "Two surfaces face each other in a vacuum: Surface A at 800 K with ε = 0.9, surface B at 400 K with ε = 0.6. Both have area 0.2 m². (a) Calculate the power emitted by each surface using Stefan-Boltzmann. (b) Analyse the ratio of emitted powers and explain why surface A dominates despite being only twice the temperature. (c) If both surfaces are cooled to half their temperatures (400 K and 200 K), calculate the new power ratio and comment on the change.",
        evaluate:   "A student uses Wien's Displacement Law to calculate the peak emission wavelength of a human body at 37°C and concludes: 'Since the peak is in the infrared at about 9.4 μm, humans emit no visible light, confirming we cannot be seen in the dark.' Evaluate this statement — address the Wien's Law calculation, the conclusion about visible light emission, and any oversimplification in the reasoning.",
        create:     "Design the thermal management system for a satellite that generates 800 W of waste heat and orbits in an environment at effectively 3 K. The satellite must maintain an internal temperature of 290 K. (a) Explain why conduction and convection cannot remove heat from the satellite. (b) Using the Stefan-Boltzmann Law, calculate the minimum radiating surface area needed (assume ε = 0.85, ignore absorbed solar radiation for this calculation). (c) Propose a surface coating strategy and explain the emissivity trade-offs for different surfaces. (d) Describe what happens to internal temperature if a solar panel shadow reduces incoming solar load — will the satellite get hotter or cooler?"
    },

    thermalEquilibrium: {
        remember:   "State the condition for thermal equilibrium between two objects. Write Newton's Law of Cooling in its exponential (temperature vs time) form. Identify every variable including the cooling constant k and state its units.",
        understand: "Explain why an object cooling according to Newton's Law of Cooling never theoretically reaches ambient temperature, yet in practice we say it reaches equilibrium. Your answer must reference the shape of the exponential function and what 'asymptote' means in this physical context.",
        apply:      "A steel billet at 750°C is quenched in oil at 30°C. The cooling constant k = 0.08 min⁻¹. (a) Calculate the temperature of the billet after 15 minutes. (b) Calculate the time at which the billet reaches 100°C. Show all algebraic rearrangement steps clearly before substituting numbers.",
        analyze:    "A forensic team measures a body temperature of 31°C in a room maintained at 19°C. The body's normal temperature was 37°C. The cooling constant for a body of this build in this environment is estimated as 0.06 h⁻¹. (a) Apply Newton's Law of Cooling to estimate time of death. (b) Calculate the 95% confidence interval if k has an uncertainty of ±0.01 h⁻¹. (c) Analyse two environmental factors that would make this estimate unreliable, explaining the mechanism by which each factor violates the model's assumptions.",
        evaluate:   "Evaluate the suitability of Newton's Law of Cooling for modelling: (a) a cup of tea cooling from 85°C to room temperature (20°C) over 30 minutes; (b) the cooling of a nuclear reactor core from 2800°C. For each case, identify which heat transfer mechanisms are operating, assess whether the assumptions of Newton's Law are met, and state whether the model is appropriate, with reasoning.",
        create:     "Construct a complete experimental investigation to verify that Newton's Law of Cooling applies to a metal cylinder cooling in air. Your investigation must include: (a) a clear statement of what you are trying to verify (the exponential form); (b) equipment list and measurement procedure with stated time intervals; (c) the data transformation you will apply to produce a linear graph; (d) how you will extract k from the graph; (e) an assessment of whether your data confirm or refute the model; (f) two modifications that would test whether forced convection changes k and how."
    }

  }


};
}

const EndSection4 = "close"