

functions: {

    diagrams: [
        "Draw a large input-output machine diagram: a box labelled 'FUNCTION RULE', an arrow entering from the left labelled 'input x (domain)', and an arrow exiting to the right labelled 'output f(x) (range)'. Below the machine, write four examples using different function rules. Draw a second machine that takes f(x) as its input and produces f⁻¹(x) as its output, connecting both machines with a reverse arrow. This single diagram encodes the function concept, notation, and inverse simultaneously.",
        "Draw a vertical line test reference diagram: sketch five curves on separate small axes — a parabola opening upward, a circle, a straight line, a sideways parabola (x = y²), and a V-shape. On each, draw three vertical lines. Count intersections. Write 'FUNCTION' or 'NOT A FUNCTION' under each, with one sentence explaining which criterion is met or violated. Keep this diagram visible during every function identification task.",
        "Draw a transformations reference diagram for y = x² as the base function. On the same set of axes, draw y = x² + 3 (vertical translation up 3), y = (x − 3)² (horizontal translation right 3), y = −x² (reflection), and y = 2x² (vertical stretch). Label each transformation in a different colour. Annotate the vertex of each curve. Add arrows showing the movement from the parent function to each transformation. This provides a visual dictionary for every transformation type.",
        "Draw a function families reference page: six small coordinate systems, one per function family (linear, quadratic, exponential growth, exponential decay, reciprocal, square root). In each, draw the characteristic shape with its key features annotated: intercepts, asymptotes, vertex, domain and range written beside it. When a new problem involves identifying a function family, match its features against this reference page.",
        "Draw a composite function flow diagram for a specific example: write g(x) = 2x + 1 on the left, f(x) = x² on the right. Draw the chain: x → [g] → g(x) = 2x+1 → [f] → f(g(x)) = (2x+1)². Then draw the reverse chain for g(f(x)). Label the input and each intermediate output. This diagram makes the composition order unmistakable and prevents left-to-right reading errors."
    ],

    comparisonTables: [
        "Create a function-vs-relation comparison table: columns (1) property, (2) relation, (3) function. Rows: definition, vertical line test result, example mapping, example equation, example graph. Filling every cell forces a clear distinction between the two concepts — the row that matters most is the vertical line test row.",
        "Create a function families comparison table: rows are the six function types (linear, quadratic, exponential, reciprocal, square root, cubic); columns are (1) general form, (2) graph shape, (3) domain, (4) range, (5) distinctive feature (asymptote / vertex / intercept behaviour), (6) one real-world example. Cover columns 2–6 and generate from memory given only the general form. This builds automatic recognition of function families.",
        "Create a transformations comparison table: rows are the six transformations (vertical up, vertical down, horizontal right, horizontal left, reflection x-axis, reflection y-axis, vertical stretch, vertical compression); columns are (1) transformation name, (2) effect on equation, (3) effect on graph, (4) effect on a specific point (e.g. what happens to (3, 5)), (5) common error. The 'common error' column is the most important — anticipating mistakes prevents them.",
        "Create a domain-finding procedure table: rows are (1) linear/polynomial — no restrictions, (2) rational function — set denominator ≠ 0, (3) square root — set expression ≥ 0, (4) rational with root — apply both rules, (5) logarithm — set argument > 0; columns are (1) function type, (2) restriction rule, (3) example function, (4) domain result in interval notation. Use this table as a checklist for every domain problem.",
        "Create a one-to-one and inverse comparison table: columns (1) property, (2) one-to-one function, (3) NOT one-to-one. Rows: horizontal line test result, can it have an inverse function? (yes/no), example function, example of what goes wrong without restriction, fix (domain restriction). This table directly addresses the most common inverse function error."
    ],

    graphingPractice: [
        "Graph each function family from its equation on separate axes, without a calculator: (a) f(x) = 3x − 4, (b) f(x) = −(x − 2)² + 5, (c) f(x) = 2ˣ, (d) f(x) = 1/x, (e) f(x) = √(x + 1). For each: state the domain, state the range, mark intercepts, mark any asymptotes, draw the shape. Then write the equation of each function's inverse and sketch it on the same axes as a reflection in y = x.",
        "Transformations graphing drill: start with f(x) = x² drawn on graph paper. On the same diagram (in different colours), graph: g(x) = x² + 4, h(x) = (x + 4)², p(x) = −x², q(x) = 3x². For each, write the transformation in one sentence and verify by computing one transformed point. Time yourself — aim to complete all five in under 6 minutes, since transformation recognition should become automatic.",
        "Plot composite functions in stages: given f(x) = x + 2 and g(x) = x², compute and plot g(x) from x = −3 to x = 3. Then compute and plot f(g(x)) = x² + 2 on the same axes. Annotate three specific points showing how the g-output becomes the f-input. Repeat with f and g swapped to plot g(f(x)) = (x + 2)². This staged plotting makes the layered nature of composition visible.",
        "Domain and range from graphs: collect or sketch six graphs including at least one with a gap in the domain, one with a horizontal asymptote, and one restricted to x ≥ 0. For each, identify the domain and range by reading the graph — express both in interval notation. Then check by substituting boundary values algebraically. Reconcile any discrepancy.",
        "Inverse function graphing from the original: draw f(x) = 2x − 3 on a grid with the line y = x also drawn. Reflect three specific points of f in y = x to plot f⁻¹. Connect the reflected points with a line and verify the equation matches f⁻¹(x) = (x + 3)/2. Repeat with f(x) = x² (restricted to x ≥ 0), whose inverse is f⁻¹(x) = √x. This builds the geometric understanding of inverse functions before algebraic methods are applied."
    ],

    flashcards: [
        "Make a card for every key function definition: front = term (e.g. 'Inverse function'), back = definition + notation + one worked example + verification property. Include: function, domain, range, one-to-one, onto, bijection, composite, inverse, asymptote, vertical line test, horizontal line test. These twelve cards are the vocabulary layer — all other function work depends on them.",
        "Make a card for each function family: front = name (e.g. 'Exponential function'), back = general form + graph shape sketch + domain + range + distinctive features (asymptote, vertex, etc.) + one real-world example. Six cards — one per family. Test by covering the back and generating all fields from the name alone.",
        "Make a transformations card for each type: front = transformation description (e.g. 'Horizontal translation right 4 units'), back = what changes in the equation (x replaced by x − 4) + what changes on the graph + example (y = f(x − 4)) + one common error (confusing direction). Eight cards — one per transformation type. Use the common-error field every time.",
        "Make a composite function card: front = 'f(g(x)) — which function is applied first?', back = 'g is applied FIRST, then f is applied to the result of g.' Include the three-step process: (1) find g(x), (2) substitute result into f, (3) simplify. Back also shows a worked example with arrows showing the sequence. This card addresses the most common composition error.",
        "Make an inverse finding card: front = 'Steps to find f⁻¹(x)', back = (1) write y = f(x), (2) swap x and y, (3) rearrange to get y = ..., (4) write f⁻¹(x) = ..., (5) verify: f(f⁻¹(x)) = x. Include a reminder: 'Check f is one-to-one BEFORE finding the inverse.' Include one worked example of a linear and one of a non-linear function."
    ],

    mnemonics: [
        "For function notation: 'f(x) is f AT x, not f TIMES x' — say this aloud before every evaluation. The bracket in f(x) means INPUT, not multiplication. The phrase 'f OF x' captures this: f is the rule, x is what you feed into it.",
        "For composite function order: 'Right to Left — the rightmost function goes first.' In f(g(x)), read right to left: g acts on x first, then f acts on the result. Alternatively: 'Inside Out' — evaluate the inner function first, then the outer. Both mnemonics prevent the most common composite error.",
        "For transformation directions: 'OUTSIDE changes y (Vertical); INSIDE changes x (Horizontal and Opposite).' The word OHIO captures this: Outside = y, Inside = Opposite of what you expect. f(x − 3) shifts RIGHT (not left) because it is inside and opposite.",
        "For domain restrictions checklist: 'DREAD' — Denominator cannot be zero, Root (even) cannot take a negative, Every other expression is unrestricted, Apply all restrictions together, Domain is what remains. Work through DREAD for every rational or root function.",
        "For the inverse verification property: 'What goes in must come back out' — f⁻¹(f(x)) = x means: apply f, then undo it with f⁻¹, and you return to x. Think of putting on a shoe (f) and taking it off (f⁻¹) — you end up with a bare foot (x). This captures the inverse as a literal undoing of the original function."
    ],

    practiceRoutines: [
        "Function evaluation sprint: generate 10 expressions of the form f(a), f(−a), f(2a), f(a+1) for a given function f. Solve all 10 in under 8 minutes. Track three separate error types: arithmetic errors in simplification, substitution errors (failing to replace every x), and bracket expansion errors. Address whichever error type occurs most before the next session.",
        "Domain drill with interval notation: for each of 10 functions (mixture of rational, root, and combined), write the domain in both inequality and interval notation. Then categorise each domain as (a) all reals, (b) all reals minus a point, (c) half-line, (d) interval with a gap. Build familiarity with all domain shapes before exam practice.",
        "Transformation identification drill: given 8 pairs (f(x) and g(x)), identify the complete set of transformations mapping f to g for each pair. Express each transformation in words and in equation terms. Then reverse the exercise: given a transformation description, write the equation of g. This bidirectional practice builds fluency in both directions of the transformation language.",
        "Composite and inverse alternation: solve 4 composite problems and 4 inverse problems in alternating sequence (composite, inverse, composite, inverse...). After each inverse, verify using f(f⁻¹(x)) = x. After each composite, verify by evaluating at a specific number. The alternation prevents the two procedures from merging in memory.",
        "Function family identification from data: given 5 tables of (x, y) values, determine the function family for each using first differences (constant → linear), second differences (constant → quadratic), or ratios (constant → exponential). Write the explicit equation for each table, verify with two data points, and state the domain and range of the function in context. This routine builds the pattern-recognition skill essential for modelling problems."
    ],

    workedExampleAnalysis: [
        "Take the worked example for evaluating a composite function as an expression (f(x) = x² + 1, g(x) = 2x − 3, finding f(g(x))). Cover all steps after the setup. Try to write each step before revealing it. After completing the problem, repeat it using g(f(x)) and compare the two results. Annotate why the two composites differ — this active comparison develops the insight that composition is not commutative.",
        "Take the worked example for finding the inverse of a linear function (f(x) = 3x − 7). After following it, immediately attempt the inverse of g(x) = (2x + 5)/3 without looking at the worked example. Compare your steps to the template. Then find g(g⁻¹(x)) algebraically to verify. If any step differs from the template, identify which of the four steps you omitted or mis-executed.",
        "Take the domain-finding worked example for the combined restriction case (h(x) = √(x + 3)/(x − 1)). Cover the solution. List all restrictions first using the DREAD checklist. Then work through the solution and compare your restriction list to the worked answer. If any restriction was missed, return to DREAD and identify which letter you failed to apply.",
        "Take the quadratic transformation worked example (g(x) = −3(x + 2)² + 5 mapped from f(x) = x²). Cover the transformation list. Write your own list of transformations in order. Then reveal the worked solution and compare — particularly check (a) the direction of horizontal translation and (b) the order in which you applied vertical stretch and reflection. These are the two most commonly mis-ordered steps.",
        "Work backwards from a given composite: you are told that f(g(x)) = 6x² − 1 and that g(x) = x² − (1/6). Find f without being given it. Then verify by computing f(g(x)). Compare the difficulty of this reverse-engineering task to a standard composite — this inversion of the usual direction develops the decomposition skill needed for integration by substitution in calculus."
    ]
},


angles: {

            diagrams: [
                "Draw a single point with six rays radiating from it, creating six angles. Label each angle with a different type name: acute, right, obtuse, straight, reflex, full turn. Write the degree range for each. Draw a small arc to indicate each angle. Return to this master diagram whenever you need to classify an angle — always ask 'which section of this diagram does my angle fall into?'",
                "Draw two parallel lines cut by a transversal, clearly larger than you normally would. Use three distinct colours: one for corresponding angle pairs (F-shape), one for alternate angle pairs (Z-shape), and one for co-interior angle pairs (C-shape). Label each pair with its rule (equal or supplementary) and its shape name. This is your master parallel-lines reference — recreate it from memory until the colour associations are automatic.",
                "Draw a triangle with its three interior angles labelled a, b, c. Then extend one side to create an exterior angle d. Annotate: (1) a + b + c = 180° (interior sum); (2) d = a + b (exterior angle theorem); (3) d + c = 180° (straight line). Draw a second diagram showing the proof: a parallel line through the top vertex, with alternate angles labelled to show how the 180° rule is derived. These two diagrams capture all triangle angle facts.",
                "Build a polygon angle sum table as a visual diagram: draw each polygon from triangle to octagon in a row. Inside each, draw all the triangulation diagonals from one vertex, showing the (n − 2) triangles. Beneath each polygon write n, (n − 2), and the total angle sum. Beneath that, if regular, write the size of each interior and exterior angle. This visual sequence makes the formula concrete — the (n − 2) is not abstract when you can count the triangles.",
                "Draw the three parallel-line scenarios side by side on one page — corresponding (F), alternate (Z), co-interior (C) — each with the angle values marked: 70° and 70° for F; 70° and 70° for Z; 70° and 110° for C. Beneath each write the rule in words. Colour the equal angles the same colour. This side-by-side comparison prevents the single most common error: applying the equal-angles rule to co-interior angles."
            ],

            comparisonTables: [
                "Create a three-column comparison table of the parallel-line angle pairs: columns (1) name, (2) position/shape, (3) relationship. Rows: corresponding (F-shape, same side, equal), alternate (Z-shape, opposite sides, equal), co-interior (C-shape, same side, supplementary). Add a fourth column: (4) how to prove lines are parallel using this relationship. Cover columns 3 and 4 and reproduce from memory.",
                "Create a five-row comparison table of special triangles: columns (1) triangle type, (2) side property, (3) angle property, (4) example angles, (5) a diagram sketch. Rows: equilateral, isosceles, scalene, right-angled, right isosceles. This table is particularly useful before exam questions that give a diagram without labelling the triangle type — match the given information to the table.",
                "Create a comparison table of interior vs exterior angles for regular polygons: columns (1) polygon name, (2) n, (3) interior angle formula value, (4) exterior angle (= 360° ÷ n), (5) check (interior + exterior = 180°). Include triangle through dodecagon. The check column prevents the common error of using 360° ÷ n as the interior angle.",
                "Create a two-column table contrasting the interior angle sum formula for general vs regular polygons: left column = general polygon (use formula to find total sum; cannot use ÷ n); right column = regular polygon (use formula for total, then ÷ n for each; or use 360° ÷ n for exterior and subtract from 180°). Include the condition under which each approach is valid. This table resolves the most common polygon formula misapplication.",
                "Create a complementary vs supplementary vs full-turn comparison table: columns (1) relationship name, (2) sum, (3) example, (4) diagram type (corner, straight line, full rotation), (5) typical context. Rows: complementary (90°, corner of square), supplementary (180°, straight line), angles around a point (360°, full rotation). This anchors the three main angle-sum targets before any calculation."
            ],

            graphingPractice: [
                "Draw and measure ten angles using a protractor: draw five at random, measure each, then classify. Then draw five angles to specification — one of each type (acute, right, obtuse, straight, reflex). This physical drawing practice calibrates visual estimation so that diagrams in exam questions can be used as a sanity check even when not drawn to scale.",
                "Draw five sets of parallel lines with transversals on squared paper. For each, mark all eight angles formed at both intersections. Starting from one angle (e.g. 65°), find all other seven angles using only angle rules — no measuring. Vary the transversal angle each time (30°, 45°, 60°, 75°, 90°) to build recognition of all configurations.",
                "On graph paper, draw polygons with n = 3, 4, 5, 6, 8 sides. For each, draw all triangulation diagonals from one vertex, count the triangles, and verify the interior angle sum formula. For the regular versions, measure one interior angle and check it matches the formula. This turns the abstract formula into a verifiable geometric fact.",
                "Practice the 'angle chain' skill: draw a complex diagram with two parallel lines, a triangle formed by a transversal, and a polygon sharing a side with the triangle. Starting from one known angle, annotate each derived angle in order on the diagram, writing the rule beside each. Aim to find all unknown angles without erasing or restarting — this simulates the multi-step reasoning required in exam questions.",
                "Draw the same isosceles triangle five times, each with a different apex angle (20°, 60°, 90°, 100°, 120°). For each, calculate the base angles, draw the exterior angles, and verify both the interior angle sum and the exterior angle theorem. Annotate the triangle type (acute, right, obtuse) for each version. This variety prevents the mistake of associating isosceles triangles only with one visual form."
            ],

            flashcards: [
                "Make a card for each angle rule: front = rule name (e.g. 'Co-interior angles'), back = the relationship (sum to 180°) + the shape clue (C) + the condition (parallel lines only) + one worked example. Cover all eight rules: angles on a line, angles around a point, vertically opposite, corresponding, alternate, co-interior, triangle sum, exterior angle theorem.",
                "Make a card for each regular polygon from triangle to dodecagon: front = polygon name and sketch, back = n (sides), interior angle, exterior angle, and interior angle sum. Test by covering the back and reproducing all four values. Also test in reverse: cover the front, read the interior angle, and name the polygon — this prepares you for 'find the number of sides' questions.",
                "Make an angle-type card with all six types: front shows a sketch of the angle with an arc, back = name + degree range + a real-world example. Include a specific card for reflex angles (the one most often omitted) and full turns. Test by sketching an angle and naming its type before checking.",
                "Make a 'proof strategy' card for the most commonly tested proofs: (1) why alternate angles are equal, (2) why triangle angles sum to 180°, (3) why the exterior angle equals the sum of two remote interior angles. Front: theorem statement. Back: the two-sentence logical chain for each proof. Memorise the logical structure, not the wording.",
                "Make a 'formula selection' card for polygon questions: front = three scenarios (general polygon; regular polygon — find each angle; regular polygon — find number of sides). Back = formula and method for each. Use this card to select the method before every polygon problem rather than guessing which formula to use."
            ],

            mnemonics: [
                "For the three parallel-line pairs: 'F is Friendly (equal), Z is Zero-different (equal), C is Combined (supplementary).' The first letter of each key word matches the shape: F-Friendly (corresponding), Z-Zero-different (alternate), C-Combined (co-interior). Recall the letter, recall the shape, recall the rule.",
                "For the polygon interior angle sum formula: 'Take away Two, times One-Eighty' — (n − 2) × 180°. The phrase 'Take away Two' gives (n − 2) and 'times One-Eighty' gives × 180. Recite this phrase before every polygon calculation.",
                "For exterior angles of polygons: 'Three-Sixty Divided by the Number of Sides' — 360° ÷ n. This applies to ANY regular polygon's exterior angle. Writing '360 ÷ n' as a reflex before every regular polygon problem prevents the most common error (using the interior angle formula when the exterior is needed).",
                "For the exterior angle theorem in triangles: 'The Outside equals the Far Two Inside' — the exterior angle equals the two non-adjacent (far) interior angles. The phrase 'Far Two Inside' emphasises that the two angles are the ones NOT adjacent to the exterior angle.",
                "For co-interior vs alternate: 'Co means Co-operative — they cooperate to make 180°; Alternate means they Alternate — they swap sides and stay Equal.' This connects the word meaning to the mathematical property: co-interior angles work together to make a straight line; alternate angles just swap sides and remain the same."
            ],

            practiceRoutines: [
                "Angle identification drill: draw ten diagrams, each showing angles formed by intersecting lines, parallel lines with a transversal, or polygons. For each diagram, name every angle relationship visible before calculating any values. Practice the identification step separately from the calculation step — the most common exam error is calculating using the wrong rule because the identification was rushed.",
                "Five-minute missing angle sprint: complete ten missing-angle problems — covering all rule types (straight line, around a point, vertically opposite, parallel lines, triangles) — in five minutes. Track which rule type causes the most errors and focus the next sprint exclusively on that type. Aim for 10/10 accuracy before increasing speed.",
                "Polygon formula fluency drill: given ten polygon descriptions (e.g. 'regular polygon, interior angle 135°'; 'octagon, 7 angles known'; 'polygon with interior angle sum 1440°'), write the appropriate formula, solve for the unknown, and state the polygon name. Include at least three 'find the number of sides' questions, as these require inverting the formula.",
                "Angle chain practice: draw one complex diagram per session — two parallel lines, a transversal, and a triangle — and find all unknown angles from a single given angle. Number each step, write the rule beside it, and verify by checking that angles on each straight line sum to 180° and that the triangle angles sum to 180°. This multi-step practice is the format of the hardest exam questions.",
                "Error-detection practice: solve five angle problems deliberately making the most common error for each type (e.g. treating co-interior as equal, applying 180° sum to a quadrilateral). Then swap papers with a peer or review your work after 24 hours. Identifying errors in your own work trains the self-checking habit needed to avoid losing marks on problems you know how to solve."
            ],

            workedExampleAnalysis: [
                "Take the worked example for co-interior angles (from the parallelLinesAndTransversal section: 3x + 10° and x + 50°). Cover all steps after setting up the equation. Attempt each subsequent step before revealing it. For every step, write next to it: (a) the operation performed, and (b) the rule or principle that justifies it. If any step differs from the given solution, identify whether your approach is an equivalent method or an error.",
                "Take the exterior angle theorem worked example (exterior = 115°, angles 3x + 5° and 2x) and solve it using two different methods: (1) directly with the exterior angle theorem; (2) find the third interior angle first (180° − 115° = 65°), then use the triangle sum. Compare the number of steps. This comparison makes explicit why the exterior angle theorem is a time-saving shortcut.",
                "Take the regular polygon worked example (interior angle 150° → find n). Solve it in reverse: start with n = 12 and verify the interior angle. Then modify the target interior angle to 160° and find the new n. Then attempt a case that gives a non-integer n (e.g. interior angle = 100°) and explain why this means no regular polygon has this interior angle. Working in both directions and with impossible cases deepens formula fluency.",
                "Take the hexagon missing-angle worked example (five angles given, find the sixth). After working through it, modify it: replace one of the known angles with an algebraic expression. Re-solve the problem. Then modify again so that two angles are algebraic expressions that are related (e.g. one is twice the other). This graduated modification builds the skill of adapting a known example structure to a new algebraic situation.",
                "Compare the substitution method and the exterior angle sum method for finding a missing angle in a polygon: solve the same problem both ways — (1) using the interior angle sum formula and summing all known angles; (2) finding all exterior angles and using their 360° sum. Verify that both methods give the same answer. Articulate in one sentence which method was faster and when you would choose each — this metacognitive reflection is the mark of a fluent problem-solver."
            ]
        },

trigonometry: {

    diagrams: [
        "Draw a single right-angled triangle and label all three side-name types three times over — once with the reference angle at the bottom-left, once at the top, and once at the bottom-right. For each position, re-label which side is opposite, which is adjacent, and which is hypotenuse. This teaches the critical lesson that opposite and adjacent are relative to the reference angle, while hypotenuse is always fixed. Keep this diagram visible during every SOHCAHTOA problem.",
        "Draw the unit circle with all four quadrants clearly marked. Plot and label the coordinates (cos θ, sin θ) at 0°, 30°, 45°, 60°, 90°, 120°, 135°, 150°, 180°, 210°, 225°, 240°, 270°, 300°, 315°, 330°, 360°. Add the CAST labels in each quadrant. This single diagram contains all the information needed to find exact trig values and determine signs — recreate it from memory three times.",
        "Draw the two special triangles side by side on one card: (1) the 30-60-90 triangle with sides 1, √3, 2 and all angles labelled; (2) the 45-45-90 triangle with sides 1, 1, √2 and all angles labelled. From each triangle, write the six trig values (sin, cos, tan for both acute angles) directly beside it. This card replaces the special-angle table — derive the values from the geometry rather than memorising them in isolation.",
        "Draw one complete period of each of y = sin x, y = cos x, and y = tan x on the same page with the same x-axis scale (0° to 360°). Label every zero, maximum, minimum, and asymptote. Draw a vertical dashed line at 90° and annotate why sin peaks here (unit circle y-coordinate reaches 1), why cos is zero here (x-coordinate reaches 0), and why tan is undefined here (0 in the denominator). Connecting the graph features to the unit circle definition builds understanding rather than rote graph-shape memory.",
        "Draw a 'transformation parameter anatomy' diagram for y = a sin(bx + c) + d: draw one fully labelled transformed sine graph and annotate each feature — mark the amplitude |a| as a vertical bracket, the midline y = d as a dashed horizontal line, the period 360°/b as a horizontal bracket on the x-axis, and the phase shift −c/b as a horizontal arrow from the y-axis to the first maximum. Annotate a = 3 sin(2x − 60°) + 1 in full using this diagram. Recreate it for two further equations until annotation is automatic."
    ],

    comparisonTables: [
        "Create a three-column comparison table of the three trig graphs: columns (1) feature, (2) y = sin x, (3) y = cos x, (4) y = tan x. Rows: domain, range, period, amplitude, y-intercept value, zeros in 0°–360°, maximum value and where it occurs, minimum value and where it occurs, asymptotes (N/A for sin and cos). Completing this table requires you to know every key feature — use it as a pre-exam revision checklist.",
        "Create a four-column table for the sine rule vs cosine rule decision: columns (1) given information, (2) which rule, (3) which form of the rule, (4) one-line example. Rows: AAS (two angles, one side), ASA (two angles, one side), SSA (two sides, non-included angle), SAS (two sides, included angle), SSS (all three sides). For each SSA row, add a note about the ambiguous case. This decision table should be consulted before every non-right-triangle problem until the selection is automatic.",
        "Create a two-column identity reference table: column (1) identity name, column (2) the identity statement. Rows: Pythagorean primary; Pythagorean cosec-cot; Pythagorean sec-tan; Quotient tan; Quotient cot; sin double angle; cos double angle (all three forms); tan double angle. Cover column 2 and reproduce from memory. Then cover column 1 and name each identity from its formula — building recognition in both directions.",
        "Create a parallel comparison table of degree vs radian measure: columns (1) angle name, (2) degrees, (3) radians (exact), (4) radian decimal. Rows: 0°, 30°, 45°, 60°, 90°, 120°, 135°, 150°, 180°, 270°, 360°. Add a fifth column for sin and a sixth for cos values at each angle. This master reference table connects all four representations simultaneously and reveals patterns (e.g. sin and cos values mirror each other about 45°).",
        "Create a comparison table of the transformations of y = a sin(bx + c) + d vs y = a cos(bx + c) + d: columns (1) parameter, (2) effect on sine graph, (3) effect on cosine graph, (4) effect on y = tan(bx + c). Rows: a > 1, 0 < a < 1, a < 0, b > 1, 0 < b < 1, c > 0, c < 0, d > 0, d < 0. Noting that the effect is identical for both sine and cosine consolidates the transformation rules into one unified table."
    ],

    graphingPractice: [
        "Sketch the graphs of y = sin x and y = cos x on the same axes for 0° ≤ x ≤ 720° (two full periods). Without looking at notes, label all zeros, maxima, and minima with exact x-coordinates. Then draw a vertical line at x = 90° and annotate why the sine graph peaks while the cosine graph crosses zero — connecting the graphs to the unit circle. Repeat for x = 270° and x = 180°. Time yourself — aim for under 2 minutes per complete annotated graph.",
        "Graph five transformed trig functions from equations: y = 3 sin x, y = sin 2x, y = sin(x − 45°), y = sin x + 2, y = −sin x. For each, state the transformation in words before sketching. Then check by computing y at three key x-values and confirming they lie on your graph. This isolates the effect of each parameter a, b, c, d individually before combining them.",
        "Graph three functions and their solutions: for each of sin θ = 0.6, cos θ = −0.8, and tan θ = 2.4, draw the relevant trig graph, draw a horizontal line at the given value, and mark all intersection points in the range 0° to 360°. Label each intersection with its θ value (found using a calculator and CAST). This visual approach to solving trig equations builds intuition before pure algebraic methods become automatic.",
        "Practise 'graph reading': given five sketched trig graphs (drawn by a teacher or textbook), identify the equation y = a sin(bx + c) + d for each. Extract amplitude from the max-min range, period from two consecutive maxima, midline from the average of max and min, and phase shift from the first maximum position. Write the equation and verify by testing one point. This reversal of the usual direction (equation → graph) deepens understanding of each parameter's role.",
        "Graph a system of two trig equations on the same axes (e.g. y = 2 cos x and y = 1 − sin x for 0° to 360°) and estimate the x-values of intersection from the graph. Then solve the equation algebraically using identities and compare the algebraic solutions to your graphical estimates. Record the discrepancy — this reveals both the power and limitations of graphical methods for trig equations."
    ],

    flashcards: [
        "Make a card for each trig ratio and its reciprocal: front = 'sin θ in terms of sides', back = 'Opposite / Hypotenuse. Reciprocal: cosec θ = Hypotenuse / Opposite = 1/sin θ.' Include a small labelled triangle. Six cards cover all six ratios. Test by covering the back and writing the definition and reciprocal from the triangle sketch alone.",
        "Make a card for each special angle: front = the angle (e.g. '60°'), back = sin, cos, tan exact values with the fraction form and any surd form (e.g. sin 60° = √3/2, cos 60° = 1/2, tan 60° = √3). Include which special triangle the values come from. Eight cards cover 0°, 30°, 45°, 60°, 90°, 120°, 135°, 150° — the most common special angles in exam questions.",
        "Make a card for each major identity: front = the left-hand side (e.g. 'sin²θ + cos²θ'), back = '= 1. Derived from Pythagoras on the unit circle. Rearrangements: sin²θ = 1 − cos²θ; cos²θ = 1 − sin²θ.' Include a short note on the most common use of this identity. Six identity cards cover the primary Pythagorean form, the two sec-tan and cosec-cot forms, the quotient identity, and both double-angle formulas.",
        "Make a formula-selection card for triangle problems: front lists five scenarios (right-angled; AAS/ASA; SSA; SAS; SSS). Back states the rule for each and one key alert (e.g. 'SSA → sine rule, check ambiguous case'). Also add a sixth row: 'know two sides + included angle + need area → Area = ½ab sin C'. Use this card as a decision tool before every triangle problem until automatic.",
        "Make a CAST diagram card: front = blank unit circle divided into four quadrants. Back = the completed CAST diagram with letters and 'All Students Take Calculus' mnemonic, plus the related-angle rules for each quadrant (e.g. 'Quadrant 2: θ = 180° − reference angle; sin positive, cos and tan negative'). Test by drawing the CAST diagram from memory and writing the related-angle formula for each quadrant without looking at the back."
    ],

    mnemonics: [
        "SOHCAHTOA: 'Some Old Horses Can Always Hear Their Owner Approaching' — Sin = Opposite/Hypotenuse, Cos = Adjacent/Hypotenuse, Tan = Opposite/Adjacent. The three letters of each word match the initial letters of the ratio components. Write this out and verify it against the actual definitions at the start of every new SOHCAHTOA session.",
        "CAST anticlockwise: 'All Students Take Calculus' — starting from quadrant 1 (positive x, positive y) and moving anticlockwise: All positive (Q1), Sin positive (Q2), Tan positive (Q3), Cos positive (Q4). The fourth quadrant is labelled C (Cosine) and is where the rotation starts (nearest the positive x-axis), which is why the mnemonic begins with quadrant 4: Cast = C(Q4)-A(Q1)-S(Q2)-T(Q3).",
        "For remembering the cosine rule: 'Cosine connects the Included angle to the Side opposite it: c² = a² + b² − 2ab cos C. The lonely side c is opposite the named angle C.' The alliteration of 'cosine-connected-included-opposite' captures the geometry: the cosine rule always involves the angle sandwiched between the two known sides.",
        "For the three forms of cos 2A: 'Cosines go up, sines go down, mixed is the start' — cos 2A = 2cos²A − 1 (cosines only, going up); cos 2A = 1 − 2sin²A (sines only, going down — note the negative on sin²); cos 2A = cos²A − sin²A (mixed form — the starting point to derive the others). Link each form to its use: use the cosines-only form when you want to eliminate sin; use the sines-only form when you want to eliminate cos.",
        "For radian conversion: 'Divide to go to radians, multiply to return to degrees — and the bridge is always π/180 or 180/π.' Attach the memory hook: π radians = 180° looks like π = 180 if you 'forget the word radians' — and dividing any degree value by 180 and multiplying by π gives radians. Verify: 90° → 90 × π/180 = π/2 ✓; 360° → 360 × π/180 = 2π ✓."
    ],

    practiceRoutines: [
        "Special-angle fluency drill: complete a 5×5 table (rows: sin, cos, tan, cosec, sec; columns: 0°, 30°, 45°, 60°, 90°) with exact values from memory in under 3 minutes. Then derive any value you cannot recall from the special triangle diagrams rather than looking it up. Track errors by angle — if you consistently miss 30° values, spend five minutes deriving all six from the 30-60-90 triangle derivation before repeating the drill.",
        "CAST equation drill: solve 10 trig equations of the form sin/cos/tan θ = k (with both positive and negative k values) in the range 0°–360°, aiming for 10/10 in under 6 minutes. For each, write: (1) principal value; (2) CAST quadrants; (3) second solution formula; (4) both solutions. Include three equations where k is negative to practise quadrant identification for negative values — the most error-prone case.",
        "Triangle rule selection and execution drill: given 8 triangle problems with varied given information (AAS, SAS, SSS, SSA, right-angled), state the correct rule before calculating, then solve completely. After each problem, write one sentence justifying the rule choice. Time the set — aim for under 10 minutes total. If rule selection is taking longer than calculation, this signals the decision process needs more rehearsal with the comparison card.",
        "Identity proof practice: attempt five identity proofs per session. Start each by writing 'LHS only' and the three power moves (express in sin/cos; look for Pythagorean substitution; find common denominator). Record how many moves were needed for each proof. A clean proof requiring only one move is expert-level; a proof requiring all three plus manipulation is developing-level. Track this progression over multiple sessions.",
        "Graph transformation timed exercise: given five equations of the form y = a sin(bx + c) + d, write all four parameter values, state the resulting amplitude and period, and sketch one period — all within 90 seconds per equation. Use the annotations: amplitude = |a|, period = 360°/b, phase = −c/b, midline = d. A student who cannot complete this in 90 seconds needs more parameter-extraction practice before attempting full sketching problems."
    ],

    workedExampleAnalysis: [
        "Take the fully worked example for 'Solve 2sin²θ − cos θ − 1 = 0' (from the trigIdentities section). Cover the solution after 'Step 1'. Predict Step 2 (which Pythagorean substitution to use) before revealing it. The key decision point is recognising sin²θ = 1 − cos²θ as the bridge — if you chose to substitute cos²θ = 1 − sin²θ instead, work through that path and see why it creates a harder quadratic. Understanding why one substitution is cleaner than another is the mark of a proficient solver.",
        "Take the cosine rule worked example for finding angle A (from the sineAndCosineRules section, workedExampleAngle). Copy it out but change the sides to a = 6, b = 9, c = 11. Work through all four steps in parallel with the original. Then check your answer by verifying that the three angles of the triangle (find B and C using the same method) sum to 180°. This side-by-side structure builds procedural fluency while using a new numerical case.",
        "Find a CAST equation example with a negative trig value (e.g. sin θ = −√3/2) and work through the full solution. Then draw the unit circle and mark both solutions as points on the circle. Annotate why the reference angle (60°) appears in both solutions and how the quadrant determines whether the final angle is 180° + 60° or 360° − 60°. This visual annotation of an algebraic solution is the most effective technique for fixing the CAST rule permanently.",
        "Take the worked example for the trig identity proof 'tan θ + cot θ = sec θ cosec θ'. Cover the solution and attempt your own proof from LHS. Compare your working to the given solution step by step. If your proof used different intermediate steps but reached the same result, annotate why both paths are valid. If your proof failed, identify the specific step where you became stuck — was it writing tan as sin/cos, creating a common denominator, or recognising the Pythagorean identity in the numerator? Address that specific move.",
        "Work backwards from a trig graph to its equation: take a sketch of a transformed sinusoidal graph (you or your teacher can draw one with known parameters a, b, c, d) and determine the equation from the graph alone. Read off: maximum and minimum to find a and d; period to find b; the x-coordinate of the first maximum to find c. Write the equation, then verify by checking at least three specific points from the graph against your equation. This inversion of the usual workflow deepens mastery of every transformation parameter."
    ]
},

formulaRearranging: {

            diagrams: [
                "Draw the 'inverse operations ladder' for rearranging v = u + at for t: at the top write the formula; draw a downward arrow labelled with each operation applied to t in order (×a, then +u); then draw an upward arrow labelled with the inverse operations in reverse order (−u, then ÷a), arriving at t = (v − u)/a at the bottom. Reconstruct this diagram for three different formulae until the reverse-order pattern is automatic.",
                "Draw a 'balance scale' diagram for each rearranging step: draw a central fulcrum, the left side of the formula on the left pan, the right side on the right pan. Each time you apply an operation, draw it applied to both pans equally with a label (e.g. '÷a applied to both sides'). This visual reinforces the balance principle and makes visible exactly when a step applies an operation to only one term instead of the entire side.",
                "Draw the collect-factorise-divide flowchart for multi-step rearranging: box 1 = 'Does the target variable appear more than once?' → YES arrow → box 2 = 'Collect all target-variable terms to one side' → box 3 = 'Factorise: write as (target)(bracket)' → box 4 = 'Divide both sides by bracket'; NO arrow → standard inverse-operation chain. Use this flowchart as a decision tool at the start of every rearranging problem.",
                "Draw a 'box the radicand' diagram for square root rearranging: write T = 2π√(l/g), then draw a large box around the entire expression l/g under the square root. Annotate: 'This entire box is squared — not individual terms.' Show the squaring step, then the result T²/4π² = l/g. Contrast this with the common error (squaring only l or only g separately) by showing that error and crossing it out in red.",
                "Draw a side-by-side comparison of rearranging s = d/t for t (denominator case) versus rearranging d = st for t (numerator case): for the denominator case, show that the first step is always 'multiply both sides by t'; for the numerator case, show that division is the first step. Label each path clearly. Add a third path for t appearing inside a bracket. These three paths cover the majority of formula types."
            ],

            comparisonTables: [
                "Create a five-row comparison table of rearranging strategies: columns (1) strategy name, (2) when to use it (formula structure that triggers it), (3) first step, (4) key risk of error, (5) example formula. Rows: one-step, two-step reverse order, collect-factorise-divide, clear denominator, square/square-root. Cover column 3 and reproduce from memory.",
                "Create a three-column table comparing rearranging for a variable in a numerator versus in a denominator: columns (1) position of target variable, (2) first operation to apply, (3) example. Rows: in numerator (multiply or divide), in denominator (multiply both sides by the variable), equal to a reciprocal (take reciprocal of both sides). This table directly addresses the most common denominator confusion.",
                "Create a before-and-after comparison table for the collect-factorise-divide strategy: columns (1) stage name, (2) what the equation looks like, (3) what you do next. Rows: original (ax + b = cx + d), after collecting (ax − cx = d − b), after factorising (x(a − c) = d − b), final answer (x = (d − b)/(a − c)). Fill in a new example in the same table alongside the template.",
                "Create a two-column table of valid vs invalid applications of square roots: left column = INVALID (with explanation of why), right column = CORRECT equivalent. Rows: √(a² + b²) = a + b (wrong) vs √(a² + b²) stays as is; √(4x²) = 4x (wrong, sign) vs √(4x²) = 2|x|; squaring T/2π = √(l/g) term by term (wrong) vs squaring the entire left side (T/2π)² = l/g (correct). Memorise by generating a new correct-incorrect pair weekly.",
                "Create a verification procedure table: columns (1) step number, (2) what to do, (3) example (using v = u + at rearranged for t). Rows: (1) choose simple values for all variables except the target; (2) compute the target using the original formula; (3) substitute all values into the rearranged formula; (4) check agreement; (5) if disagreement, identify which step of the rearrangement fails this check. Use this table as a checklist for every rearrangement until verification is automatic."
            ],

            flashcards: [
                "Make a card for every formula in the commonFormulaeLibrary: front = formula in original form (e.g. 'T = 2π√(l/g)'), back = the formula rearranged for every variable listed. Test by covering the back and producing all rearrangements from scratch, then checking. Prioritise the physics and geometry cards as these are most frequently examined.",
                "Make a card for each rearranging strategy: front = strategy name and trigger condition (e.g. 'Collect-Factorise-Divide — target variable appears in more than one term'), back = the four steps in order with one example formula worked through. Test by covering the back and reproducing the steps and example.",
                "Make an inverse operations flashcard deck: front = operation (e.g. 'Squaring: x²'), back = inverse operation + rule for applying it in rearranging (e.g. 'Square-root both complete sides as a unit — never distribute over individual terms') + one correct and one incorrect example. This card addresses the most frequently lost marks in rearranging with roots.",
                "Make a verification method card: front = 'How do you verify a rearrangement?', back = the five verification steps with a worked example using F = ma rearranged for a. Test by covering the back and producing the verification method and example from memory. Commit to using this method after every rearrangement problem in practice.",
                "Make a 'danger zones' card: front = 'Top 3 rearranging errors', back = (1) applying an operation to one term only instead of the whole side; (2) forgetting to factorise when the target variable appears in two terms; (3) distributing a square root over individual terms. For each danger zone, write a one-line rule that prevents it. Review this card before every timed rearranging exercise."
            ],

            mnemonics: [
                "For the reverse-order rule: 'Last In, First Out' (LIFO) — the last operation applied to the target variable is the first to be undone. This is the same principle as a stack in computer science. Write LIFO at the top of every rearranging problem until the rule is automatic.",
                "For the collect-factorise-divide strategy: 'Collect, Factor, Divide — or you'll lose marks every time' (CFD). When you see the target variable in more than one term: Collect all instances to one side, Factor out the target variable, Divide both sides by the bracket. Three words, one sequence, applied every time.",
                "For the square root rule: 'Box Before You Root' — draw a box around the entire expression under the square root (or around the entire side before squaring), and remember the root or square applies to the whole box, never to individual terms inside it. The box is your visual reminder that √(a + b) ≠ √a + √b.",
                "For clearing denominators: 'Denominator Times Both' — when the target variable is trapped in a denominator, multiply BOTH sides by that denominator as the very first step. No exceptions. The formula s = d/t illustrates: t is trapped — multiply both sides by t → st = d → t = d/s.",
                "For verification: 'Three Numbers, Two Formulae, One Check' — choose three numbers (values for the known variables), compute the target variable using the original formula (one formula), then substitute all four values into the rearranged formula (second formula) and confirm agreement (one check). Three numbers, two formulae, one check — if the check fails, the rearrangement is wrong."
            ],

            practiceRoutines: [
                "Formula sprint: take five formulae from the commonFormulaeLibrary (one from each of physics, geometry, and chemistry) and rearrange each for every listed variable without looking at the answers. Time yourself. After the sprint, verify every rearrangement by substituting numbers. Track error type: wrong-order errors, missing-factorise errors, square-root-distribution errors. Focus repeat practice on the dominant error type.",
                "Structured difficulty progression: practise rearranging in four rounds. Round 1: one-step formulae only (F = ma, V = IR, C = 2πr — three each). Round 2: two-step formulae (v = u + at for each variable — three rearrangements). Round 3: collect-factorise-divide formulae (ax + b = cx + d style — three problems). Round 4: fractions and roots (1/f = 1/u + 1/v for u; T = 2π√(l/g) for l; KE = (1/2)mv² for v). Do not advance to the next round until the current round is error-free.",
                "Error-correction drill: obtain five worked rearrangements with deliberate errors (one per error type: wrong order, operation on one term only, no factorising, denominator not cleared, square root distributed). For each, identify the error without looking at the answer key, state the rule violated, correct the rearrangement, and verify. This trains the evaluative skill that distinguish strong exam responses.",
                "Derivation challenge: given any two formulae from the physics or chemistry library, derive a third formula by substituting one into the other and rearranging. Example: combine v = u + at and s = ut + (1/2)at² to eliminate t and derive v² = u² + 2as. Attempt this for three pairs per session. Each successful derivation demonstrates mastery of rearranging in its most demanding form.",
                "Timed verification routine: solve eight rearranging problems in timed conditions (90 seconds each). After the time expires for each, spend exactly 30 seconds verifying numerically. Record how many verifications revealed an error. The goal is zero errors detected at verification — meaning the rearrangement itself was done correctly under time pressure. If errors are found at verification, identify the type and add it to your targeted practice list."
            ],

            workedExampleAnalysis: [
                "Take the fully worked rearrangement of T = 2π√(l/g) for l from the lesson. Cover every step after Step 1. Predict the next step before revealing it. If your step differs, identify whether your approach is equivalent (both correct) or whether an error was made. After working through all steps, cover the solution entirely and reproduce it from scratch. Compare — any divergence reveals a gap in the procedure.",
                "Take a worked example using the collect-factorise-divide strategy (use the ax + b = cx + d example from the lesson). After reading it once, close the example and reconstruct it step by step with justification written next to each step. Compare your justifications to the lesson's annotations. Missing justifications identify steps you are executing procedurally without understanding — these are the steps to re-examine.",
                "Annotate a worked rearrangement of 1/f = 1/u + 1/v for u by writing next to each step: (1) what operation was applied; (2) why that operation was chosen; (3) which general rearranging principle it instantiates (e.g. 'subtract 1/v from both sides — inverse of addition — to isolate 1/u'). This annotation exercise forces explicit connection between each symbol-manipulation step and the underlying principle.",
                "Work backwards from the answer: given that the rearrangement of v² = u² + 2as for s is s = (v² − u²)/(2a), start from this answer and work backwards — applying forward operations in the correct order to reconstruct v² = u² + 2as. This inverted approach tests whether you understand the structure of the formula or are merely executing steps by rote.",
                "Compare two rearrangements of the same formula using different strategies: rearrange 3x + 2y = 12 for x both by (a) dividing every term by 3 at the start and (b) subtracting 2y first then dividing by 3. Record all steps for both approaches and verify both give the same answer. Then identify which approach produces fewer steps and smaller intermediate expressions — developing efficiency judgement alongside procedural accuracy."
            ]
        },


equations: {

    diagrams: [
        "Draw a single large diagram with five curves on the same axes — one for each equation family in this lesson: a parabola (quadratic), a wavy cubic (polynomial), a hyperbolic curve (rational), a V-shape (absolute value), and an exponential growth curve. Label each curve with its family name, a sample equation, and the phrase 'roots = x-intercepts'. This single diagram embeds the core geometric principle: solving an equation means finding where its graph crosses the x-axis.",
        "Draw the discriminant decision tree as a flowchart: start at the top with 'Compute Δ = b² − 4ac'. Branch left for Δ > 0 (label: two distinct real roots; parabola crosses x-axis twice; sketch). Branch centre for Δ = 0 (label: one repeated root; parabola touches x-axis; sketch). Branch right for Δ < 0 (label: no real roots; parabola above or below x-axis; sketch). Keep this visible for every quadratic discriminant task.",
        "Draw the absolute value function y = |x| as a V-shape, then draw the horizontal line y = k for k > 0, k = 0, and k < 0. Mark the intersections: two intersections when k > 0 (two cases); one intersection when k = 0 (one case); no intersections when k < 0 (no solution). Annotate the two intersection x-values for k > 0 as x = k and x = −k. This diagram justifies the algebraic split rule directly.",
        "Draw the logarithm and exponential curves y = eˣ and y = ln(x) on the same axes, reflecting them in the line y = x to show they are inverses. Mark the point (0, 1) on y = eˣ and (1, 0) on y = ln(x). Annotate: 'eˣ: domain all real x, range y > 0' and 'ln(x): domain x > 0, range all real y'. This diagram makes the domain restriction on logarithms visual and explains why log of a non-positive number is undefined.",
        "Draw a step-by-step flow diagram for solving a rational equation: box 1 → 'State restrictions (denominators ≠ 0)'; box 2 → 'Find LCD'; box 3 → 'Multiply EVERY term by LCD'; box 4 → 'Solve the resulting equation'; box 5 → 'Check solutions against restrictions'; box 6 → 'Report only valid solutions'. Connect each box with arrows and label the most common error at each step in red. Reproduce this flow from memory before every rational equation problem."
    ],

    comparisonTables: [
        "Create a six-row method comparison table for solving quadratic equations: columns (1) method, (2) when to use it, (3) advantages, (4) limitations, (5) one example equation suited to this method. Rows: factoring, completing the square, quadratic formula, graphical, square-root method (for x² = k), substitution (for disguised quadratics). Cover column 2 and reproduce method selection criteria from memory.",
        "Create a comparison table for exponential versus logarithmic equations: columns (1) equation type, (2) unknown location, (3) first move, (4) key law used, (5) domain/range restriction to check. Rows: exponential same-base (2ˣ = 8), exponential different-base (3ˣ = 20), logarithmic single term (log₂(x) = 5), logarithmic requiring combination (log(x) + log(x−2) = 1). Fill every cell.",
        "Create a three-column comparison of absolute value equation outcomes: columns (1) form of equation, (2) number of solutions, (3) reason. Rows: |A| = k with k > 0 (two solutions — two distances); |A| = 0 (one solution — only zero is zero distance); |A| = k with k < 0 (no solution — distance non-negative); |A| = |B| (two cases: A = B or A = −B). Include a number line sketch for each row.",
        "Create a solutions summary table for polynomial equations: columns (1) degree, (2) maximum real roots, (3) minimum real roots (for real-coefficient polynomials), (4) example, (5) factoring strategy. Rows: degree 1 (linear), 2 (quadratic), 3 (cubic), 4 (quartic). Note that odd-degree polynomials always have at least one real root — include this in the minimum column with a brief justification.",
        "Create a 'same structure, different context' table linking rational equation forms to their real-world interpretations: columns (1) rational equation form, (2) real-world context, (3) what the unknown represents, (4) restriction meaning. Rows: 1/a + 1/b = 1/t (work rate — two workers), 1/R = 1/R₁ + 1/R₂ (parallel resistors), 1/f = 1/u + 1/v (lens equation), d/r₁ + d/r₂ = T (average speed). Recognising the common structure across contexts is the key skill."
    ],

    graphingPractice: [
        "Graph five quadratic functions by hand: y = x² − 4 (crosses x-axis), y = x² + 4 (no x-intercepts), y = (x−2)² (touches x-axis), y = −x² + 3x (opens downward), y = 2x² − x − 1 (a ≠ 1). For each: compute the discriminant first to predict x-intercepts; find the vertex using x = −b/2a; plot the vertex, intercepts, and one additional point on each side. Label the axis of symmetry. Compare predicted roots to graphical x-intercepts.",
        "Graph the absolute value functions y = |x|, y = |x − 3|, y = |2x + 1|, y = −|x| + 4, and y = 2|x − 1| − 3 on separate axes. For each, identify the vertex (the tip of the V), the slope of each arm, and the x- and y-intercepts. Connect each graph to its equation by annotating which part of the equation controls the horizontal shift, vertical shift, reflection, and stretch.",
        "Graph exponential functions y = 2ˣ, y = (1/2)ˣ, y = 3·2ˣ, y = 2ˣ⁻¹ on the same axes. Label each with its key features: y-intercept, horizontal asymptote (y = 0), whether it grows or decays. Then graph their inverse logarithms y = log₂(x), y = log₂(x) + 1 on the same second set of axes, showing the reflection in y = x. Mark the point where the exponential and log curves intersect y = x (only for y = 2ˣ and y = log₂(x)).",
        "Sketch a cubic polynomial f(x) = (x+1)(x−2)(x−4) by: first listing the roots (−1, 2, 4); checking the leading coefficient sign (positive → rises to right); plotting the roots with crosses through the axis (all multiplicity 1); sketching the S-shaped curve through those roots. Then modify one root to multiplicity 2 — f(x) = (x+1)²(x−4) — and re-sketch, showing the touch-and-bounce at x = −1. Compare the two sketches to internalise the effect of multiplicity.",
        "Graph three rational functions: y = 1/(x−2), y = (x+1)/(x−2), y = (x²−4)/(x−2). For each: identify vertical asymptotes (denominator = 0), horizontal asymptotes (comparing degrees), x-intercepts, and y-intercepts. For the third function, simplify before graphing and note the removable discontinuity (hole) at x = 2. This visual exercise connects the algebra of rational simplification directly to a gap in the graph."
    ],

    flashcards: [
        "Make a card for each quadratic solving method: front = equation type cue (e.g. 'equation in form x² = k' or 'clearly factorable' or 'non-factorable, need exact answer'), back = method name + first step + one example. Include six cards covering: square root method, factoring (a=1), AC factoring method (a≠1), completing the square, quadratic formula, and discriminant-only analysis.",
        "Make a card for each logarithm law: front = law name and algebraic statement; back = a worked numerical example using log base 10 AND a worked example using the law to simplify a logarithmic expression for solving. Include: product law, quotient law, power law, change-of-base formula, and the inverse property (logₐ(aˣ) = x and a^(logₐx) = x). Never attempt a logarithmic equation without first reviewing these five cards.",
        "Make a card for the Factor Theorem: front = 'Factor Theorem — state it and its converse'; back = full statement + a worked example using f(3) = 0 to conclude (x−3) is a factor, then performing synthetic division to find the depressed polynomial. Include a second example on the reverse where f(2) = 4 ≠ 0, confirming (x−2) is NOT a factor.",
        "Make an extraneous solutions card: front = 'Name two equation types that can produce extraneous solutions and state why for each.' Back = (1) Rational equations — clearing the LCD multiplies by an expression that could be zero for restricted values; (2) Logarithmic equations — the solving process may produce values that fall outside the domain (log of non-positive number). Include one example of each type with the extraneous solution identified and discarded.",
        "Make a card for the absolute value two-case split: front = '|A| = k — write out both cases for k > 0, k = 0, and k < 0.' Back = complete rules for all three cases, plus a separate card for |A| = |B| (cases: A = B or A = −B). On the back, include a memory note: '|A| = |B| gives TWO cases, not four — because A = −(−A), so the four combinations reduce to two.'"
    ],

    mnemonics: [
        "For the quadratic formula: 'Negative b, plus or minus, square root of b squared minus 4ac, all over 2a' — say this aloud before every use until the formula is fully automatic. The rhythm of the phrase encodes the structure: (−b) in numerator, ±√(b²−4ac) added, divided by 2a.",
        "For the discriminant outcomes: 'Positive Discriminant — Pair of roots. Zero Discriminant — only One. Negative Discriminant — None.' PZN → Pair, Zero-one, None. Or: 'Two, One, None — the sign of Δ is done.' Associate with the parabola sketches: Δ > 0 parabola crosses twice, Δ = 0 parabola kisses axis, Δ < 0 parabola misses.",
        "For the absolute value split: 'SPLIT WHEN ISOLATED.' Do not split until the absolute value expression stands alone on one side. After isolation, remember: 'Positive k → Two cases. Zero k → One case. Negative k → No case (no solution).'",
        "For logarithm laws in sequence: 'Product goes Plus, Quotient goes Minus, Power comes in Front.' PPF or 'Plus, Minus, Front' — product rule (add logs), quotient rule (subtract logs), power rule (bring exponent to front as a multiplier). Associate each word with the corresponding algebraic operation.",
        "For avoiding the most common logarithm error: 'log(A + B) is NOT log(A) + log(B). Logs split products, not sums.' The log laws apply to products (multiplication) and quotients (division) inside the logarithm — never to sums or differences. Write 'LOGS SPLIT PRODUCTS, NOT SUMS' at the top of every logarithm problem until automatic."
    ],

    practiceRoutines: [
        "Discriminant drill: for 10 quadratic equations in mixed forms (some not in standard form), convert to standard form, compute Δ, classify the solution type, and sketch the parabola — all before solving. Check your predictions by solving with the formula. Track: (1) how often you correctly classified the type, (2) how often the sign error on b caused a wrong discriminant. This drill develops the habit of discriminant-first thinking.",
        "Factor Theorem candidate testing sprint: given three polynomials of degree 3 or 4, list all rational root candidates using ±(factors of constant)/(factors of leading coefficient), test the smallest candidates first using synthetic division, and factor each polynomial completely within 15 minutes. Focus on testing candidates in size order and performing synthetic division efficiently — full polynomial long division is slower and more error-prone.",
        "Equation type identification drill: given 12 equations of mixed types (quadratic, rational, absolute value, exponential, logarithmic, polynomial), identify the type of each equation and state the opening strategy for each — without solving. Do this within 5 minutes. The goal is instant recognition: seeing ax² + bx + c and reaching for the discriminant; seeing 1/x + ... and stating restrictions; seeing |A| and isolating before splitting.",
        "Extraneous solution verification routine: for every rational or logarithmic equation solved in any practice session, perform the verification check as a separate, labelled step. Write 'RESTRICTIONS: x ≠ ___' before starting. After solving, write 'CHECK: substitute x = ___ into original equation.' Never skip this step even if the solution looks obviously valid — the value that creates a restriction is often not the value that looks suspicious.",
        "Logarithm law consolidation practice: take 8 logarithmic expressions (not equations) and simplify each using the log laws, showing which law is applied at each step in the margin. Then take 5 logarithmic equations and solve each using the simplified single-log form. Track how many times you correctly consolidate multiple log terms before converting to exponential form — the most common error at developing level is converting before consolidating."
    ],

    workedExampleAnalysis: [
        "Take the completing-the-square worked example (x² + 6x + 5 = 0) from the lesson and cover all steps after step 1. Write the next step before revealing it. At step 2, pay particular attention to the value added: (6/2)² = 9, not 6² = 36 — the most common error. After working through the example, apply the same method to x² + 8x + 7 = 0 from scratch and verify both methods (completing the square and factoring) give the same roots.",
        "Take the synthetic division worked example (x³ − 6x² + 11x − 6 = 0) and work through the division step by completing it row by row, checking each multiplication and addition. After the full example, apply synthetic division to x³ − 2x² − 5x + 6 = 0, testing candidates in size order. Compare the efficiency of synthetic division versus full polynomial long division — count the number of written operations in each method.",
        "Take the rational equation worked example with an extraneous solution [x/(x−2) = 2/(x−2) + 1] and annotate every step with: (1) what operation was performed; (2) why this operation is valid; (3) what risk is introduced. At the conclusion, write 'result = identity → infinitely many candidates, but ALL are restricted by x ≠ 2 → no valid solution.' This worked example is the template for recognising identity-type rational equations.",
        "Take the logarithmic worked example [log(x) + log(x−3) = 1] and work through it with the following active protocol: before each step, predict what the next step should be; after each step, identify which log law was used; at the quadratic step, factor the quadratic before applying the formula (it factors easily). After completion, modify the right-hand side from 1 to 2 and solve the new equation, tracking how the domain check changes.",
        "Compare two solution methods for 4ˣ = 64: (a) same-base method — express 64 = 4³, equate exponents, x = 3; (b) logarithmic method — x = log(64)/log(4) = 1.806/0.602 = 3. Note that both methods give exactly x = 3. Then solve 4ˣ = 70 — the same-base method fails (70 is not a power of 4) but the logarithmic method gives x = log(70)/log(4) ≈ 3.07. This comparison makes explicit why the logarithmic method is the general-purpose tool."
    ]
},


geometricMeasurements: {

    diagrams: [
        "Draw every standard 2D shape (rectangle, triangle, parallelogram, trapezoid, circle) with its dimensions labelled using the variable names from the formula. For each shape, draw a dotted line showing the perpendicular height, label it 'h (⊥)' and colour it differently from the slant side. Alongside every parallelogram and triangle, draw the equivalent rectangle that has the same base and height — this makes the area formula's geometric origin visible rather than a fact to be memorised.",
        "Draw the net of every standard 3D solid (cuboid, triangular prism, cylinder, cone, square pyramid) on squared paper. Label every face with its area formula. For the cylinder, show the rectangle produced when the curved surface is unrolled, with its width labelled '2πr' and its height labelled 'h'. This net-drawing practice is the most reliable method for preventing face-omission errors in surface area calculations.",
        "Draw two identical circles side by side. On the first, label the radius r from centre to edge. On the second, label the diameter d from edge to edge through the centre and mark the centre point with a dot. Below both circles, write: 'Circumference: C = 2πr = πd' and 'Area: A = πr² — RADIUS ONLY, never diameter.' Recreate this from memory before every circle problem until the radius-first habit is automatic.",
        "Draw a cone and label all three heights: (1) vertical perpendicular height h from base centre to apex with a right-angle symbol; (2) slant height l from base edge to apex; (3) radius r along the base. Beside the diagram write: 'Volume uses h. Surface area uses l. l = √(r² + h²).' This single diagram addresses the most common cone calculation error.",
        "Draw a staircase diagram showing the relationship between linear, area, and volume units: top step = cm (×10 → mm); middle step = cm² (×100 → mm²); bottom step = cm³ (×1000 → mm³). Label each step with the conversion factor and an arrow showing the direction. Alongside each step, show why: '1 cm = 10 mm → 1 cm² = 10² mm² = 100 mm² → 1 cm³ = 10³ mm³ = 1000 mm³.' Extend to metres using 1 m = 100 cm."
    ],

    comparisonTables: [
        "Create a master formula table with seven columns: (1) shape name, (2) diagram/sketch, (3) perimeter or circumference formula, (4) area formula, (5) surface area formula, (6) volume formula, (7) units for each. Rows: rectangle, triangle, parallelogram, trapezoid, circle/sector, cuboid, cylinder, cone, sphere, square pyramid. Fill every applicable cell. Leave non-applicable cells blank (e.g. 2D shapes have no surface area column). This single table is the most useful revision resource for this entire topic.",
        "Create a 'Which height?' comparison table for formulas that involve height: columns (1) shape, (2) formula, (3) which height is used (perpendicular h vs slant l), (4) how to find the other if given one (Pythagoras), (5) common error. Rows: triangle area (⊥h; slant side is not height), parallelogram area (⊥h; adjacent side is not height), cone surface area (slant l; vertical h is not used), cone volume (⊥h; slant l is not used), pyramid surface area (slant l of face), pyramid volume (⊥h). Cover column 3 and reproduce from memory.",
        "Create a 2D versus 3D measurement comparison: columns (1) property, (2) 2D equivalent, (3) 3D equivalent. Rows: what is measured (boundary length vs outer skin; enclosed flat space vs enclosed space); units used (cm vs cm² vs cm³); how formula is derived (add sides vs add face areas; multiply dimensions vs multiply cross-section by depth); what it tells you in real life (fencing needed vs paint needed vs storage capacity).",
        "Create a 'factor identification' table: columns (1) formula, (2) the key numerical factor (1/2, 1/3, 4/3, 2, π), (3) geometric reason for that factor. Rows: triangle area (1/2: half a rectangle); parallelogram area (no fraction: full rectangle equivalent); trapezoid area (1/2: average of parallel sides × height); cone/pyramid volume (1/3: one-third of prism/cylinder); sphere volume (4/3: derived from integration); cylinder SA curved surface (2: two ends); sphere SA (4: four times area of great circle). Understanding the reason prevents the factor from being forgotten.",
        "Create a unit conversion reference table: headers — unit (mm, cm, m, km); length conversion from/to each; area conversion (squared); volume conversion (cubed); real-world example for each unit. Practise covering the area and volume columns and reproducing the correct squared and cubed conversions. The most useful single drill: write '1 m = ___ cm, so 1 m² = ___ cm², so 1 m³ = ___ cm³' and complete without the table."
    ],

    graphingPractice: [
        "Practise sketching 3D solids in isometric form on dotted isometric paper: cuboid, triangular prism, cylinder, cone, pyramid. For each solid, label all dimensions given in a problem on your sketch before applying any formula. The act of labelling forces you to identify which dimensions are present and which need to be calculated (e.g. slant height from Pythagoras). Students who sketch before calculating make far fewer formula-selection errors.",
        "Practise the 'net-to-formula' cycle for surface area: for each solid, (1) draw the net; (2) label each face's dimensions; (3) write the area formula for each face; (4) sum the areas; (5) verify against the standard formula. Do this for cuboid, triangular prism, cylinder, and square pyramid in a single session. Once the cycle is fluent for all four, the standard formula can be derived rather than recalled — and cannot be forgotten.",
        "Practise 'dimension hunting' problems: draw a solid with two out of three dimensions given (e.g. a cylinder with volume 200 cm³ and radius 4 cm — find height). Write the formula, substitute the known values, isolate the unknown algebraically, then verify by substituting back into the original formula. This routine applies to every formula in the topic and builds the algebraic confidence needed for reverse-calculation problems.",
        "Practise composite solid decomposition: take five descriptions of composite solids and draw them. For each, draw a labelled sketch showing the decomposition into standard components, mark which surfaces are internal (not included in surface area) and which are external, and plan the calculation before executing it. This planning-before-calculating habit is the single most effective intervention for preventing errors in composite solid problems.",
        "Practise sector and arc problems using a protractor: draw circles with radius 6 cm and measure sectors of 45°, 90°, 120°, and 270° with a protractor. For each, physically measure the arc length with a thread and compare to the calculated value (θ/360 × 2πr). This hands-on approach builds intuition for the fraction of the full circle that a sector represents and prevents the common error of applying the full circumference formula to arc length problems."
    ],

    flashcards: [
        "Make a formula card for every shape: front = shape name + a small sketch with variables labelled; back = all applicable formulas (perimeter, area, surface area, volume as appropriate) with variable definitions. Crucially, include a 'WATCH OUT' note for the most common error for that shape (e.g. for cone: 'Volume uses vertical h, NOT slant l. SA uses slant l = √(r² + h²), NOT vertical h'). Review all cards before any test.",
        "Make a 'units' card: front = 'What units does AREA use? What about VOLUME?'; back = 'Area: always SQUARE units (cm², m², mm²). Volume: always CUBIC units (cm³, m³, mm³). If your area answer says cm³, you have used the wrong formula.' Keep this card visible during every problem until the unit-check is automatic.",
        "Make a '1/3 solids' card: front = 'Which solids use the factor 1/3 in their volume formula?'; back = 'Pyramid: V = (1/3) × base area × h. Cone: V = (1/3)πr²h. BOTH are one-third of their corresponding prism/cylinder. Sphere: V = (4/3)πr³ — NOT 1/3, but 4/3.' This card targets the single most commonly forgotten numerical factor in the topic.",
        "Make a Pythagoras-in-3D card: front = 'How do you find the slant height of a cone?' and 'How do you find the slant height of a pyramid face?'; back = 'Cone: l = √(r² + h²) — right triangle with legs r and h. Pyramid (square base): l = √((b/2)² + h²) — right triangle with legs (half base) and height.' Alongside each, sketch the cross-section triangle that generates the Pythagoras calculation.",
        "Make a reverse-calculation card: front = 'A cylinder has volume 500 cm³ and height 8 cm. Find the radius.'; back = 'V = πr²h → 500 = πr² × 8 → r² = 500/(8π) = 19.89... → r = √19.89 = 4.46 cm.' The key annotation: 'REARRANGE FIRST — isolate r² before taking the square root.' Make similar cards for finding radius from circumference, from area, and from surface area."
    ],

    mnemonics: [
        "For the area of a trapezoid: 'Add the Parallel sides, Half them, then Height' → A = (1/2)(a + b)h. The mnemonic 'A Peculiar Half-sized Hat' encodes (A = Parallel-sum × Half × Height). Alternatively, think of the trapezoid as two triangles or as the average of the two parallel sides times the height — the average idea is geometrically the cleanest.",
        "For distinguishing surface area from volume units: 'Two-D for the skin, Three-D for the filling' — surface area covers the 2D skin of a 3D object (square units); volume measures the 3D filling (cubic units). After writing any answer, ask: 'Skin or filling?' and assign the correct unit accordingly.",
        "For the sphere formulas: 'Four Radius Squared for the surface, Four-thirds Radius Cubed for the space' → SA = 4πr², V = (4/3)πr³. Note the pattern: SA has r² (two-dimensional) and V has r³ (three-dimensional). The coefficient of V is one-third of the SA coefficient, reflecting the general relationship between surface area and volume for a sphere.",
        "For the cone and pyramid 1/3 rule: 'Three cones fill the cylinder, three pyramids fill the prism' — a cone and a cylinder with equal base and height have a 3:1 volume ratio; fill the cone three times and you fill the cylinder. Visualising this physical experiment makes the 1/3 factor unforgettable.",
        "For the area unit conversion trap: 'Square the scale, cube the scale' — if the linear scale factor is 100 (1 m to 100 cm), then area scales by 100² = 10 000 and volume scales by 100³ = 1 000 000. Whenever converting area or volume units, ask yourself: 'Have I squared (for area) or cubed (for volume) the linear conversion factor?' This single question prevents the most common unit conversion error in the topic."
    ],

    practiceRoutines: [
        "Formula identification drill: write the names of ten geometric shapes and solids on index cards. Shuffle them. For each card drawn, write down every applicable formula (perimeter, area, surface area, volume) from memory before checking. Track which shapes you hesitate on and prioritise those in the next session. Aim for 100% fluency — not checking a single formula — across all ten shapes in under 4 minutes.",
        "Perpendicular height drill: prepare ten triangle and parallelogram diagrams where both the perpendicular height and a slant side are labelled with numbers. For each, circle the correct height to use in the area formula before calculating. Include two traps where the slant side has a suspiciously round number and the perpendicular height has a decimal — this tests resistance to choosing the 'easier-looking' number.",
        "Surface area net practice: for each of five 3D solids (cuboid, cylinder, triangular prism, cone, square pyramid), draw the net, label all dimensions, calculate each face area, and sum to give the total surface area. Then verify against the formula. Track time per solid — when you can complete all five in under 20 minutes with no errors, the net method is fully automatic.",
        "Unit conversion sprint: write twenty conversion questions mixing area and volume units (e.g. '3.5 m² = ___ cm²', '250 000 cm³ = ___ m³', '4.2 litres = ___ cm³'). Complete under timed conditions (target: under 6 minutes). After checking, categorise errors as (a) wrong conversion factor, (b) multiplied instead of divided, or (c) applied linear factor instead of squared/cubed. Focused repeat practice on the most frequent error category.",
        "Reverse calculation routine: for each volume formula, construct five problems where the volume is given and one dimension is unknown. For each problem: (1) write the formula; (2) substitute known values; (3) rearrange algebraically to isolate the unknown; (4) calculate; (5) verify by substituting back into the formula. This routine builds the algebraic fluency needed for the harder exam questions and integrates formula recall with equation solving."
    ],

    workedExampleAnalysis: [
        "Take the cone surface area worked example from the lesson (radius 5 cm, vertical height 12 cm). Before reading the solution, attempt the problem yourself. Then compare your solution step by step against the given solution. Pay particular attention to Step 2 (finding slant height using Pythagoras) — identify whether you completed this preliminary step or attempted to substitute vertical height directly into the surface area formula. If you skipped Pythagoras, annotate your solution with 'ALWAYS find slant height before SA formula for a cone.'",
        "Take a composite solid worked example (cylinder plus cone) and annotate every step with: (1) which formula is being applied; (2) which measurement is being substituted; (3) why this face or component is being included or excluded from the surface area calculation. This triple annotation forces active engagement with the decisions at each step rather than passive reading of the arithmetic.",
        "Work backwards from a surface area answer: given that the surface area of a closed cylinder is 314 cm², construct two equations — 2πr² + 2πrh = 314 and, separately, assume h = 2r (optimal cylinder). Solve for r and h. Then verify by forward substitution. This reverse-engineering approach deepens understanding of the formula structure and previews optimisation problems.",
        "Take a unit conversion worked example (e.g. converting 2.4 m³ to cm³ and then to litres). Cover the solution and attempt each step yourself. After completing each step, reveal the given step and compare. For any step where you used a different conversion factor, trace the error to its source: did you apply a linear factor, a squared factor, or the correct cubed factor? Write the correction on a sticky note and attach it to your conversion table.",
        "Compare two methods for the same composite area problem: (1) decompose into two rectangles and add; (2) treat as a large rectangle and subtract the missing section. Verify both methods give identical answers. Annotate which method required fewer steps and explain in one sentence why that method is more efficient for this shape. Developing the habit of choosing the more efficient decomposition strategy before calculating is what distinguishes fluent problem-solvers from mechanical ones."
    ]
},


linearEquations: {

            diagrams: [
                "Draw the coordinate plane with all four quadrants clearly labelled. On the same diagram, draw five lines: positive slope, negative slope, zero slope (horizontal), undefined slope (vertical), and slope of exactly 1. Label each with its slope value and write a one-sentence interpretation of what each slope means physically (e.g. 'slope −2: y decreases by 2 for every 1 unit increase in x'). Use this as a visual reference for every graphing problem.",
                "Draw a single line in slope-intercept form (e.g. y = 2x + 3) and annotate every component: (1) the y-intercept dot at (0, 3) labelled 'b = 3: start here'; (2) a right-angle rise/run triangle from the intercept showing rise = 2 and run = 1 labelled 'm = 2 = 2/1'; (3) a second point at (1, 5) confirmed by substitution. Recreate this diagram from memory for three different equations until the annotation is automatic.",
                "Draw three parallel diagrams side by side — each showing a different system outcome: (a) two lines crossing at a single point labelled '(x, y) = one solution'; (b) two parallel lines labelled 'no intersection = no solution — same slope, different intercepts'; (c) one line drawn twice in different colours labelled 'identical lines = infinite solutions — same slope, same intercept'. Beneath each, write the algebraic signal: (a) unique x and y; (b) contradiction like 0 = 5; (c) identity like 0 = 0.",
                "Draw a number line for inequality solutions. For each type — x > a, x ≥ a, x < a, x ≤ a — draw the correct number line representation: open circle for strict inequalities, filled circle for non-strict. Then shade the correct direction. Underneath each number line, write the corresponding set notation and one test value that satisfies the inequality and one that does not.",
                "Draw the step-by-step transformation of solving 3(2x − 4) = 2x + 8 as a visual flow: draw the equation at the top, then each step below it connected by an arrow labelled with the operation performed (e.g. 'expand brackets', 'subtract 2x', 'add 12', 'divide by 4'). Circle the final solution and draw a return arrow labelled 'check' showing the substitution verification. This visual flow makes the sequence of inverse operations concrete."
            ],

            comparisonTables: [
                "Create a four-column comparison table of the three equation forms: columns are (1) form name, (2) equation template, (3) what you can read off directly, (4) best used when. Rows: slope-intercept (y = mx + b — read m and b directly — graphing quickly), standard (Ax + By = C — find both intercepts easily — elimination in systems), point-slope (y − y₁ = m(x − x₁) — write the equation fast — given slope and one point). Memorise by converting one example equation into all three forms.",
                "Create a five-column table comparing the three methods for solving systems: columns (1) method name, (2) how it works in one sentence, (3) best suited when, (4) main risk/error, (5) one example system it solves neatly. Fill every cell. Use this to guide method selection before every system problem rather than defaulting to substitution for all problems.",
                "Create a parallel-vs-perpendicular comparison table: columns (1) relationship name, (2) slope condition, (3) algebraic test, (4) geometric appearance, (5) example equation pair. Also add a row for coincident lines (same line). Cover column 2 and reproduce from memory.",
                "Create a three-column table of inequality vs equation differences: columns (1) feature, (2) equation (=), (3) inequality (< ≤ > ≥). Rows: solution set (single value vs range), graph (point vs ray/region), reversal rule (N/A vs flip when ×/÷ by negative), checking method (substitute back vs test a value in the region). This table addresses the single most common source of inequality errors.",
                "Create a comparison table of slope types: columns (1) slope value, (2) line direction, (3) equation example, (4) real-world meaning. Rows: positive, negative, zero, undefined. Add a fifth row for 'slope = 1' (45° diagonal) as a visual benchmark. Include a small sketch of each line type in the table."
            ],

            graphingPractice: [
                "Graph five equations in slope-intercept form without a calculator: y = 2x + 1, y = −(1/3)x + 4, y = −2x, y = 3, x = −2. For each, write the slope and y-intercept, plot the y-intercept first, use rise/run to find a second point, and verify a third point by substitution. Annotate which lines are horizontal, vertical, positive, or negative slope. Time yourself — aim for under 90 seconds per graph.",
                "Convert five equations from standard form to slope-intercept form, graph each, and label both x and y intercepts: 2x + y = 8, 3x − 4y = 12, x − 2y = −6, 5x + 5y = 20, 2x − y = 0. For each, also verify the intercepts algebraically (set y = 0 for x-intercept; set x = 0 for y-intercept). Compare the two methods of finding intercepts — which is faster?",
                "Solve five systems graphically on graph paper before solving algebraically: choose systems where the solution is an integer point so you can verify the graph. After graphing each, solve algebraically and confirm that the intersection matches. Record any case where your graph gives the wrong answer — this reveals both graphing errors and the limitation of graphical methods for non-integer solutions.",
                "Build a slope intuition exercise: given ten pairs of points, calculate the slope for each pair mentally (or with minimal written work) and predict whether the line rises steeply, rises gently, falls steeply, or falls gently before checking. Sort the slopes from most negative to most positive. Graph the steepest and gentlest lines on the same axes to build a visual vocabulary of slope magnitude.",
                "Graph a system of two linear inequalities on the same axes, shade each region in a different colour, and identify the overlapping (feasible) region. Test three specific points — one in each individual shaded region but not the overlap, and one in the overlap — by substituting into both original inequalities. This builds the skill needed for linear programming problems."
            ],

            flashcards: [
                "Make a card for every key formula: front = formula name (e.g. 'Slope formula'), back = the formula + what each symbol means + one worked example. Include: slope formula, slope-intercept form, standard form, point-slope form, condition for parallel lines, condition for perpendicular lines, midpoint formula (for extension).",
                "Make a card for each type of special line: front = description (e.g. 'Horizontal line through (0, 4)'), back = equation + slope + intercepts + sketch. Types: horizontal, vertical, line through origin, line with slope 1, line with slope −1. These five cards cover the most common exam graph-recognition tasks.",
                "Make a card for each system outcome: front = outcome name (e.g. 'Inconsistent system'), back = geometric description + algebraic signal + slope/intercept condition + example equations. Covers one solution, no solution, infinite solutions. Test by covering the front and generating the name from the back.",
                "Make an inequality rule card: front = 'What happens to the inequality sign when you multiply or divide both sides by a negative number?', back = 'The sign REVERSES direction.' Include three worked examples — one with multiplication, one with division, one where students commonly forget because the negative is in the variable term (e.g. −x < 5 → x > −5). Never attempt an inequality problem without reviewing this card first.",
                "Make a system-solving method selection card: front = three system scenarios (both equations in standard form; one equation already solved for y; both equations with same coefficient of x), back = recommended method for each (elimination; substitution; elimination — subtract equations directly). This builds the habit of choosing a method strategically rather than by default."
            ],

            mnemonics: [
                "For slope-intercept form y = mx + b: 'My eXcellent Brother' — m is the coefficient of x (My eXcellent), b is the standalone constant (Brother). The slope is always attached to x; the intercept is always the loose number.",
                "For the inequality reversal rule: 'Divide by Negative — Flip the Sign, or your answer will be Wrong by Design.' Write this on top of every inequality problem until the habit is automatic.",
                "For the three system outcomes: 'One, None, or All' — intersecting lines give One solution; parallel lines give None; identical lines give All (infinite). The first letter sequence O-N-A also stands for 'Only, Never, Always' — the line either Only crosses once, Never crosses, or Always overlaps.",
                "For identifying slope from a graph using two points: 'Rise over Run, left to right, no exception' — always read the rise (vertical change) in the numerator and the run (horizontal change) in the denominator, always moving left to right so that run is always positive.",
                "For perpendicular slopes: 'Flip and Negate' — take the slope of the original line, flip it (take the reciprocal), and change its sign. For slope 3/4: flip to 4/3, negate to −4/3. For slope −2: flip to −1/2, negate to +1/2. Two words — Flip, Negate — cover the complete procedure."
            ],

            practiceRoutines: [
                "Two-step equation fluency drill: solve 10 equations of the form ax + b = c in under 5 minutes. Then advance to 10 equations with variables on both sides (ax + b = cx + d). Track your error rate separately for sign errors, arithmetic errors, and structural errors (wrong step order). Focus repeat practice on whichever error type dominates.",
                "Slope calculation sprint: given 10 pairs of points, calculate the slope for each using m = (y₂ − y₁)/(x₂ − x₁). Aim for 10/10 correct in under 3 minutes. Common trap: include two pairs where Δy = 0 (horizontal line, slope = 0) and two where Δx = 0 (vertical line, slope = undefined) — these test whether you recognise the special cases.",
                "Equation writing drill: given 10 descriptions (slope + y-intercept; slope + one point; two points; parallel to a given line through a point; perpendicular to a given line through a point), write the equation in slope-intercept form for each. Work through all five description types at least twice per session until all are equally fluent.",
                "System solving rotation: solve 6 systems — 2 using substitution, 2 using elimination, 2 using the graphical method. For each, state why you chose the method, solve completely, verify both components of the solution in both equations, and state the geometric meaning. The rotation prevents over-reliance on one method.",
                "Inequality practice with built-in verification: solve 8 linear inequalities (including at least 2 that require reversing the sign). After each solution, (a) circle the sign and write 'REVERSED' or 'UNCHANGED' explicitly; (b) test one value inside the solution set to confirm it satisfies the original inequality; (c) test one value outside the solution set to confirm it does not satisfy it. This three-step verification makes the sign-reversal rule automatic."
            ],

            workedExampleAnalysis: [
                "Take a fully worked solution to a system-by-elimination problem (use the worked example in the systemsOfEquations lesson section: 2x + 3y = 12 and 4x − y = 10). Cover all steps after the first. Try to write the next step before revealing it. Compare your step to the given step — identify any difference in approach or notation. Repeat for each step. This active engagement with worked examples (rather than passive reading) is proven to accelerate procedural fluency.",
                "Take a worked example containing a deliberate error (e.g. the solution to 3(2x − 4) = 2x + 8 where the student writes 6x − 4 = 2x + 8 after expanding instead of 6x − 12 = 2x + 8). Identify the error, correct it, and complete the solution from the correction point. Then solve from scratch and compare. This 'error-correction' technique trains attention to the expansion step, where bracket mistakes are most common.",
                "Take any worked example from the lesson and annotate it with justification for every step: next to each line of algebra, write a phrase explaining what operation was performed and why (e.g. '÷4 both sides to isolate x'). This transforms passive example reading into active reasoning. After annotating, cover the original and reproduce the solution from your annotations alone.",
                "Work backwards from a solution: given that the answer to a system is (2, −1), reconstruct a system of two equations with this solution, solve your system from scratch to verify, and then modify one equation to create a system with no solution and another to create a system with infinite solutions. This inverts the usual direction of thinking and deepens understanding of what solutions mean structurally.",
                "Compare two methods on the same system: solve one system using both substitution and elimination. Write both solutions in parallel columns. Identify which method required fewer steps and smaller numbers. Then justify in one sentence which method you would choose for this system if seeing it fresh — articulating method selection builds the metacognitive skill that distinguishes fluent problem-solvers from procedural ones."
            ]
        }

};

const EndSection12 = "close"