


this.assessmentQuestions = { 


matterParticleTheory: {
    particleModel: {
        remember:   "State three assumptions of the kinetic particle theory. Define: (a) diffusion; (b) temperature (in terms of particles); (c) absolute zero. Write the equation for specific latent heat and define every symbol.",
        understand: "Explain why diffusion is much slower in liquids than in gases, even though liquid particles are also in continuous motion. Your answer must reference particle spacing, collision frequency, and mean free path. Explain why diffusion rates increase with temperature.",
        apply:      "Ammonia gas (M = 17 g/mol) and hydrogen chloride gas (M = 36.5 g/mol) are released simultaneously from opposite ends of a 120 cm sealed tube. Using Graham's law, calculate the distance from the ammonia end at which the white smoke of ammonium chloride will form.",
        analyze:    "In a diffusion experiment, bromine vapour (brown, M = 160 g/mol) is introduced at one end of a tube. After 10 minutes, the colour front has advanced 30 cm. An unknown gas is simultaneously introduced from the same end under identical conditions. After 10 minutes, the unknown gas has advanced 45 cm. Calculate the molar mass of the unknown gas using Graham's law and suggest one gas that this could be.",
        evaluate:   "Evaluate the following student explanation: 'Diffusion is faster in gases than liquids because gas particles are lighter and therefore move faster.' Identify what is correct, what is incomplete, and what is missing from this explanation. Provide a complete corrected explanation that addresses all relevant factors.",
        create:     "Design a complete experiment to demonstrate and compare the rates of diffusion of ammonia and hydrogen chloride using the two-gas tube method. Include: (a) apparatus and setup; (b) method for simultaneous release; (c) how the meeting point is identified; (d) expected result calculated from Graham's law; (e) two sources of experimental error and how each would affect the result."
    },

    statesOfMatter: {
        remember:   "Draw labelled particle diagrams for a solid, a liquid, and a gas. For each state, state: (a) particle arrangement; (b) type of particle motion; (c) strength of intermolecular forces; (d) whether it has a fixed shape; (e) whether it has a fixed volume; (f) whether it is compressible.",
        understand: "Explain why gases have much lower densities than liquids or solids. Your explanation must reference: (a) the typical ratio of particle separation in gases vs liquids; (b) the cause of that large separation; (c) why gases are compressible but liquids are not.",
        apply:      "A gas occupies 750 cm³ at 120 kPa and 17°C. It is compressed to 250 cm³ and cooled to −23°C. Calculate the new pressure using the combined gas law. Show all working, including temperature conversion.",
        analyze:    "The following data are recorded for a gas: at 300 K, pressure = 200 kPa; at 400 K, pressure = 267 kPa; at 500 K, pressure = 333 kPa. All measurements are at constant volume. (a) Show that these values are consistent with the pressure-temperature law by calculating p/T for each pair. (b) Predict the pressure at 600 K. (c) Predict the temperature at which the pressure would reach zero — explain what this temperature represents.",
        evaluate:   "Evaluate the claim: 'A liquid is simply a less compressed gas — as you compress a gas enough, it eventually becomes a liquid.' Identify what is correct and what is fundamentally wrong with this claim. Explain the key structural difference between a gas and a liquid at the particle level, and describe what actually happens during condensation.",
        create:     "Construct a complete quantitative comparison of the particle behaviour of water and steam at 100°C at atmospheric pressure. Include: (a) particle arrangement and spacing; (b) a calculation of the volume ratio of 1 g of steam vs 1 g of liquid water at 100°C, using the ideal gas equation to estimate steam volume; (c) an explanation of why the density ratio is so extreme; (d) the energy implications of this density difference for the steam engine."
    },

    changesOfState: {
        remember:   "Name all six changes of state and give the direction of each (e.g. solid → liquid = melting). For each, state whether it is endothermic or exothermic. Write the equation for specific latent heat. State the difference between evaporation and boiling.",
        understand: "Explain why the specific latent heat of vaporisation of water (2,260,000 J/kg) is much greater than the specific latent heat of fusion (334,000 J/kg). Your explanation must describe what happens to the intermolecular forces during melting and during boiling at the particle level.",
        apply:      "500 g of ice at 0°C is heated until it becomes steam at 100°C. Calculate the total energy required. (L_f = 334,000 J/kg; c_water = 4,200 J/kg°C; L_v = 2,260,000 J/kg.) Show each stage clearly: (a) energy to melt ice at 0°C; (b) energy to heat water from 0°C to 100°C; (c) energy to boil water at 100°C.",
        analyze:    "A heating curve is recorded for a 0.4 kg sample. The heater supplies 800 J/min. The flat lines occur at 0°C (lasting 6 minutes) and 100°C (lasting 24 minutes). The temperature rises between the flat lines from 0°C to 100°C in 10 minutes. (a) Calculate the specific latent heat of fusion and vaporisation. (b) Calculate the specific heat capacity of the liquid phase. (c) Explain why the second flat line is 4 times longer than the first, using particle theory.",
        evaluate:   "Evaluate the following explanation of sweating: 'Sweating cools the body because water is cold, and when cold water evaporates from the skin, it removes heat.' Identify all errors in this explanation. Provide a correct particle-level explanation of why evaporation cools, referencing kinetic energy distribution among particles and the concept of latent heat.",
        create:     "Construct a complete energy analysis for cooling 200 g of steam at 120°C to ice at −15°C. Calculate the energy released at every stage. (c_steam = 2,010 J/kg°C; L_v = 2,260,000 J/kg; c_water = 4,200 J/kg°C; L_f = 334,000 J/kg; c_ice = 2,090 J/kg°C.) Draw a sketch cooling curve labelling all flat lines and sloping regions. State which stage releases the most energy per kilogram and explain why."
    },

    gasLaws: {
        remember:   "State Boyle's law, Charles's law, and the pressure-temperature law, each in words and in symbols. Write the combined gas law equation. State the conversion between Celsius and Kelvin. State what is meant by an ideal gas.",
        understand: "Explain, using the particle collision model, why the pressure of a fixed mass of gas at constant volume increases when the temperature is raised. Your answer must address: (a) the effect of temperature on particle speed; (b) the effect on collision frequency with walls; (c) the effect on force per collision; and (d) the combined effect on pressure.",
        apply:      "A gas has a volume of 600 cm³ at 57°C and 80 kPa. It is heated to 117°C and compressed to 400 cm³. Calculate the new pressure using the combined gas law. Verify your answer by confirming the direction of each change is consistent with the relevant gas law.",
        analyze:    "A student measures the pressure of a gas in a sealed syringe at five different volumes, all at room temperature (20°C): (V = 100 cm³, p = 200 kPa); (V = 200 cm³, p = 100 kPa); (V = 400 cm³, p = 50 kPa); (V = 500 cm³, p = 42 kPa); (V = 50 cm³, p = 390 kPa). (a) Calculate pV for each data point and state whether the data supports Boyle's law. (b) Identify which data point is anomalous. (c) Suggest one reason why a real gas might deviate from Boyle's law at very high pressures.",
        evaluate:   "Evaluate the following student solution: 'A gas at 0°C and 100 kPa is heated to 100°C at constant volume. New pressure = 100 × (100/0) = undefined — the equation cannot be applied.' Identify the error that led to this impossible result, state the correct approach, and calculate the correct new pressure.",
        create:     "Formulate a step-by-step derivation showing that the combined gas law p₁V₁/T₁ = p₂V₂/T₂ can be derived from Boyle's law and Charles's law alone, using an intermediate state as a bridge. Then apply the combined gas law to the following engineering problem: an air compressor takes in air at 15°C and 100 kPa and compresses it to 1/8 of its original volume. The compression raises the temperature to 215°C. Calculate the pressure of the compressed air. Assess whether this pressure would be safe for a tyre rated to 400 kPa maximum."
    }
},


kinematicsThermodynamics: {
    reactionRates: {
        remember:   "State four factors that affect the rate of a chemical reaction. For each factor, state whether it affects collision frequency, collision energy, or both. Define: (a) activation energy; (b) rate constant; (c) order of reaction. Write the general form of the rate equation for a reaction between species A and B.",
        understand: "Explain why increasing the concentration of a reactant in solution increases the rate of reaction. Your answer must reference collision theory and the two criteria for a successful collision. Contrast this with the explanation for why increasing temperature also increases rate — identify which factor (frequency or energy) is the dominant effect in each case and why.",
        apply:      "Initial rate data for A + 2B → C + D: [Expt 1: A=0.10, B=0.20, rate=1.2×10⁻³]; [Expt 2: A=0.20, B=0.20, rate=2.4×10⁻³]; [Expt 3: A=0.20, B=0.60, rate=2.16×10⁻²]. Determine (a) the order with respect to A; (b) the order with respect to B; (c) the rate equation; (d) the value and units of k. Show all working for each step.",
        analyze:    "A concentration–time graph shows [A] falling as follows: at t=0, [A]=1.00; t=30s, [A]=0.50; t=60s, [A]=0.25; t=90s, [A]=0.125 mol dm⁻³. Analyse the data to: (a) determine the order with respect to A with full justification; (b) calculate the rate constant k with units; (c) predict [A] at t=150 s; (d) sketch the shape of the rate–concentration graph for this reaction and explain the shape.",
        evaluate:   "A student determines the rate equation as rate = k[A]²[B] from the balanced equation A + B → C (where A has coefficient 1 and B has coefficient 1 in the equation). The student reasons: 'The rate must depend on [A]² because the rate doubled when [A] was doubled.' Evaluate every aspect of this student's reasoning — identify what is correct, what is incorrect, and what additional experiments would be required to properly determine the rate equation.",
        create:     "Design a complete experimental procedure to determine the rate equation for the reaction: S₂O₃²⁻(aq) + 2HCl(aq) → S(s) + SO₂(g) + 2Cl⁻(aq) + H₂O(l). Include: (a) how you would measure rate; (b) at least four experimental conditions varying concentrations systematically; (c) how you would calculate orders from your data; (d) how you would determine k; (e) one hazard specific to this reaction and appropriate precaution; (f) one variable that must be controlled and why."
    },

    activationEnergy: {
        remember:   "Describe the key features of a Maxwell–Boltzmann energy distribution curve. State how each of the following changes the diagram: (a) increasing temperature; (b) adding a catalyst. State the effect of a catalyst on: Eₐ, ΔH, the equilibrium constant K, and the rate of reaction.",
        understand: "Explain, with reference to the Maxwell–Boltzmann distribution, why a 10°C rise in temperature has a proportionally larger effect on rate than a 10°C rise at a different, higher temperature would have. (Hint: consider the shape of the distribution in the high-energy tail.) Then explain why a catalyst is often more effective than a temperature rise for industrial processes, referencing both kinetics and the effect on equilibrium.",
        apply:      "For a reaction A → B: Eₐ(forward) = 95 kJ/mol and ΔH = +35 kJ/mol. (a) Calculate Eₐ(reverse). (b) Sketch and fully label the energy profile diagram, including: both energy levels, transition state, Eₐ(forward), Eₐ(reverse), and ΔH with correct sign. (c) Add a dashed line to the diagram showing a catalyst that reduces Eₐ(forward) by 30 kJ/mol. (d) Calculate the new Eₐ(reverse) in the presence of the catalyst.",
        analyze:    "A student measures the rate constant k for a reaction at three temperatures: k = 8.5×10⁻⁴ mol⁻¹ dm³ s⁻¹ at 300 K; k = 3.4×10⁻³ mol⁻¹ dm³ s⁻¹ at 320 K; k = 1.2×10⁻² mol⁻¹ dm³ s⁻¹ at 340 K. Analyse this data to: (a) confirm that the rate approximately doubles per 10°C for this reaction; (b) determine the order of reaction from the units of k; (c) explain using the Boltzmann factor why the rate ratio for 300→320 K approximately equals the ratio for 320→340 K for this reaction.",
        evaluate:   "Evaluate the following description of a Maxwell–Boltzmann diagram for the effect of increasing temperature: 'The curve becomes taller and shifts to the right. The peak moves to higher energy. The area under the curve increases because there are more energetic molecules at higher temperature. The activation energy line moves to the left.' Identify every error in this description (there are four). Provide a fully corrected description of what actually changes when temperature is increased.",
        create:     "Propose a detailed experimental method to determine the activation energy for the decomposition of hydrogen peroxide (H₂O₂ → H₂O + ½O₂) using the Arrhenius equation (ln k = ln A − Eₐ/RT). Your method must include: (a) how you will measure the rate constant k at each temperature; (b) the range of temperatures you will use and why; (c) what graph you will plot and how the slope gives Eₐ; (d) how you will ensure [H₂O₂] is constant across experiments; (e) the mathematical procedure to extract Eₐ from your graph with units."
    },

    equilibrium: {
        remember:   "Write the Kc expression for each equilibrium: (a) N₂(g) + 3H₂(g) ⇌ 2NH₃(g); (b) CH₃COOH(l) + C₂H₅OH(l) ⇌ CH₃COOC₂H₅(l) + H₂O(l); (c) Fe³⁺(aq) + SCN⁻(aq) ⇌ FeSCN²⁺(aq). State which changes affect the value of K and which affect only the position of equilibrium. State Le Chatelier's principle.",
        understand: "Explain the following observations using Le Chatelier's principle and equilibrium theory: (a) The yield of ammonia in the Haber process decreases when temperature is raised, even though the rate of reaching equilibrium increases. (b) Adding more N₂ to the equilibrium system N₂ + 3H₂ ⇌ 2NH₃ shifts the equilibrium to the right, yet the mole fraction of N₂ at the new equilibrium may be higher than before the addition. Explain the apparent paradox in (b).",
        apply:      "At 700 K, the equilibrium H₂(g) + I₂(g) ⇌ 2HI(g) has the following concentrations: [H₂] = 0.22, [I₂] = 0.22, [HI] = 1.58 mol dm⁻³. (a) Calculate Kc and give its units. (b) If the volume of the container is halved at constant temperature, predict and explain what happens to: (i) the position of equilibrium; (ii) the value of Kc. (c) If the temperature is now raised to 900 K, Kc decreases to 29. State whether the forward reaction is exothermic or endothermic, justifying your answer.",
        analyze:    "Kc for the reaction PCl₃(g) + Cl₂(g) ⇌ PCl₅(g) is 3.5 mol⁻¹ dm³ at 250°C and 0.042 mol⁻¹ dm³ at 350°C. Analyse this data to: (a) determine whether the forward reaction is exothermic or endothermic, with full reasoning; (b) predict and explain what happens to the yield of PCl₅ when: (i) pressure is increased; (ii) PCl₃ is added at constant volume; (iii) a catalyst is added; (iv) temperature is increased from 250°C to 350°C. For each, state the effect on K if any.",
        evaluate:   "A student writes: 'In the Haber process, an iron catalyst is used because it increases the yield of ammonia by shifting the equilibrium to the right, making the process more economically viable. Without the catalyst, even at 450°C and 200 atm, insufficient ammonia would form.' Evaluate every claim in this statement. Identify what is correct, what is incorrect, what the catalyst actually does, and what the actual factors that determine the equilibrium yield of ammonia are.",
        create:     "Construct a fully justified account of why the industrial conditions for the Haber process (450°C, 200 atm, iron catalyst, continuous removal of NH₃) are each necessary. For each condition: (a) state what Le Chatelier or kinetic principle applies; (b) explain what would happen if the condition were changed (too high T, too low T, lower pressure, no catalyst, product not removed); (c) identify any trade-offs or competing factors. Conclude by explaining why the choice of 450°C specifically represents a kinetic–thermodynamic compromise temperature."
    },

    enthalpyEntropy: {
        remember:   "State Hess's law. Define: (a) standard enthalpy of formation; (b) standard enthalpy of combustion; (c) bond enthalpy. Give the equation relating ΔG, ΔH, and ΔS. State the units of ΔH, ΔS, and ΔG. State the spontaneity criterion in terms of ΔG.",
        understand: "Explain why the reaction N₂(g) + 3H₂(g) → 2NH₃(g) has a negative ΔS°. Your answer must reference the number and type of moles of gas on each side. Then explain why ΔG = ΔH − TΔS implies that this reaction, although exothermic (ΔH = −92 kJ/mol), will become non-spontaneous at sufficiently high temperatures. Calculate the approximate crossover temperature (T = ΔH/ΔS) given ΔS° = −197 J K⁻¹ mol⁻¹.",
        apply:      "Using the following bond enthalpies [C–H: 413; C–C: 347; C=C: 614; H–H: 436; kJ/mol], calculate ΔH for the hydrogenation of ethene: CH₂=CH₂(g) + H₂(g) → CH₃CH₃(g). Show all working, identifying bonds broken and formed. State whether this is an overestimate or underestimate of the true ΔH and explain why. Then use the following ΔH°f data [C₂H₄: +52; C₂H₆: −85; H₂: 0 kJ/mol] to calculate the exact ΔH via Hess's law and compare the two values.",
        analyze:    "Four reactions have the following ΔH° and ΔS° values: (A) ΔH = −200 kJ/mol, ΔS = +150 J K⁻¹ mol⁻¹; (B) ΔH = +80 kJ/mol, ΔS = +250 J K⁻¹ mol⁻¹; (C) ΔH = −60 kJ/mol, ΔS = −180 J K⁻¹ mol⁻¹; (D) ΔH = +120 kJ/mol, ΔS = −100 J K⁻¹ mol⁻¹. Analyse each reaction to: (a) determine spontaneity at 298 K with calculated ΔG values; (b) classify each as: always spontaneous, never spontaneous, spontaneous only at low T, or spontaneous only at high T; (c) calculate crossover temperatures for B and C.",
        evaluate:   "A student calculates ΔG for a reaction at 500 K as: ΔG = −240 − (500 × 120) = −60,240 kJ/mol, where ΔH = −240 kJ/mol and ΔS = 120 J K⁻¹ mol⁻¹. Evaluate this calculation completely — identify all errors (there are two), state the correct procedure, and calculate the correct ΔG value. Then state whether the reaction is spontaneous at 500 K and explain the physical meaning of the sign of ΔG.",
        create:     "Formulate a complete argument from first principles explaining why diamond is thermodynamically unstable relative to graphite at 298 K (ΔG° = −2.9 kJ/mol for C(diamond) → C(graphite)) yet diamond persists indefinitely under normal conditions. Your argument must: (a) use ΔG° = −RT ln K to calculate K for the conversion; (b) interpret what this K value means physically; (c) explain why thermodynamic instability does not lead to observable conversion, using activation energy and Maxwell–Boltzmann reasoning; (d) predict under what conditions (temperature, pressure) diamond could be converted to graphite at a measurable rate; (e) connect this to the industrial synthesis of diamond from graphite at very high temperature and pressure."
    }
},

redoxChemistry: {
    redoxDefinitions: {
        remember:   "Define oxidation and reduction in terms of: (a) electron transfer; (b) oxidation state change. State what is meant by an oxidising agent and a reducing agent, and explain the relationship between each agent and the process it undergoes.",
        understand: "Explain why it is impossible to have oxidation without reduction occurring simultaneously. Use a specific example — the reaction of zinc with copper(II) sulfate — to illustrate your answer, identifying the oxidising agent, reducing agent, species oxidised, and species reduced.",
        apply:      "In the following reaction: 2H₂O₂ → 2H₂O + O₂. (a) Assign oxidation states to oxygen in each species. (b) Identify which oxygen atoms are oxidised and which are reduced. (c) Name the type of reaction this represents. (d) Write the two half-equations and combine them to verify they produce the overall equation.",
        analyze:    "The following reactions were observed: (i) Cl₂ decolourises an orange solution of Br₂/KBr when the two are mixed. (ii) Br₂ has no effect on a KCl solution. Given E°(Cl₂/Cl⁻) = +1.36 V and E°(Br₂/Br⁻) = +1.07 V, analyse both observations using E°cell calculations. State what these results reveal about the relative strengths of Cl₂ and Br₂ as oxidising agents.",
        evaluate:   "Evaluate the following student statement: 'In the reaction Zn + CuSO₄ → ZnSO₄ + Cu, zinc is the oxidising agent because it causes the copper to be displaced from solution.' Identify all errors in this reasoning, state the correct oxidising and reducing agents, and provide the electron transfer evidence to support your answer.",
        create:     "Design a series of test-tube experiments to rank Cl₂, Br₂, and I₂ in order of oxidising power, using solutions of their sodium halide salts (NaCl, NaBr, NaI). State: (a) the reagents for each test; (b) the expected observation for each combination; (c) the half-equations for each reaction that occurs; (d) how you would use E° values to confirm your experimental ranking."
    },

    oxidationStates: {
        remember:   "State the oxidation state of the transition metal in each of the following: (a) FeCl₃; (b) K₂Cr₂O₇; (c) KMnO₄; (d) MnO₂; (e) V₂O₅. State the rule used to determine the oxidation state of oxygen in H₂O₂ and explain why this differs from the rule applied to H₂O.",
        understand: "Explain why Fe₃O₄ (iron(II,III) oxide) gives a non-integer average oxidation state for iron (+8/3). Show how you would assign oxidation states to confirm that the compound contains both Fe²⁺ and Fe³⁺ ions. Explain why this is chemically meaningful even though the calculated average is not a whole number.",
        apply:      "Assign the oxidation state of the underlined element in each species: (a) S in Na₂S₂O₃; (b) Cr in CrO₄²⁻; (c) N in N₂H₄; (d) Cl in NaClO₃; (e) Mn in Mn₂O₇. For each, show the algebraic working. Identify which species contains the element in its highest common oxidation state.",
        analyze:    "The following data are given for reactions of iodine: IO₃⁻ + 5I⁻ + 6H⁺ → 3I₂ + 3H₂O. Assign oxidation states to all iodine-containing species. Identify what is oxidised and what is reduced. Calculate the change in oxidation state for each species and verify that the electron transfer is balanced in the equation as written.",
        evaluate:   "Evaluate the following student answer to 'Determine the oxidation state of S in S₄O₆²⁻': 'S₄O₆²⁻: 4S + 6(−2) = −2, so 4S = +10, S = +2.5.' Assess whether the arithmetic is correct, whether the result is chemically meaningful, and whether there is a deeper structural issue with this calculation. (Note: S₄O₆²⁻ contains two types of sulfur atoms at different oxidation states — address this in your evaluation.)",
        create:     "Construct a complete oxidation state map for the element chlorine: list all oxidation states from −1 to +7 with one example compound or ion for each. For each pair of adjacent oxidation states, state whether the conversion from lower to higher is oxidation or reduction, and give one reagent that could achieve this conversion. Use your map to identify which chlorine species could act as both an oxidising and a reducing agent."
    },

    redoxEquations: {
        remember:   "Write the balanced half-equations for: (a) the reduction of MnO₄⁻ to Mn²⁺ in acid; (b) the reduction of Cr₂O₇²⁻ to Cr³⁺ in acid; (c) the oxidation of Fe²⁺ to Fe³⁺; (d) the oxidation of I⁻ to I₂; (e) the reduction of I₂ to I⁻. State the colour change observed at the endpoint of a KMnO₄/Fe²⁺ titration and explain why H₂SO₄ and not HCl is used to acidify the solution.",
        understand: "Explain the procedure for balancing a half-equation for a reaction occurring in acidic solution, using the reduction of Cr₂O₇²⁻ to Cr³⁺ as your worked example. At each step, explain WHY that step is performed (i.e. which imbalance you are correcting) before writing the equation for that step.",
        apply:      "Combine the following half-equations to give a balanced overall ionic equation for the reaction of MnO₄⁻ with C₂O₄²⁻ (oxalate) in acidic solution: Reduction: MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O. Oxidation: C₂O₄²⁻ → 2CO₂ + 2e⁻. Show all scaling steps, write the combined equation, and verify by atom and charge count.",
        analyze:    "A 0.500 g sample of iron ore was dissolved in dilute H₂SO₄ and all iron converted to Fe²⁺. The solution required 24.30 cm³ of 0.0200 mol dm⁻³ KMnO₄ for complete oxidation. The relevant equation is: MnO₄⁻ + 8H⁺ + 5Fe²⁺ → Mn²⁺ + 4H₂O + 5Fe³⁺. Analyse the data to find: (a) moles of KMnO₄; (b) moles of Fe²⁺; (c) mass of Fe in the sample; (d) percentage by mass of Fe in the ore sample. (M_r Fe = 55.8)",
        evaluate:   "Evaluate the following student answer for balancing the half-equation for reduction of NO₃⁻ to NO in acid: 'NO₃⁻ + 3e⁻ → NO + 2O'. Identify every error in this half-equation — address atom balance, the form of oxygen produced, and charge balance — and write the correct balanced half-equation.",
        create:     "Design a complete quantitative experimental procedure to determine the percentage purity of a sample of iron(II) ammonium sulfate (FeSO₄·(NH₄)₂SO₄·6H₂O, M_r = 392). The procedure must use KMnO₄ titration. Include: (a) how to prepare the sample solution; (b) choice of acid for acidification and justification; (c) the balanced equation for the titration reaction; (d) a complete example calculation showing how you would convert the titration volume to percentage purity; (e) two sources of error and how to minimise each."
    },

    electrochemistry: {
        remember:   "State the standard conditions required to measure a standard electrode potential. Write the half-equation for the standard hydrogen electrode and state its E° value. Define E°cell and state the formula used to calculate it from two half-cell E° values. State whether a positive or negative E°cell indicates a feasible reaction.",
        understand: "Explain, using the electrochemical series, why Cl₂ can oxidise Br⁻ to Br₂ but cannot oxidise F⁻ to F₂. Your answer must reference the E° values of the relevant half-reactions and explain the directionality of electron flow.",
        apply:      "Given: MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O, E° = +1.51 V; Fe³⁺ + e⁻ → Fe²⁺, E° = +0.77 V. (a) State which species acts as the cathode and which as the anode in an electrochemical cell using these two half-reactions. (b) Calculate E°cell. (c) Write the overall balanced ionic equation. (d) Write the cell notation for this cell using conventional format.",
        analyze:    "The following E° data are given: Cu²⁺/Cu = +0.34 V; Fe²⁺/Fe = −0.44 V; Ag⁺/Ag = +0.80 V; H⁺/H₂ = 0.00 V. Analyse which metals from the list will dissolve in dilute H₂SO₄ (producing H₂). For those that do not react with dilute H₂SO₄, determine whether they would dissolve in a solution of AgNO₃. Calculate E°cell for each reaction you predict to be feasible and write the balanced ionic equation.",
        evaluate:   "A student states: 'The reaction between Zn and H₂SO₄ has E°cell = +0.76 V. Therefore, zinc reacts vigorously and completely with sulfuric acid under all conditions.' Evaluate this statement fully — identify what E°cell does and does not predict, give one condition under which the reaction rate would be affected despite E°cell remaining unchanged, and explain the thermodynamic-kinetic distinction in the context of this example.",
        create:     "Formulate a complete electrochemical argument to explain why magnesium can be used to protect the iron hull of a ship from corrosion (cathodic protection), while copper cannot. Your argument must: (a) give the E° values of all relevant half-cells (Mg²⁺/Mg, Fe²⁺/Fe, Cu²⁺/Cu); (b) calculate E°cell for each metal paired with Fe; (c) state which reaction is spontaneous in each case; (d) explain the mechanism by which the more reactive metal protects iron; (e) explain what happens when the protective metal is consumed."
    }
},



chemicalBonding: {
    ionicBonding: {
        remember:   "State two properties of ionic compounds. Define lattice enthalpy. Draw a dot-cross diagram for the formation of magnesium chloride (MgCl₂), showing all electrons in the outer shells and the charge on each ion.",
        understand: "Explain why magnesium oxide (MgO) has a much higher melting point than sodium chloride (NaCl), despite both being ionic compounds with the same crystal structure type. Your answer must reference ionic charge, ionic radius, and the electrostatic model of lattice stability.",
        apply:      "Predict the formula of the ionic compound formed between aluminium (Al) and oxide (O²⁻) ions. Draw a dot-cross diagram showing the electron transfer. Explain why the formula is Al₂O₃ and not AlO or AlO₃.",
        analyze:    "Compound X has a melting point of 2852°C, conducts electricity when molten but not solid, and is insoluble in hexane but dissolves slowly in water. Compound Y has a melting point of 800°C, conducts when molten, and dissolves readily in water. Analyse the properties of both compounds to deduce their bonding type and to identify which has stronger ionic interactions. Justify using ionic charge and radius arguments.",
        evaluate:   "A student states: 'Ionic compounds always conduct electricity because ions carry charge, just like electrons in metals.' Evaluate this statement — identify what is correct, identify the error (specifying the condition that must be met), and explain the correct conditions for ionic conductivity with a mechanistic explanation.",
        create:     "Construct a Born-Haber cycle for the formation of lithium fluoride (LiF) from its elements. Label each enthalpy term (atomisation of Li, atomisation of F, ionisation energy of Li, electron affinity of F, lattice enthalpy, and enthalpy of formation). Use the cycle to explain why LiF has a negative enthalpy of formation despite the positive ionisation energy of Li being a significant energy cost."
    },

    covalentBonding: {
        remember:   "State the bond angles in: (a) CH₄; (b) NH₃; (c) H₂O. For each, state the number of bonding pairs and lone pairs on the central atom. Define the term 'dative (coordinate) bond' and give one example.",
        understand: "Explain why NH₃ has a bond angle of 107° rather than the tetrahedral angle of 109.5°. Your answer must reference the number and type of electron pairs around N and the relative magnitude of their repulsions. Extend your explanation to predict the bond angle in H₂O (104.5°) and explain the further reduction.",
        apply:      "For each of the following molecules: (i) SO₂; (ii) PCl₃; (iii) SF₄; (iv) XeF₂ — use VSEPR theory to predict the number of bonding pairs and lone pairs on the central atom, the molecular shape, and the approximate bond angles. For SO₂, also draw a dot-cross diagram showing the dative bond.",
        analyze:    "The bond angles in NF₃ (102.5°) are smaller than those in NH₃ (107°). Both molecules are trigonal pyramidal with one lone pair on N. Analyse this difference — identify the structural/electronic reason why F substituents produce a smaller N–X–N angle than H substituents. (Hint: consider the electronegativity of F and H and the location of the bonding electron pairs.)",
        evaluate:   "A student draws the following Lewis structure for CO₂: one C=O double bond on the left and one C–O single bond on the right, with the remaining electrons as lone pairs. Evaluate this structure — identify whether the octet rule is satisfied for all atoms, state what is incorrect about the structure, and draw the correct Lewis structure for CO₂ with full justification.",
        create:     "Design a complete argument from first principles — using electronegativity values, VSEPR, and dipole vector analysis — to determine whether PCl₅ is a polar or non-polar molecule. Your argument must: (1) establish the shape using VSEPR; (2) determine the polarity of each P–Cl bond; (3) analyse whether the bond dipoles cancel; (4) state the conclusion with justification. Explain why the question is less straightforward than for simpler molecules."
    },

    metallicBonding: {
        remember:   "Describe the metallic bonding model in terms of the particles present and the nature of the electrostatic attraction. List three properties of metals that are explained by the metallic bonding model. State why metals are good electrical conductors.",
        understand: "Explain why aluminium (Al) has a higher melting point than sodium (Na), using the metallic bonding model. Your answer must compare: (1) the number of delocalised electrons per atom; (2) the charge and radius of the metal cation; (3) the resulting strength of electrostatic attraction.",
        apply:      "Place the following metals in order of increasing melting point and justify your order using the metallic bonding model: Na, Mg, Al, K. For each metal, state the number of electrons delocalised per atom and the charge of the cation formed.",
        analyze:    "Iron (Fe, melting point 1538°C) is much harder than sodium (Na, melting point 98°C). Analyse this difference using the metallic bonding model. Then analyse why sodium is malleable (can be cut with a knife) while iron requires significant force to deform — both are metals, so why does malleability vary so greatly?",
        evaluate:   "A student explains metallic conductivity as follows: 'Metals conduct electricity because they have weak bonds that break easily, allowing electrons to escape and flow.' Evaluate every element of this explanation — identify what is correct, identify all errors, and write a complete, accurate account of the mechanism of metallic electrical conduction.",
        create:     "Propose a structural explanation, using the metallic bonding model, for why (a) adding carbon to iron increases hardness (producing steel); (b) an alloy of copper and zinc (brass) is harder than either pure metal; (c) pure gold is too soft for most engineering applications and must be alloyed. Identify the common structural principle in all three cases and connect it to the metallic bonding model."
    },

    intermolecularForces: {
        remember:   "Name the three types of intermolecular force. State two requirements for hydrogen bond formation. State which type of intermolecular force acts between all molecules regardless of polarity. Rank the three intermolecular force types in order of increasing strength.",
        understand: "Explain why the boiling point of H₂O (100°C) is anomalously high compared to H₂S (−60°C), H₂Se (−41°C), and H₂Te (−2°C). Your answer must identify the specific intermolecular force responsible, explain why H₂O can form it while the other Group 16 hydrides cannot, and explain why the trend from H₂S to H₂Te (increasing boiling point) follows the expected pattern.",
        apply:      "For each of the following pairs, predict which substance has the higher boiling point and justify your answer by identifying the intermolecular forces present in each: (a) CH₄ vs NH₃; (b) HCl vs HBr; (c) ethanol (C₂H₅OH) vs dimethyl ether (CH₃OCH₃) — both have Mr = 46.",
        analyze:    "The boiling points of the noble gases are: He −269°C, Ne −246°C, Ar −186°C, Kr −153°C, Xe −108°C. Analyse this trend — identify the single intermolecular force responsible, explain why it increases down the group, and calculate the average increase in boiling point per period. Predict the approximate boiling point of radon (Rn) using the trend, and state one source of uncertainty in this prediction.",
        evaluate:   "Evaluate the following claim: 'Ethanol (C₂H₅OH) has a higher boiling point than propane (C₃H₈) because ethanol has a larger molar mass (46 vs 44 g/mol) and therefore stronger London dispersion forces.' Identify every error in this reasoning, state the correct forces acting in each substance, and provide the correct explanation for the boiling point difference.",
        create:     "Formulate a set of molecular design criteria that a pharmaceutical chemist would apply to maximise a drug's water solubility for intravenous injection. Your criteria must: (1) identify which intermolecular forces must be maximised between drug and water; (2) specify which functional groups or structural features achieve this; (3) explain the trade-off between water solubility and membrane permeability using intermolecular force arguments; and (4) give one example of a structural modification that increases water solubility and explain its mechanism."
    }
},

atomicStructure: {
    subatomicParticles: {
        remember:   "State the relative mass, relative charge, and location of: (a) a proton; (b) a neutron; (c) an electron. For the nuclide ⁵⁶₂₆Fe, state the number of each subatomic particle in a neutral iron atom and in an Fe³⁺ ion.",
        understand: "Explain why isotopes of the same element have identical chemical properties but different physical properties (such as mass and nuclear stability). Your answer must reference electronic configuration and the role of proton number in determining chemical identity.",
        apply:      "The nuclide ⁶³₂₉Cu forms a Cu²⁺ ion. (a) Calculate the number of protons, neutrons, and electrons in the ion. (b) A different copper isotope, ⁶⁵Cu, also forms a Cu²⁺ ion. State how the subatomic particle numbers in ⁶⁵Cu²⁺ differ from those in ⁶³Cu²⁺. (c) Predict whether ⁶³Cu and ⁶⁵Cu would have the same first ionisation energy. Justify your answer.",
        analyze:    "Two nuclides are given: ¹⁴₆C and ¹⁴₇N. (a) Calculate the subatomic particle composition of each. (b) Analyse whether these nuclides are isotopes of one another, isobars (same mass number), or neither. Justify your answer using your subatomic particle data. (c) Predict whether ¹⁴C and ¹⁴N would have the same chemical properties. Justify your reasoning.",
        evaluate:   "A student states: 'The atomic number of an element can vary because different samples of the same element found in different locations may contain different numbers of protons.' Evaluate this claim comprehensively — identify all errors, explain what actually varies between samples of the same element found in different locations, and provide the correct definition of atomic number.",
        create:     "Construct a logical argument — from first principles — that explains why the periodic table is organised by atomic number (proton number) rather than by atomic mass, using isotopes as your evidence. Your argument must include: (a) a specific example of an element where atomic mass ordering would place it incorrectly relative to proton number ordering; (b) an explanation of why proton number is the chemically meaningful quantity; (c) a historical note on how Moseley's X-ray experiments resolved the ordering dispute."
    },

    electronicConfiguration: {
        remember:   "Write the full electronic configuration for: (a) silicon (Z=14); (b) potassium (Z=19); (c) iron (Z=26). State Hund's rule. Draw the box notation for the outer subshell of each element.",
        understand: "Explain why the 4s subshell is filled before the 3d subshell in neutral atoms (Aufbau order), but 4s electrons are removed before 3d electrons when transition metal atoms form positive ions. Your answer must reference how the relative energies of 4s and 3d change between the neutral atom and the ion.",
        apply:      "Write the full electronic configuration and outer subshell box notation for: (a) titanium (Z=22); (b) Ti²⁺; (c) Ti⁴⁺; (d) bromide ion Br⁻ (Z=35). For each, state the number of unpaired electrons and identify any that are diamagnetic (all electrons paired).",
        analyze:    "An element has the electronic configuration [Ar] 3d¹⁰ 4s¹. (a) Identify the element. (b) Analyse whether this configuration is predicted by the Aufbau principle or represents an exception, and explain why the exception arises. (c) Write the configuration of the 1+ and 2+ ions of this element. (d) State which ion would be colourless in aqueous solution and explain why, with reference to the d subshell.",
        evaluate:   "A student writes the following electronic configurations: (i) Fe²⁺: [Ar] 3d⁴ 4s²; (ii) Cr: [Ar] 3d⁴ 4s²; (iii) Cu: [Ar] 3d¹⁰ 4s¹. Evaluate each configuration — state whether it is correct or incorrect, identify any error, state which rule has been violated, and provide the correct configuration.",
        create:     "Derive a decision procedure (a step-by-step algorithm) for writing the electronic configuration of any transition metal ion with a charge of 2+ or 3+. Your algorithm must correctly handle: (a) the Aufbau filling order for the neutral atom; (b) the 4s-removed-first rule for ionisation; (c) the Cr and Cu exceptions. Test your algorithm on Mn²⁺ (Z=25), Ni³⁺ (Z=28), and Zn²⁺ (Z=30)."
    },

    ionisationEnergy: {
        remember:   "Define first ionisation energy. Write the equation representing the first ionisation energy of potassium, including state symbols. State the units of ionisation energy. State the general trend in first ionisation energy: (a) across Period 3 from left to right; (b) down Group 2.",
        understand: "Explain why the first ionisation energy of aluminium (577 kJ/mol) is lower than that of magnesium (738 kJ/mol), despite aluminium having a greater nuclear charge. Your answer must: (a) state the outer electron subshell for each element; (b) explain the relative energies of the subshells involved; (c) explain the role of the 3s electrons in shielding the 3p electron in aluminium.",
        apply:      "The successive ionisation energies (kJ/mol) of an unknown element Q are: 590, 1145, 4912, 6474, 8144, 10496, 12320, 15000. (a) Identify the large jump and state between which ionisation energies it occurs. (b) Deduce the group of element Q and justify your reasoning. (c) Given that Q is in Period 4, suggest its identity and write its electronic configuration.",
        analyze:    "The first ionisation energies across Period 3 (kJ/mol) are: Na 496, Mg 738, Al 577, Si 786, P 1012, S 1000, Cl 1251, Ar 1521. (a) Identify all anomalies (places where IE does not follow the general increasing trend). (b) For each anomaly, provide a detailed mechanistic explanation using electronic configuration and orbital diagrams. (c) Calculate the average rate of IE increase per element across Period 3 (excluding anomalies) and explain why the rate is not uniform.",
        evaluate:   "Evaluate the following student explanation for why sulfur has a lower first IE than phosphorus: 'Sulfur has more electrons than phosphorus, so there is more electron-electron repulsion overall, making it easier to remove an electron from sulfur.' Identify what is correct in this reasoning, what is imprecise, and what is missing. Provide a rigorous corrected explanation that specifies the orbital from which the electron is removed in each element.",
        create:     "Design a procedure by which a chemist could use successive ionisation energy data alone — without reference to any other chemical property — to identify an unknown pure metallic element from Period 3 or Period 4. Your procedure must: (a) specify what data to measure; (b) explain how to determine the group from the IE pattern; (c) explain how to distinguish Period 3 from Period 4 elements using the magnitude of the IE values; (d) describe how to confirm the identification. Apply your procedure to the data: 1st IE = 738, 2nd IE = 1451, 3rd IE = 7733 kJ/mol."
    },

    isotopesAndMassSpectrometry: {
        remember:   "Define: (a) isotope; (b) relative atomic mass; (c) relative isotopic mass. List the four stages of a mass spectrometer in order. Write the equation for the ionisation step in electron ionisation mass spectrometry.",
        understand: "Explain how a mass spectrometer separates ions of different mass-to-charge ratio (m/z). Your answer must describe what happens in the acceleration and deflection stages and explain at which point in the instrument the separation of ²³⁵U from ²³⁸U actually takes place, with reference to the physics of each stage.",
        apply:      "A mass spectrum of boron shows two peaks: m/z = 10 (relative abundance 199) and m/z = 11 (relative abundance 801). (a) Identify the two isotopes represented. (b) Calculate the relative atomic mass of boron to 2 decimal places, showing full working. (c) Calculate the percentage abundance of each isotope.",
        analyze:    "A mass spectrum of an element shows three peaks: m/z = 28 (relative abundance 9222), m/z = 29 (relative abundance 470), m/z = 30 (relative abundance 308). (a) Calculate the relative atomic mass to 2 d.p. (b) Identify the element. (c) Analyse why the peak at m/z = 28 is so much more intense than the others and explain what this tells you about the natural abundance of the corresponding isotope. (d) State how many neutrons are present in the atom giving the peak at m/z = 30.",
        evaluate:   "A student calculates the relative atomic mass of magnesium from a mass spectrum as follows: 'The peaks are at m/z = 24, 25, and 26. Average = (24 + 25 + 26) ÷ 3 = 25.0.' Evaluate this method fully — identify the conceptual error in the student's approach, explain what the correct method is, and show with the actual magnesium abundance data (²⁴Mg 79.0%, ²⁵Mg 10.0%, ²⁶Mg 11.0%) that the student's answer is incorrect.",
        create:     "Propose a method using mass spectrometry to determine the percentage of ¹³C in a sample of an organic compound. Include: (a) how the sample would be prepared and introduced into the instrument; (b) what peaks you would expect to observe in the mass spectrum and at what m/z values for a simple molecule like CO₂; (c) how you would calculate the ¹³C:¹²C ratio from the peak heights; (d) what additional correction factor might be needed and why. Explain how this method is used in anti-doping analysis."
    }
},


organicChemistry: {
    alcoholsAndPhenols: {
        remember:   "State the reagents and conditions for the following conversions: (a) primary alcohol → aldehyde; (b) primary alcohol → carboxylic acid; (c) secondary alcohol → ketone; (d) tertiary alcohol → no reaction. In each case, state the observation with acidified dichromate(VI) solution.",
        understand: "Explain why phenol (pKa 10) is a stronger acid than ethanol (pKa 16) but a weaker acid than ethanoic acid (pKa 4.8). Your answer must reference the stability of the conjugate base in each case, using delocalisation and inductive effects.",
        apply:      "Draw the full curly arrow mechanism for the formation of propyl propanoate from propanoic acid and propan-1-ol. State the catalyst and conditions, explain why the reaction is reversible, and calculate how the yield can be improved using Le Chatelier's principle.",
        analyze:    "Three colourless liquids A, B, and C each have molecular formula C₃H₈O. Compound A: reacts with acidified K₂Cr₂O₇ (orange → green) under distillation; the product gives a silver mirror with Tollens'. Compound B: reacts with acidified K₂Cr₂O₇ (orange → green) under reflux; the product does not give a silver mirror. Compound C: no reaction with acidified K₂Cr₂O₇ (orange remains). Identify A, B, and C. Draw the structural formula of each and classify as primary, secondary, or tertiary.",
        evaluate:   "Evaluate the following claim: 'Ethanol and phenol both react with sodium metal to produce hydrogen gas, so they must have approximately the same acid strength.' Identify the error in equating both reactions with equivalent acid strength, provide the quantitative evidence (pKa values), and explain the structural reason for the difference using the concept of conjugate base stability.",
        create:     "Design a synthesis of ethyl propanoate (CH₃CH₂COOC₂H₅) from ethanol and propan-1-ol only (no purchased acid or ester). Your route must include: oxidation of propan-1-ol to propanoic acid, esterification with ethanol, and the conditions and equations for each step. Identify a problem with the direct esterification route in terms of yield, and propose one method to maximise the yield of ethyl propanoate."
    },

    halogenoalkanes: {
        remember:   "State: (a) the observation and conclusion when AgNO₃(ethanol) is added to separate solutions of chloroethane, bromoethane, and iodoethane; (b) the reagents and conditions for converting a halogenoalkane to an alkene; (c) the type of bond fission that occurs when a C–X bond is broken heterolytically in nucleophilic substitution.",
        understand: "Explain why the rate of hydrolysis of halogenoalkanes follows the order RI > RBr > RCl >> RF, even though the order of C–X bond polarity is C–F > C–Cl > C–Br > C–I. Your answer must distinguish between bond polarity and bond enthalpy and explain which property controls the rate.",
        apply:      "Draw the complete SN2 mechanism for the reaction of 1-bromopropane with KCN in ethanol. Name the product, state the type of mechanism, write the rate equation, and explain what happens to the carbon chain length. Then draw the complete SN1 mechanism for the hydrolysis of 2-bromo-2-methylpropane with water, including all intermediates and the stereochemical outcome.",
        analyze:    "Compound X has formula C₄H₉Br. It reacts with AgNO₃(ethanol) to give a cream precipitate. With hot ethanolic KOH it gives a mixture of two alkene products. With aqueous NaOH at room temperature it gives a single alcohol product. Deduce the structure of X, identify the two possible elimination products (naming both using IUPAC), explain why two alkenes form, and state which is the major product according to Zaitsev's rule.",
        evaluate:   "A student proposes that 2-chloro-2-methylpropane reacts with NaOH by an SN2 mechanism because 'OH⁻ is a strong nucleophile that can displace any leaving group by back-side attack.' Evaluate this proposal — identify every error; state the correct mechanism for this substrate with justification from substrate class; write the correct mechanism including all steps and intermediates; and explain what 'back-side attack' requires structurally and why it cannot occur here.",
        create:     "Propose a synthetic route to 2-aminopropane starting from propene, in no more than three steps. For each step: write the balanced equation; state the reagents, conditions, and mechanism type; identify major and minor products where applicable. Justify the regiochemistry of the first step using carbocation stability, and explain why excess ammonia is required in the final step."
    },

    carbonylCompounds: {
        remember:   "For each of the following tests, state the reagent(s), the observation for a positive result, and one compound that gives a positive result: (a) Tollens' test; (b) Fehling's solution; (c) iodoform test; (d) 2,4-dinitrophenylhydrazine (Brady's reagent).",
        understand: "Explain why the carbonyl carbon in aldehydes and ketones is susceptible to nucleophilic attack. Your answer must reference the electronegativity of oxygen, the polarity of the C=O bond, and why the nucleophile attacks carbon rather than oxygen.",
        apply:      "Draw the full two-step curly arrow mechanism for the nucleophilic addition of HCN to butanone (CH₃COC₂H₅). Name the product using IUPAC nomenclature, identify the chiral centre in the product, and state whether the reaction produces a single enantiomer or a racemic mixture. Justify your answer.",
        analyze:    "An unknown compound with molecular formula C₄H₈O: gives an orange precipitate with 2,4-DNP; gives no silver mirror with Tollens' reagent; gives no yellow precipitate with I₂/NaOH. A second compound with the same formula gives an orange precipitate with 2,4-DNP; gives a silver mirror with Tollens'; gives no precipitate with I₂/NaOH. Identify both compounds, draw their structural formulae, and explain why the two compounds respond differently to Tollens' reagent by reference to their structural difference at the carbonyl carbon.",
        evaluate:   "Evaluate the following student claim: 'The iodoform test can be used to distinguish ethanal from propanone, because ethanal is an aldehyde and propanone is a ketone — only ketones give a positive iodoform test.' Identify all errors in this statement; state which compounds give a positive iodoform test and why (using structural criteria); and provide a corrected explanation of what the iodoform test actually detects.",
        create:     "Construct a complete, unambiguous testing scheme to identify five unknown compounds: propanal, propanone, propan-1-ol, propan-2-ol, and propanoic acid. Use no more than four chemical tests. For each test: state the reagent(s); predict the observation for each compound; and explain the chemistry. Show how the sequence of tests eliminates possibilities step by step until all five compounds are uniquely identified."
    },

    carboxylicAcidsAndDerivatives: {
        remember:   "Write equations for the following reactions of ethanoic acid: (a) with NaOH; (b) with Na₂CO₃; (c) with ethanol (state catalyst and conditions); (d) with Na metal. State the observation in each case and name all products.",
        understand: "Explain why ethanoyl chloride (CH₃COCl) reacts vigorously with water at room temperature, while ethyl ethanoate (CH₃COOC₂H₅) requires reflux with dilute acid or base to hydrolyse under comparable conditions. Your answer must reference the leaving group ability and the electrophilicity of the carbonyl carbon in each compound.",
        apply:      "Draw the full mechanism for the reaction of propanoyl chloride (C₂H₅COCl) with ammonia (NH₃) to form propanamide. Include: the tetrahedral intermediate; all curly arrows; the role of the second NH₃ molecule in removing HCl. Name the mechanism type and explain why the reaction is faster than the equivalent reaction with propanoic acid.",
        analyze:    "Compound A (C₄H₈O₂) has a sweet fruity smell, does not react with Na₂CO₃, and hydrolyses with dilute HCl to give a carboxylic acid (which turns litmus red) and an alcohol (which gives a positive iodoform test). Compound B (C₄H₈O₂) effervesces with Na₂CO₃ and does not hydrolyse easily. Identify the functional group and structural formula of A and B. Name both compounds using IUPAC rules.",
        evaluate:   "Evaluate the following proposed synthesis of N-methylethanamide (CH₃CONHCH₃): 'React ethanoic acid with methylamine directly at room temperature.' Identify whether this reaction occurs as described and explain why the yield would be very low under these conditions. Propose an improved route using an acyl chloride and justify why this gives a higher yield.",
        create:     "Formulate a synthetic route from ethanol to glycine (H₂N–CH₂–COOH) in the minimum number of steps. Each step must include: the balanced equation; the reagents and conditions; the mechanism type; and the name of the intermediate formed. Justify the order of steps, explaining why the amine group cannot be installed first if the carboxylic acid step uses harsh oxidising conditions."
    }
},

acidsAndBases: {
    acidBaseDefinitions: {
        remember:   "State the Brønsted–Lowry definitions of (a) an acid and (b) a base. Write the dissociation equation for ethanoic acid in water and identify the two conjugate acid–base pairs. Define the term 'amphoteric' and give one example of an amphoteric species.",
        understand: "Explain why the Brønsted–Lowry definition of a base is more general than the Arrhenius definition, using the reaction of ammonia with water (NH₃ + H₂O ⇌ NH₄⁺ + OH⁻) as your example. In your answer, explain what the Arrhenius model predicts for this reaction and why it is insufficient.",
        apply:      "For each of the following reactions, identify the Brønsted–Lowry acid, base, conjugate acid, and conjugate base: (a) HNO₃ + H₂O → H₃O⁺ + NO₃⁻; (b) NH₃ + HCl → NH₄⁺ + Cl⁻; (c) HCO₃⁻ + OH⁻ → CO₃²⁻ + H₂O. For reaction (c), identify the amphoteric species and write the equation showing it acting as an acid.",
        analyze:    "A 0.100 mol dm⁻³ solution of acid HA has pH 2.87 and a 0.100 mol dm⁻³ solution of acid HB has pH 1.00. Analyse this data: determine whether each acid is strong or weak; calculate Ka for any weak acid identified; rank the two acids by strength; and explain why two acids with the same concentration can have such different pH values.",
        evaluate:   "Evaluate the following student answer to 'Explain why water is described as amphoteric': 'Water is amphoteric because it is neutral, with pH 7, which means it is neither acidic nor alkaline.' Identify all errors in this answer — address what amphoteric actually means, write two equations showing water acting in each role, and explain why neutrality (pH 7) is an unrelated concept to amphoteric character.",
        create:     "Design a series of experiments to determine whether an unknown colourless liquid is a strong acid, weak acid, strong base, or weak base. Your procedure must include: (a) at least three experimental tests, each with the expected observation for each possible identity; (b) a decision tree showing how the results of each test narrow the possibilities; (c) at least one quantitative measurement and how it would be interpreted."
    },

    pHAndStrength: {
        remember:   "State the formula for pH and write the expression for Kw. Give the value of Kw at 25°C. Write the approximation formula for calculating [H⁺] of a weak acid. State the condition that must be satisfied for this approximation to be valid.",
        understand: "Explain, using the Ka equilibrium expression, why a weak acid at concentration c has a lower [H⁺] than a strong acid at the same concentration c. In your answer, distinguish between the terms 'strength' and 'concentration', and explain what the degree of dissociation tells you about a weak acid.",
        apply:      "Calculate the pH of: (a) 0.0500 mol dm⁻³ HCl; (b) 0.0200 mol dm⁻³ Ba(OH)₂ (assume complete dissociation; Ba(OH)₂ is dibasic); (c) 0.200 mol dm⁻³ propanoic acid (Ka = 1.34 × 10⁻⁵ mol dm⁻³). For part (c) show the complete working including the approximation, the verification, and the final pH to 2 decimal places.",
        analyze:    "A weak acid HX has Ka = 4.70 × 10⁻⁴ mol dm⁻³ at 25°C. (a) Calculate the pH of 0.150 mol dm⁻³ HX. (b) Calculate the degree of dissociation. (c) The same acid is diluted to 0.0100 mol dm⁻³. Calculate the new pH and new degree of dissociation. (d) Analyse the trend: what happens to pH and to degree of dissociation as the acid is diluted? Explain both trends using equilibrium principles.",
        evaluate:   "A student calculates the pH of 0.0400 mol dm⁻³ NaOH as follows: pH = −log(0.0400) = 1.40. Evaluate this calculation — identify all errors, state what each error is, and provide the complete correct working to arrive at the correct pH value.",
        create:     "Derive the expression [H⁺] = √(Ka × c) for a weak acid HA from the Ka equilibrium expression, clearly stating the approximation made at each step and the mathematical condition under which it is valid. Then derive the quadratic form of the equation for cases where the approximation breaks down. Test both expressions for Ka = 1.00 × 10⁻³ mol dm⁻³, c = 0.0100 mol dm⁻³, and compare the results to determine whether the approximation is acceptable in this case."
    },

    buffers: {
        remember:   "State what a buffer solution is and list the two components of (a) an acidic buffer and (b) an alkaline buffer. Write the Henderson–Hasselbalch equation. State the pH of a buffer solution when [HA] = [A⁻], explaining why this is the case.",
        understand: "Explain how an ethanoate buffer (CH₃COOH / CH₃COO⁻) resists pH change when (a) a small volume of hydrochloric acid is added and (b) a small volume of sodium hydroxide is added. Write equations for both processes. Explain why the buffer is eventually overwhelmed if a very large amount of acid or alkali is added.",
        apply:      "(a) Calculate the pH of a buffer prepared by mixing 40.0 cm³ of 0.200 mol dm⁻³ ethanoic acid with 60.0 cm³ of 0.200 mol dm⁻³ sodium ethanoate. Ka(CH₃COOH) = 1.74 × 10⁻⁵ mol dm⁻³. (b) Calculate the new pH after adding 5.00 cm³ of 0.100 mol dm⁻³ HCl to this buffer. Show all mole balance steps and use Henderson–Hasselbalch for the final calculation.",
        analyze:    "Three buffer solutions are prepared using ethanoic acid (pKa = 4.76) with different ratios of [CH₃COO⁻]/[CH₃COOH]: Buffer A = 0.1:1; Buffer B = 1:1; Buffer C = 10:1. (a) Calculate the pH of each buffer. (b) 0.010 mol of HCl is added to 1.00 dm³ of each buffer. Calculate the new pH for each. (c) Analyse which buffer shows the smallest pH change and explain in terms of reservoir availability.",
        evaluate:   "A student prepares a 'buffer' by mixing 100 cm³ of 0.100 mol dm⁻³ HCl with 100 cm³ of 0.100 mol dm⁻³ NaOH. She claims the resulting solution is a buffer because it contains both an acid (HCl) and a base (NaOH). Evaluate this claim — identify whether the solution is indeed a buffer, explain what has formed, calculate the pH of the resulting solution, and explain what chemical components would actually be required to make a buffer at approximately this pH.",
        create:     "Design the preparation of an acetate buffer at pH 5.20 using ethanoic acid (pKa = 4.76) and sodium ethanoate in 500 cm³ total volume. Your design must include: (a) the required [A⁻]/[HA] ratio from Henderson–Hasselbalch; (b) the moles and mass of each component to dissolve (Mr(CH₃COONa) = 82.0 g mol⁻¹; Mr(CH₃COOH) = 60.1 g mol⁻¹) for a total acetate concentration of 0.200 mol dm⁻³; (c) an explanation of why the total concentration was specified and how it affects capacity but not pH."
    },

    titrations: {
        remember:   "State the difference between equivalence point and end point in a titration. Name a suitable indicator for (a) strong acid–strong base titration and (b) weak acid–strong base titration, giving the colour change for each. State the pH at the equivalence point for a strong acid–strong base titration and explain why it is not the same for a weak acid–strong base titration.",
        understand: "Explain why the equivalence point of the titration of ethanoic acid with NaOH occurs at a pH greater than 7. Your answer must include: (a) the ionic equation for the reaction at the equivalence point; (b) the hydrolysis equation showing why the salt solution is alkaline; (c) the reason phenolphthalein is suitable and methyl orange is not, with reference to their colour change ranges.",
        apply:      "(a) 20.0 cm³ of 0.150 mol dm⁻³ H₂SO₄ is titrated against 0.200 mol dm⁻³ NaOH. Calculate the volume of NaOH required to reach the equivalence point. (H₂SO₄ is diprotic: H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O.) (b) 25.0 cm³ of 0.100 mol dm⁻³ ethanoic acid is titrated with 0.100 mol dm⁻³ NaOH. Calculate the pH at (i) the start; (ii) the half-equivalence point; (iii) 1.00 cm³ before the equivalence point. Ka(CH₃COOH) = 1.74 × 10⁻⁵ mol dm⁻³.",
        analyze:    "A student titrates an unknown monoprotic weak acid (25.0 cm³, concentration unknown) with 0.200 mol dm⁻³ NaOH. The following pH readings are recorded: at 5.00 cm³ NaOH, pH = 4.15; at 10.0 cm³ NaOH, pH = 4.68; at 15.0 cm³ NaOH, pH = 5.22; equivalence point at 20.0 cm³ NaOH (pH = 9.1). (a) Determine pKa and Ka of the unknown acid. (b) Calculate the initial concentration of the acid. (c) State and justify which indicator should be used. (d) Determine whether the acid is stronger or weaker than ethanoic acid (pKa = 4.76).",
        evaluate:   "A student titrates 25.0 cm³ of 0.100 mol dm⁻³ HCl with 0.100 mol dm⁻³ NH₃ solution using phenolphthalein indicator and records a titre of 30.2 cm³ (expected 25.0 cm³). Evaluate the student's choice of indicator for this titration — state the expected equivalence point pH (explaining why it is below 7), explain why the titre is too large, calculate the systematic error in calculated [HCl], and state the correct indicator choice.",
        create:     "Construct a fully annotated titration curve for the addition of 0.100 mol dm⁻³ NaOH to 25.0 cm³ of 0.100 mol dm⁻³ propanoic acid (pKa = 4.87). Your answer must include: (a) a labelled sketch of the curve with correctly calculated pH values at the starting point, half-equivalence point, equivalence point, and 5 cm³ past the equivalence point; (b) identification of the buffer region and its pH range; (c) identification of the correct indicator with justification; (d) explanation of why the curve shape differs from a strong acid–strong base titration curve."
    }
},

stoichiometry: {
    molesAndMass: {
        remember:   "State the equation linking moles (n), mass (m), and molar mass (M). Define the term 'mole' and give the value of Avogadro's constant with its unit. State the equations for percentage yield and atom economy.",
        understand: "Explain why the limiting reagent — and not the reagent present in the larger amount — determines the theoretical yield of a reaction. In your answer, use a specific balanced equation to illustrate the point and explain what happens to the excess reagent.",
        apply:      "Iron reacts with sulfur according to: Fe(s) + S(s) → FeS(s). 5.00 g of iron is mixed with 4.00 g of sulfur and heated. (a) Identify the limiting reagent, showing all working. (b) Calculate the theoretical yield of FeS in grams. (c) Calculate the mass of the excess reagent that remains unreacted. (Ar: Fe = 55.8, S = 32.1)",
        analyze:    "Complete combustion of 1.40 g of a compound X (containing only C, H, and O) produces 2.64 g of CO₂ and 1.08 g of H₂O. (a) Calculate the moles and masses of C and H in the sample. (b) Determine the mass of O by subtraction. (c) Find the mole ratio C : H : O and determine the empirical formula. (d) Given that Mr(X) = 60.1, determine the molecular formula. (Ar: C = 12.0, H = 1.0, O = 16.0)",
        evaluate:   "A student synthesises magnesium oxide by burning 2.40 g of magnesium ribbon: 2Mg + O₂ → 2MgO. They collect 3.80 g of MgO. They calculate the percentage yield as: % yield = (3.80 / 2.40) × 100 = 158%. Evaluate this calculation fully — identify every error the student made in the calculation and in their reasoning, state the correct theoretical yield, and calculate the correct percentage yield. (Ar: Mg = 24.3, O = 16.0)",
        create:     "A pharmaceutical company produces ibuprofen (C₁₃H₁₈O₂, Mr = 206.3) via two routes. Route A: single-step synthesis, 78% yield, atom economy 40.2%. Route B: three-step synthesis, individual step yields of 90%, 85%, and 88%; atom economies of 60%, 75%, and 95%. (a) Calculate the overall percentage yield for Route B. (b) Calculate the overall atom economy for Route B (assume equal molar masses throughout or use the given step values as proxies). (c) Recommend which route is preferable for industrial use, considering both metrics and any other relevant factors."
    },

    concentration: {
        remember:   "Write the equation linking concentration (c), moles (n), and volume (V). State the SI unit of concentration. Define the term 'standard solution'. State what piece of glassware is used to prepare a standard solution and why.",
        understand: "Explain why a volumetric flask must be used — rather than a beaker or measuring cylinder — when preparing a standard solution of exact known concentration. In your answer, refer to the tolerance of each piece of glassware and how this affects concentration accuracy.",
        apply:      "Describe, with all calculations, the preparation of 250.0 cm³ of 0.0500 mol dm⁻³ sodium carbonate solution (Na₂CO₃) from solid sodium carbonate. Include: (a) the mass of Na₂CO₃ to be weighed; (b) a step-by-step procedure; (c) the glassware required at each step and why. (Ar: Na = 23.0, C = 12.0, O = 16.0)",
        analyze:    "A student dilutes 20.0 cm³ of a stock NaOH solution to 200.0 cm³ in a volumetric flask. A 25.0 cm³ portion of the diluted solution is titrated with 0.0500 mol dm⁻³ HCl, requiring 18.75 cm³ at the equivalence point (HCl + NaOH → NaCl + H₂O). (a) Calculate the concentration of the diluted NaOH solution. (b) Calculate the concentration of the original stock NaOH solution. (c) State one source of uncertainty in this procedure and indicate whether it would cause a systematic positive or negative error in the calculated concentration.",
        evaluate:   "A student prepares a 0.100 mol dm⁻³ NaCl solution by dissolving 5.85 g of NaCl in 100 cm³ of water (not 900 cm³, to make 1 litre), then transferring all the solution to a 1 dm³ flask and adding water to the mark. Evaluate whether this procedure produces a solution of exactly 0.100 mol dm⁻³. Identify: (a) the correct mass of NaCl required for exactly 0.100 mol dm⁻³ in 1 dm³; (b) whether the student's mass is correct; (c) a procedural error the student made even if the mass were correct; (d) the correct procedure. (Ar: Na = 23.0, Cl = 35.5)",
        create:     "Design a complete experimental procedure to prepare 1.00 dm³ of 0.100 mol dm⁻³ sulfuric acid (H₂SO₄) from a concentrated stock solution labelled '98.0% H₂SO₄ by mass, density 1.84 g cm⁻³'. Include: (a) calculation of the volume of concentrated acid required; (b) step-by-step mixing procedure with safety precautions (state which liquid is added to which and why); (c) apparatus list with justification; (d) one source of systematic error and how you would minimise it. (Mr: H₂SO₄ = 98.1)"
    },

    gasStoichiometry: {
        remember:   "State the molar volume of a gas at (a) RTP and (b) STP, including units. Write the ideal gas equation and define each term, including the value and units of the gas constant R. State Avogadro's law as it applies to gas volumes.",
        understand: "Explain why one mole of hydrogen gas (M = 2.0 g mol⁻¹) and one mole of carbon dioxide gas (M = 44.0 g mol⁻¹) occupy the same volume at the same temperature and pressure, even though their molar masses differ by a factor of 22. Your answer must reference kinetic theory and the nature of gas pressure.",
        apply:      "Calcium carbonate reacts with excess hydrochloric acid: CaCO₃(s) + 2HCl(aq) → CaCl₂(aq) + H₂O(l) + CO₂(g). (a) Calculate the volume of CO₂ (at RTP) produced from 5.00 g of CaCO₃. (b) Using pV = nRT, calculate the volume of CO₂ at 50°C and 120 kPa. Express your answer in dm³. (Ar: Ca = 40.1, C = 12.0, O = 16.0; R = 8.314 J mol⁻¹ K⁻¹)",
        analyze:    "A 0.250 g sample of a pure unknown gas is found to occupy 143 cm³ at 25°C and 100 kPa. (a) Using pV = nRT, calculate the moles of the gas. (b) Calculate the molar mass of the gas. (c) Given that the gas contains only carbon and hydrogen and has a degree of unsaturation consistent with one C=C bond, identify the gas and write its molecular formula. (R = 8.314 J mol⁻¹ K⁻¹; Ar: C = 12.0, H = 1.0)",
        evaluate:   "A student uses the molar volume at STP (22.4 dm³ mol⁻¹) to calculate the moles of gas in a 500 cm³ sample collected at 25°C and 1.00 atm, obtaining n = 0.500/22.4 = 0.0223 mol. A second student uses pV = nRT and obtains n = 0.0204 mol. Evaluate both calculations — identify which is correct and why, explain the source of error in the first calculation, and calculate the percentage error introduced by using the wrong molar volume.",
        create:     "Derive the value of the molar volume of an ideal gas at RTP (25°C, 101325 Pa) from the ideal gas equation pV = nRT, showing all working and unit conversions. Then derive the molar volume at STP (0°C, 101325 Pa) and explain quantitatively why the STP value is smaller than the RTP value in terms of kinetic theory."
    },

    titrations: {
        remember:   "State the difference between the equivalence point and the end point of a titration. State two indicators suitable for acid-base titrations, giving the colour change at the end point for each. State what is meant by a 'concordant titre' and how many are required for a reliable result.",
        understand: "Explain why phenolphthalein is a more appropriate indicator than methyl orange for the titration of sodium hydroxide (strong base) against ethanoic acid (weak acid). Your answer must include: (a) the approximate pH at the equivalence point; (b) the transition range of each indicator; (c) the consequence of using the wrong indicator on the titre value.",
        apply:      "25.0 cm³ of potassium hydroxide (KOH) solution is titrated against 0.200 mol dm⁻³ sulfuric acid (H₂SO₄). The mean concordant titre is 15.65 cm³. Equation: H₂SO₄ + 2KOH → K₂SO₄ + 2H₂O. (a) Calculate the moles of H₂SO₄ used. (b) Apply the mole ratio to find the moles of KOH. (c) Calculate the concentration of the KOH solution in mol dm⁻³.",
        analyze:    "A back titration is used to determine the percentage purity of a sample of anhydrous sodium carbonate (Na₂CO₃) that may contain inert impurities. 2.86 g of the sample is dissolved and reacted with 50.0 cm³ of 1.00 mol dm⁻³ HCl (excess). The mixture is titrated with 0.500 mol dm⁻³ NaOH, requiring 12.40 cm³. Equations: Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂; NaOH + HCl → NaCl + H₂O. (a) Calculate the moles of HCl added initially. (b) Calculate the moles of excess HCl titrated by NaOH. (c) Calculate the moles of HCl that reacted with Na₂CO₃. (d) Calculate the mass and percentage purity of Na₂CO₃ in the sample. (Mr: Na₂CO₃ = 106.0)",
        evaluate:   "A student determines the concentration of an ethanoic acid solution by titrating with 0.100 mol dm⁻³ NaOH using methyl orange indicator. The titration requires 24.50 cm³ of NaOH for 25.0 cm³ of acid, and the student calculates c(CH₃COOH) = 0.0980 mol dm⁻³. Evaluate this experiment fully — assess: (a) the suitability of methyl orange for this titration with reference to the equivalence point pH; (b) whether the titre obtained is likely to be too high, too low, or accurate as a result of the indicator choice; (c) the direction of error in the calculated concentration; (d) what indicator should have been used and why.",
        create:     "Design a complete titration procedure to determine the percentage of aspirin (C₉H₈O₄, Mr = 180.2) in a commercial tablet that also contains inert binders. Aspirin reacts with NaOH in a 1:1 molar ratio. Include: (a) how you would dissolve the tablet and prepare it for titration; (b) the concentration and approximate volume of NaOH solution you would use and how you determined these; (c) your choice of indicator and justification; (d) how you would ensure concordant titres; (e) the full calculation procedure from titre to percentage aspirin; (f) one systematic error and how you would correct for it."
    }
},


dynamicEquilibrium: {
    equilibriumConcept: {
        remember:   "Define dynamic equilibrium. State two conditions that must be met for a reversible reaction to reach dynamic equilibrium. Write the Kc expression for the reaction: 2SO₂(g) + O₂(g) ⇌ 2SO₃(g). State the units of Kc for this expression.",
        understand: "Explain, at the molecular level, why the concentrations of reactants and products remain constant at dynamic equilibrium even though the reaction continues in both directions. Include a description of how the forward and reverse rates change from the start of reaction until equilibrium is reached.",
        apply:      "A sealed flask initially contains 0.800 mol dm⁻³ N₂O₄(g). At equilibrium at 25°C, [NO₂] = 0.0480 mol dm⁻³ for the reaction N₂O₄(g) ⇌ 2NO₂(g). Construct a full ICE table, calculate all equilibrium concentrations, and calculate Kc including units.",
        analyze:    "The Kc values for a reaction at three temperatures are: 298 K: 1.3 × 10⁻²; 373 K: 4.8 × 10⁻¹; 448 K: 7.2. Analyse this data to determine: (a) whether the forward reaction is exothermic or endothermic; (b) at which temperature products are most favoured; (c) what would happen to the equilibrium position if the system at 298 K were suddenly heated to 448 K.",
        evaluate:   "Evaluate the following student statement: 'At equilibrium, the concentrations of products and reactants are equal because the forward and reverse reactions have cancelled each other out and no further reaction occurs.' Identify all conceptual errors in this statement, explain what dynamic equilibrium actually means, and describe one piece of experimental evidence that demonstrates reactions continue at equilibrium.",
        create:     "Design a laboratory experiment to demonstrate dynamic equilibrium using the N₂O₄ / NO₂ system (N₂O₄ is colourless; NO₂ is brown). Specify: initial conditions; how you would establish equilibrium; how you would perturb the system (minimum two different perturbations); what observations you would expect; and how each observation demonstrates both Le Chatelier's principle and the dynamic (not static) nature of equilibrium."
    },

    leChatelierPrinciple: {
        remember:   "State Le Chatelier's principle. For the reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g)  ΔH = −92 kJ mol⁻¹: state the effect on equilibrium position of (a) increasing [N₂]; (b) increasing pressure; (c) increasing temperature; (d) adding an iron catalyst. For each, state whether Kc changes.",
        understand: "Explain why a catalyst does not change the value of Kc or the equilibrium position for the reaction 2SO₂(g) + O₂(g) ⇌ 2SO₃(g). Your answer must reference activation energy, the rates of the forward and reverse reactions, and the definition of Kc.",
        apply:      "For the reaction PCl₅(g) ⇌ PCl₃(g) + Cl₂(g)  ΔH = +88 kJ mol⁻¹: predict and explain the effect on equilibrium position and on Kc of (a) increasing the temperature from 300°C to 400°C; (b) increasing the pressure by halving the volume; (c) removing PCl₃ as it forms; (d) adding an inert gas at constant volume. Justify each prediction using Le Chatelier's principle and state clearly for each whether Kc changes.",
        analyze:    "A reaction vessel contains an equilibrium mixture of H₂(g), I₂(g), and HI(g) at 425°C: Kc = 54 for H₂(g) + I₂(g) ⇌ 2HI(g). The concentrations are: [H₂] = 0.400 mol dm⁻³; [I₂] = 0.400 mol dm⁻³; [HI] = 1.700 mol dm⁻³. (a) Calculate the reaction quotient Q. (b) Compare Q to Kc = 54. (c) Determine the direction the reaction will proceed to reach equilibrium. (d) Explain why Q ≠ Kc in terms of what the reaction quotient represents.",
        evaluate:   "A student claims: 'Increasing the pressure in the reaction H₂(g) + I₂(g) ⇌ 2HI(g) will shift the equilibrium to the right and increase the yield of HI, because more pressure always drives more product formation.' Evaluate this claim fully — identify the specific error in applying Le Chatelier's principle to this reaction, explain the correct analysis, and state the actual effect of increasing pressure on this system.",
        create:     "Construct a comprehensive analysis of the following industrial dilemma: the reaction A(g) + 2B(g) ⇌ 2C(g)  ΔH = −150 kJ mol⁻¹ is used industrially to produce C. Currently the process runs at 500°C, 100 atm, with a metal catalyst, giving 30% yield per pass. A competitor claims running at 200°C, 400 atm, with an improved catalyst would give 85% yield per pass. Formulate a complete analysis covering: (a) the thermodynamic basis for each set of conditions; (b) the kinetic implications; (c) the engineering and economic considerations; (d) your recommendation with justification."
    },

    equilibriumConstant: {
        remember:   "Write the Kc expression for each of the following reactions, including units: (a) N₂(g) + 3H₂(g) ⇌ 2NH₃(g); (b) CH₃COOH(l) + C₂H₅OH(l) ⇌ CH₃COOC₂H₅(l) + H₂O(l); (c) CaCO₃(s) ⇌ CaO(s) + CO₂(g). State which factor is the only one that changes the value of Kc.",
        understand: "Explain why the value of Kc for the reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g) decreases when temperature is increased from 300°C to 500°C. Your answer must reference the sign of ΔH for the forward reaction, the direction of the Le Chatelier shift, and what a decrease in Kc means for the equilibrium composition.",
        apply:      "0.300 mol of ethanoic acid and 0.500 mol of ethanol are mixed in a 2.00 dm³ flask at 60°C. At equilibrium, 0.250 mol of ethyl ethanoate has formed. CH₃COOH(l) + C₂H₅OH(l) ⇌ CH₃COOC₂H₅(l) + H₂O(l). Construct a complete ICE table using concentrations, calculate Kc, determine its units, and calculate the percentage yield of ethyl ethanoate.",
        analyze:    "Kc for the reaction 2NO₂(g) ⇌ N₂O₄(g) has the following values: 273 K: 1.3 × 10³ mol⁻¹ dm³; 298 K: 1.7 × 10² mol⁻¹ dm³; 323 K: 3.8 × 10¹ mol⁻¹ dm³. (a) Analyse the trend to determine the sign of ΔH for the forward reaction 2NO₂ → N₂O₄. (b) Calculate the ratio Kc(273 K) / Kc(323 K) and interpret its magnitude. (c) At 298 K, a mixture contains [NO₂] = 0.100 mol dm⁻³ and [N₂O₄] = 0.800 mol dm⁻³. Calculate Q and determine whether the system is at equilibrium; if not, state which direction it will react.",
        evaluate:   "A student calculates Kc for the reaction H₂(g) + I₂(g) ⇌ 2HI(g) as follows: equilibrium concentrations are [H₂] = 0.200 mol dm⁻³, [I₂] = 0.200 mol dm⁻³, [HI] = 0.800 mol dm⁻³. The student writes: Kc = (2 × 0.800) / (0.200 × 0.200) = 1.600 / 0.0400 = 40. Evaluate this calculation — identify the error, explain the correct method, and calculate the correct value of Kc with units.",
        create:     "Derive a general algebraic expression for the equilibrium yield fraction (α = moles of product formed / maximum possible moles of product) for the simple equilibrium A(g) ⇌ B(g), starting with 1 mol A in a 1 dm³ vessel. Express α as a function of Kc. Then extend your derivation to the case where the reaction is A(g) ⇌ 2B(g), identifying where the algebra becomes more complex and how a quadratic equation arises. Solve the quadratic case for Kc = 4.0 mol dm⁻³."
    },

    industrialEquilibrium: {
        remember:   "State the conditions (temperature, pressure, catalyst) used in (a) the Haber process and (b) the Contact process. For each, write the equation for the equilibrium reaction including ΔH and state symbols. State the purpose of each industrial process (what product is made and what it is used for).",
        understand: "Explain why the Haber process uses a temperature of approximately 450°C rather than 200°C, even though the lower temperature would give a higher equilibrium yield of ammonia. Your answer must address both the kinetic argument (rate of reaction) and the thermodynamic argument (equilibrium position and Kc), and explain how the compromise temperature attempts to satisfy both requirements.",
        apply:      "The Contact process reaction 2SO₂(g) + O₂(g) ⇌ 2SO₃(g)  ΔH = −196 kJ mol⁻¹ is carried out at 450°C and ~1 atm. (a) Explain the choice of temperature using both rate and equilibrium arguments. (b) Explain why the pressure used (~1 atm) is much lower than in the Haber process, even though increasing pressure would thermodynamically favour SO₃ production. (c) Write the Kc expression for the Contact process equilibrium and state its units. (d) State what would happen to Kc if the temperature were raised to 600°C.",
        analyze:    "The table below shows the approximate equilibrium yield of NH₃ at various temperatures and pressures in the Haber process: [200 atm / 400°C: 36%], [200 atm / 450°C: 15%], [200 atm / 500°C: 9%], [400 atm / 450°C: 25%], [600 atm / 450°C: 35%]. Analyse these data to: (a) determine the effect of temperature on yield at constant pressure and connect this to ΔH; (b) determine the effect of pressure on yield at constant temperature and connect this to gas mole counts; (c) identify the conditions that give highest yield per pass and explain why these are not used commercially.",
        evaluate:   "Evaluate the following claim about the Haber process: 'The iron catalyst used in the Haber process increases the yield of ammonia per pass by shifting the equilibrium to the right. Without the catalyst, the yield at 450°C and 200 atm would be much lower than 15%.' Identify every error in this claim, explain what the iron catalyst actually does and does not do, and state what the yield would be at 450°C and 200 atm without a catalyst (compared to with a catalyst).",
        create:     "Formulate a complete design proposal for a hypothetical industrial process to manufacture methanol via the reaction CO(g) + 2H₂(g) ⇌ CH₃OH(g)  ΔH = −91 kJ mol⁻¹. Your proposal must include: (a) recommended temperature range with thermodynamic and kinetic justification; (b) recommended pressure with Le Chatelier analysis of gas moles; (c) type of catalyst (state what properties would be required); (d) a strategy for maximising overall yield based on product removal or recycle; (e) one environmental or safety consideration specific to this process. For each recommendation, state the principle invoked and justify the choice."
    }
},

hydrocarbons: {
    hydrocarbonBasics: {
        remember:   "State the general formula for: (a) alkanes; (b) alkenes; (c) cycloalkanes. Name the first five straight-chain members of the alkane homologous series and give the molecular formula of each.",
        understand: "Explain why pentane (bp 36°C) has a higher boiling point than 2,2-dimethylpropane (bp 9.5°C), despite both having the molecular formula C₅H₁₂. Your answer must reference molecular geometry, surface area, and intermolecular forces.",
        apply:      "Name the following compound using full IUPAC rules, showing all working: CH₃–CH(CH₃)–CH(C₂H₅)–CH₂–CH₃. Identify the longest chain, justify your numbering, and name all substituents in the correct order.",
        analyze:    "Four alkanes have boiling points: methane −162°C, ethane −89°C, propane −42°C, butane −1°C. Plot these values mentally against carbon number. Analyse the trend and calculate the approximate average increase in boiling point per CH₂ unit. Identify the intermolecular force responsible and explain why it increases with chain length.",
        evaluate:   "A student states: 'All isomers of C₅H₁₂ have the same boiling point because they have the same molecular formula, number of electrons, and therefore identical London dispersion forces.' Evaluate this claim fully — identify the specific error in reasoning, explain which structural feature the student has not accounted for, and give a specific example from C₅H₁₂ isomers to refute the claim.",
        create:     "Design a series of three chemical tests that would allow you to distinguish with certainty between hexane, hex-1-ene, and benzene — three colourless, insoluble liquids. For each test: state the reagent and conditions; predict the observation for each compound; and give the chemical reason for each observation. Explain why no single test alone is conclusive."
    },

    alkaneReactivity: {
        remember:   "State the three stages of free-radical substitution. Write the overall equation for the reaction of methane with chlorine under UV light. State what type of bond fission occurs in the initiation step and define this term.",
        understand: "Explain why the free-radical chlorination of methane produces a mixture of CH₃Cl, CH₂Cl₂, CHCl₃, and CCl₄, even if Cl₂ is present in limited amounts. Your answer must reference the propagation mechanism and how each substituted product can itself undergo further substitution.",
        apply:      "Write the complete free-radical mechanism for the bromination of ethane under UV light, including: (a) the initiation step with correct bond fission type; (b) both propagation steps with balanced equations; (c) all three possible termination steps. State which termination step explains the presence of traces of butane in the product mixture.",
        analyze:    "Free-radical chlorination of propane produces a mixture of 1-chloropropane and 2-chloropropane in an approximately 45:55 ratio (statistical prediction from H atom counts would predict 75:25). Analyse why the observed ratio differs from the statistical prediction. In your answer, consider the relative stability of primary and secondary radicals and the selectivity of the chlorine radical.",
        evaluate:   "Evaluate the following student mechanism for the propagation step of methane chlorination: 'Cl⁻ + CH₄ → CH₃⁻ + HCl.' Identify all errors in this equation — state whether each species is correct, identify what type of mechanism has been incorrectly applied, and rewrite the correct propagation step with appropriate species and curly arrow description.",
        create:     "Design a complete experiment to investigate whether UV light intensity affects the rate of free-radical chlorination of cyclohexane. Include: (a) independent and dependent variables; (b) how you would control all other variables; (c) how you would measure the rate of reaction; (d) what you would expect to find and the mechanistic reason; (e) one safety consideration specific to this reaction and how you would address it."
    },

    alkeneCycloalkane: {
        remember:   "List the four addition reactions of alkenes covered in this topic. For each, state the reagent(s), conditions, and the product formed. State which reaction is used as a chemical test for unsaturation and what observation confirms a positive result.",
        understand: "Explain at the mechanistic level why alkenes undergo electrophilic addition rather than free-radical substitution under standard laboratory conditions. Your answer must reference the electron density of the π bond and why this makes it susceptible to electrophilic attack.",
        apply:      "Draw the full curly arrow mechanism for the addition of HBr to but-1-ene. (a) Show both possible carbocation intermediates. (b) Identify the major and minor products, justifying your choice using carbocation stability. (c) Name both products using IUPAC nomenclature.",
        analyze:    "An unknown compound with molecular formula C₄H₈ is found to: (i) rapidly decolourise bromine water; (ii) show two peaks by ¹H NMR; (iii) exist as two geometric isomers. Deduce the structure, draw both geometric isomers, and explain why the molecular formula C₄H₈ alone is insufficient to identify the compound (state how many structural isomers are consistent with C₄H₈).",
        evaluate:   "Evaluate the claim: 'The major product of HBr addition to propene is 1-bromopropane because, according to Markovnikov's rule, the bromine atom adds to the carbon bearing fewer hydrogen atoms.' Identify every error in this statement — address: (a) which atom adds where; (b) what Markovnikov's rule actually states; (c) which product is actually the major product and why, using carbocation stability as your justification.",
        create:     "Propose a two-step synthetic route to produce 2-bromopropane starting from propane. For each step: state the reagents and conditions; write the balanced equation; draw the mechanism (or state it is free-radical substitution and write all stages); identify any major and minor products. Explain why the two-step route via propene is preferred over direct bromination of propane if high selectivity for 2-bromopropane is required."
    },

    aromaticity: {
        remember:   "State three pieces of evidence that contradict the Kekulé structure of benzene. Write the equation for the nitration of benzene, including all reagents, conditions, and the equation for the generation of the nitronium ion (NO₂⁺).",
        understand: "Explain why benzene undergoes electrophilic aromatic substitution rather than electrophilic addition. Your answer must include: (a) a description of the delocalised π system; (b) the thermodynamic argument using delocalisation energy; (c) why substitution preserves aromaticity while addition would destroy it.",
        apply:      "Draw the complete curly arrow mechanism for the nitration of benzene. Include: (a) the equation generating NO₂⁺ from concentrated HNO₃ and H₂SO₄; (b) attack of NO₂⁺ on the benzene ring showing the arenium ion intermediate; (c) loss of H⁺ to restore aromaticity. Label the arenium ion and state whether it is aromatic.",
        analyze:    "The following thermochemical data are provided: cyclohexene + H₂ → cyclohexane, ΔH = −120 kJ/mol; benzene + 3H₂ → cyclohexane, ΔH = −208 kJ/mol. (a) Calculate the predicted enthalpy of hydrogenation for cyclohexatriene (Kekulé benzene). (b) Calculate the delocalisation energy of benzene. (c) Analyse what this value tells you about the bonding in benzene compared to the Kekulé model, and connect it to benzene's preference for substitution over addition.",
        evaluate:   "Evaluate the following student response to 'Why does benzene not decolourise bromine water?': 'Benzene does not react with bromine water because it is non-polar and does not mix with water, so the bromine cannot contact the benzene molecules.' Identify all errors in this reasoning — address: (a) whether polarity and miscibility are the actual reason; (b) what the actual chemical reason is; (c) what would happen if bromine in an organic solvent were used instead; (d) what catalyst would be needed for bromination to occur.",
        create:     "Construct a logical argument — from three independent lines of evidence — that demonstrates benzene cannot be represented as cyclohexatriene (Kekulé structure) and must instead have a delocalised π system. For each piece of evidence: state the observation or data; state what the Kekulé structure predicts; explain the discrepancy; and state what the delocalised model predicts instead. Conclude by calculating the delocalisation energy from the thermochemical data above."
    }

   }
};



}

const EndSection6 = "close"